// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var BaselineType;
(function (BaselineType) {
    BaselineType[BaselineType["MEAN"] = 0] = "MEAN";
    BaselineType[BaselineType["UNKNOWN1"] = 1] = "UNKNOWN1";
    BaselineType[BaselineType["UNKNOWN2"] = 2] = "UNKNOWN2";
    BaselineType[BaselineType["UNKNOWN3"] = 3] = "UNKNOWN3";
    BaselineType[BaselineType["UNKNOWN4"] = 4] = "UNKNOWN4";
    BaselineType[BaselineType["UNKNOWN5"] = 5] = "UNKNOWN5";
})(BaselineType || (BaselineType = {}));
