// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Certainty {
  UNKNOWN = 0,
  OBSERVED = 1,
  LIKELY = 2,
  POSSIBLE = 3,
  UNLIKELY = 4,
  UNKNOWN5 = 5
}
