// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var Certainty;
(function (Certainty) {
    Certainty[Certainty["UNKNOWN"] = 0] = "UNKNOWN";
    Certainty[Certainty["UNKNOWN1"] = 1] = "UNKNOWN1";
    Certainty[Certainty["LIKELY"] = 2] = "LIKELY";
    Certainty[Certainty["POSSIBLE"] = 3] = "POSSIBLE";
    Certainty[Certainty["UNKNOWN4"] = 4] = "UNKNOWN4";
    Certainty[Certainty["UNKNOWN5"] = 5] = "UNKNOWN5";
})(Certainty || (Certainty = {}));
