// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var ChangeTrend;
(function (ChangeTrend) {
    ChangeTrend[ChangeTrend["STEADY"] = 0] = "STEADY";
    ChangeTrend[ChangeTrend["INC"] = 1] = "INC";
    ChangeTrend[ChangeTrend["DEC"] = 2] = "DEC";
    ChangeTrend[ChangeTrend["UNKNOWN3"] = 3] = "UNKNOWN3";
    ChangeTrend[ChangeTrend["UNKNOWN4"] = 4] = "UNKNOWN4";
    ChangeTrend[ChangeTrend["UNKNOWN5"] = 5] = "UNKNOWN5";
    ChangeTrend[ChangeTrend["UNKNOWN6"] = 6] = "UNKNOWN6";
})(ChangeTrend || (ChangeTrend = {}));
