// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var ComparisonType;
(function (ComparisonType) {
    ComparisonType[ComparisonType["UNKNOWN"] = 0] = "UNKNOWN";
    ComparisonType[ComparisonType["UNKNOWN1"] = 1] = "UNKNOWN1";
    ComparisonType[ComparisonType["WORSE"] = 2] = "WORSE";
    ComparisonType[ComparisonType["SAME"] = 3] = "SAME";
    ComparisonType[ComparisonType["BETTER"] = 4] = "BETTER";
    ComparisonType[ComparisonType["UNKNOWN5"] = 5] = "UNKNOWN5";
})(ComparisonType || (ComparisonType = {}));
