// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var ComparisonType;
(function (ComparisonType) {
    ComparisonType[ComparisonType["UNKNOWN0"] = 0] = "UNKNOWN0";
    ComparisonType[ComparisonType["TEMPERATURE_MAX"] = 1] = "TEMPERATURE_MAX";
    ComparisonType[ComparisonType["PRECIPITATION"] = 2] = "PRECIPITATION";
})(ComparisonType || (ComparisonType = {}));
