// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var DeviationType;
(function (DeviationType) {
    DeviationType[DeviationType["UNKNOWN0"] = 0] = "UNKNOWN0";
    DeviationType[DeviationType["HIGHER"] = 1] = "HIGHER";
    DeviationType[DeviationType["NORMAL"] = 2] = "NORMAL";
    DeviationType[DeviationType["LOWER"] = 3] = "LOWER";
    DeviationType[DeviationType["UNKNOWN4"] = 4] = "UNKNOWN4";
})(DeviationType || (DeviationType = {}));
