// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var Direction;
(function (Direction) {
    Direction[Direction["STEADY"] = 0] = "STEADY";
    Direction[Direction["INC"] = 1] = "INC";
    Direction[Direction["DEC"] = 2] = "DEC";
})(Direction || (Direction = {}));
