// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from "../../../node_modules/flatbuffers/mjs/flatbuffers.js";
export class ForecastDaily {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsForecastDaily(bb, obj) {
        return (obj || new ForecastDaily()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsForecastDaily(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ForecastDaily()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static startForecastDaily(builder) {
        builder.startObject(0);
    }
    static endForecastDaily(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createForecastDaily(builder) {
        ForecastDaily.startForecastDaily(builder);
        return ForecastDaily.endForecastDaily(builder);
    }
}
