// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from "../../../node_modules/flatbuffers/mjs/flatbuffers.js";
export class ForecastHourly {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsForecastHourly(bb, obj) {
        return (obj || new ForecastHourly()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsForecastHourly(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ForecastHourly()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static startForecastHourly(builder) {
        builder.startObject(0);
    }
    static endForecastHourly(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createForecastHourly(builder) {
        ForecastHourly.startForecastHourly(builder);
        return ForecastHourly.endForecastHourly(builder);
    }
}
