// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ForecastToken {
  CLEAR = 0,
  START = 1,
  STOP = 2,
  START_STOP = 3,
  STOP_START = 4,
  CONSTANT = 5
}
