// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
export class ID {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsID(bb, obj) {
        return (obj || new ID()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsID(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ID()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    uuid(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    static startID(builder) {
        builder.startObject(1);
    }
    static addUuid(builder, uuidOffset) {
        builder.addFieldOffset(0, uuidOffset, 0);
    }
    static endID(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createID(builder, uuidOffset) {
        ID.startID(builder);
        ID.addUuid(builder, uuidOffset);
        return ID.endID(builder);
    }
}
