// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ImportanceType {
  NORMAL = 0,
  LOW = 1,
  HIGH = 2,
  UNKNOWN3 = 3,
  UNKNOWN4 = 4,
  UNKNOWN5 = 5
}
