// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var MoonPhase;
(function (MoonPhase) {
    MoonPhase[MoonPhase["NEW"] = 0] = "NEW";
    MoonPhase[MoonPhase["WAXING_CRESCENT"] = 1] = "WAXING_CRESCENT";
    MoonPhase[MoonPhase["FIRST_QUARTER"] = 2] = "FIRST_QUARTER";
    MoonPhase[MoonPhase["WAXING_GIBBOUS"] = 3] = "WAXING_GIBBOUS";
    MoonPhase[MoonPhase["FULL"] = 4] = "FULL";
    MoonPhase[MoonPhase["WANING_GIBBOUS"] = 5] = "WANING_GIBBOUS";
    MoonPhase[MoonPhase["THIRD_QUARTER"] = 6] = "THIRD_QUARTER";
    MoonPhase[MoonPhase["WANING_CRESCENT"] = 7] = "WANING_CRESCENT";
})(MoonPhase || (MoonPhase = {}));
