// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Metadata } from '../wk2/metadata.js';
import { Placement } from '../wk2/placement.js';


export class News {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):News {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNews(bb:flatbuffers.ByteBuffer, obj?:News):News {
  return (obj || new News()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNews(bb:flatbuffers.ByteBuffer, obj?:News):News {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new News()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

metadata(obj?:Metadata):Metadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Metadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

placements(index: number, obj?:Placement):Placement|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Placement()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

placementsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startNews(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMetadata(builder:flatbuffers.Builder, metadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, metadataOffset, 0);
}

static addPlacements(builder:flatbuffers.Builder, placementsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, placementsOffset, 0);
}

static createPlacementsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startPlacementsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endNews(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNews(builder:flatbuffers.Builder, metadataOffset:flatbuffers.Offset, placementsOffset:flatbuffers.Offset):flatbuffers.Offset {
  News.startNews(builder);
  News.addMetadata(builder, metadataOffset);
  News.addPlacements(builder, placementsOffset);
  return News.endNews(builder);
}
}
