// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from "../../../node_modules/flatbuffers/mjs/flatbuffers.js";

export class News {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):News {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsNews(bb:flatbuffers.ByteBuffer, obj?:News):News {
  return (obj || new News()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsNews(bb:flatbuffers.ByteBuffer, obj?:News):News {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new News()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startNews(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endNews(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createNews(builder:flatbuffers.Builder):flatbuffers.Offset {
  News.startNews(builder);
  return News.endNews(builder);
}
}
