// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum PlacementType {
  UNKNOWN0 = 0,
  AIR_QUALITY_DETAILS = 1,
  UNKNOWN2 = 2,
  UNKNOWN3 = 3,
  UNKNOWN4 = 4,
  UNKNOWN5 = 5,
  UNKNOWN6 = 6,
  UNKNOWN7 = 7,
  UNKNOWN8 = 8,
  UNKNOWN9 = 9,
  UNKNOWN10 = 10,
  UNKNOWN11 = 11,
  UV_DETAILS = 12,
  UNKNOWN13 = 13,
  UNKNOWN14 = 14,
  UNKNOWN15 = 15,
  UNKNOWN16 = 16,
  UNKNOWN17 = 17,
  UNKNOWN18 = 18
}
