// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var PollutantType;
(function (PollutantType) {
    PollutantType[PollutantType["NOT_AVAILABLE"] = 0] = "NOT_AVAILABLE";
    PollutantType[PollutantType["C6H6"] = 1] = "C6H6";
    PollutantType[PollutantType["NH3"] = 2] = "NH3";
    PollutantType[PollutantType["NMHC"] = 3] = "NMHC";
    PollutantType[PollutantType["NO"] = 4] = "NO";
    PollutantType[PollutantType["NO2"] = 5] = "NO2";
    PollutantType[PollutantType["NOX"] = 6] = "NOX";
    PollutantType[PollutantType["OZONE"] = 7] = "OZONE";
    PollutantType[PollutantType["PM2_5"] = 8] = "PM2_5";
    PollutantType[PollutantType["SO2"] = 9] = "SO2";
    PollutantType[PollutantType["PM10"] = 10] = "PM10";
    PollutantType[PollutantType["CO"] = 11] = "CO";
    PollutantType[PollutantType["UNKNOWN12"] = 12] = "UNKNOWN12";
    PollutantType[PollutantType["UNKNOWN13"] = 13] = "UNKNOWN13";
})(PollutantType || (PollutantType = {}));
