// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var PrecipitationType;
(function (PrecipitationType) {
    PrecipitationType[PrecipitationType["CLEAR"] = 0] = "CLEAR";
    PrecipitationType[PrecipitationType["RAIN"] = 1] = "RAIN";
    PrecipitationType[PrecipitationType["SNOW"] = 2] = "SNOW";
    PrecipitationType[PrecipitationType["SLEET"] = 3] = "SLEET";
    PrecipitationType[PrecipitationType["HAIL"] = 4] = "HAIL";
    PrecipitationType[PrecipitationType["MIXED"] = 5] = "MIXED";
})(PrecipitationType || (PrecipitationType = {}));
