// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var ResponseType;
(function (ResponseType) {
    ResponseType[ResponseType["UNKNOWN0"] = 0] = "UNKNOWN0";
    ResponseType[ResponseType["UNKNOWN1"] = 1] = "UNKNOWN1";
    ResponseType[ResponseType["UNKNOWN2"] = 2] = "UNKNOWN2";
    ResponseType[ResponseType["UNKNOWN3"] = 3] = "UNKNOWN3";
    ResponseType[ResponseType["UNKNOWN4"] = 4] = "UNKNOWN4";
    ResponseType[ResponseType["UNKNOWN5"] = 5] = "UNKNOWN5";
    ResponseType[ResponseType["MONITOR"] = 6] = "MONITOR";
    ResponseType[ResponseType["UNKNOWN7"] = 7] = "UNKNOWN7";
})(ResponseType || (ResponseType = {}));
