// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var ResponseType;
(function (ResponseType) {
    ResponseType[ResponseType["UNKNOWN0"] = 0] = "UNKNOWN0";
    ResponseType[ResponseType["SHELTER"] = 1] = "SHELTER";
    ResponseType[ResponseType["EVACUATE"] = 2] = "EVACUATE";
    ResponseType[ResponseType["PREPARE"] = 3] = "PREPARE";
    ResponseType[ResponseType["EXECUTE"] = 4] = "EXECUTE";
    ResponseType[ResponseType["AVOID"] = 5] = "AVOID";
    ResponseType[ResponseType["MONITOR"] = 6] = "MONITOR";
    ResponseType[ResponseType["ACCESS"] = 7] = "ACCESS";
    ResponseType[ResponseType["ALLCLEAR"] = 8] = "ALLCLEAR";
    ResponseType[ResponseType["NONE"] = 9] = "NONE";
})(ResponseType || (ResponseType = {}));
