// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var Severity;
(function (Severity) {
    Severity[Severity["UNKNOWN"] = 0] = "UNKNOWN";
    Severity[Severity["EXTREME"] = 1] = "EXTREME";
    Severity[Severity["SEVERE"] = 2] = "SEVERE";
    Severity[Severity["MODERATE"] = 3] = "MODERATE";
    Severity[Severity["MINOR"] = 4] = "MINOR";
    Severity[Severity["UNKNOWN5"] = 5] = "UNKNOWN5";
})(Severity || (Severity = {}));
