// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var SignificanceType;
(function (SignificanceType) {
    SignificanceType[SignificanceType["UNKNOWN"] = 0] = "UNKNOWN";
    SignificanceType[SignificanceType["UNKNOWN1"] = 1] = "UNKNOWN1";
    SignificanceType[SignificanceType["UNKNOWN2"] = 2] = "UNKNOWN2";
    SignificanceType[SignificanceType["UNKNOWN3"] = 3] = "UNKNOWN3";
    SignificanceType[SignificanceType["UNKNOWN4"] = 4] = "UNKNOWN4";
    SignificanceType[SignificanceType["UNKNOWN5"] = 5] = "UNKNOWN5";
    SignificanceType[SignificanceType["UNKNOWN6"] = 6] = "UNKNOWN6";
    SignificanceType[SignificanceType["UNKNOWN7"] = 7] = "UNKNOWN7";
    SignificanceType[SignificanceType["UNKNOWN8"] = 8] = "UNKNOWN8";
    SignificanceType[SignificanceType["UNKNOWN9"] = 9] = "UNKNOWN9";
    SignificanceType[SignificanceType["STATEMENT"] = 10] = "STATEMENT";
    SignificanceType[SignificanceType["UNKNOWN11"] = 11] = "UNKNOWN11";
    SignificanceType[SignificanceType["UNKNOWN12"] = 12] = "UNKNOWN12";
    SignificanceType[SignificanceType["UNKNOWN13"] = 13] = "UNKNOWN13";
})(SignificanceType || (SignificanceType = {}));
