// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum SignificanceType {
  UNKNOWN = 0,
  UNKNOWN1 = 1,
  UNKNOWN2 = 2,
  UNKNOWN3 = 3,
  UNKNOWN4 = 4,
  UNKNOWN5 = 5,
  UNKNOWN6 = 6,
  UNKNOWN7 = 7,
  UNKNOWN8 = 8,
  UNKNOWN9 = 9,
  STATEMENT = 10,
  UNKNOWN11 = 11,
  ADVISORY = 12,
  UNKNOWN13 = 13
}
