// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var SourceType;
(function (SourceType) {
    SourceType[SourceType["APPLE_INTERNAL"] = 0] = "APPLE_INTERNAL";
    SourceType[SourceType["MODELED"] = 1] = "MODELED";
    SourceType[SourceType["STATION"] = 2] = "STATION";
})(SourceType || (SourceType = {}));
