// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum SourceType {
  APPLE_INTERNAL = 0,
  MODELED = 1,
  STATION = 2
}
