// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from "../../../node_modules/flatbuffers/mjs/flatbuffers.js";

import { PrecipitationType } from '../wk2/precipitation-type.js';


export class Summary {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Summary {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSummary(bb:flatbuffers.ByteBuffer, obj?:Summary):Summary {
  return (obj || new Summary()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSummary(bb:flatbuffers.ByteBuffer, obj?:Summary):Summary {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Summary()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

startTime():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

endTime():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint32(this.bb_pos + offset) : 0;
}

condition():PrecipitationType {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : PrecipitationType.CLEAR;
}

precipitationChance():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : 0;
}

precipitationIntensity():number {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startSummary(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addStartTime(builder:flatbuffers.Builder, startTime:number) {
  builder.addFieldInt32(0, startTime, 0);
}

static addEndTime(builder:flatbuffers.Builder, endTime:number) {
  builder.addFieldInt32(1, endTime, 0);
}

static addCondition(builder:flatbuffers.Builder, condition:PrecipitationType) {
  builder.addFieldInt8(2, condition, PrecipitationType.CLEAR);
}

static addPrecipitationChance(builder:flatbuffers.Builder, precipitationChance:number) {
  builder.addFieldInt8(3, precipitationChance, 0);
}

static addPrecipitationIntensity(builder:flatbuffers.Builder, precipitationIntensity:number) {
  builder.addFieldFloat32(4, precipitationIntensity, 0.0);
}

static endSummary(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSummary(builder:flatbuffers.Builder, startTime:number, endTime:number, condition:PrecipitationType, precipitationChance:number, precipitationIntensity:number):flatbuffers.Offset {
  Summary.startSummary(builder);
  Summary.addStartTime(builder, startTime);
  Summary.addEndTime(builder, endTime);
  Summary.addCondition(builder, condition);
  Summary.addPrecipitationChance(builder, precipitationChance);
  Summary.addPrecipitationIntensity(builder, precipitationIntensity);
  return Summary.endSummary(builder);
}
}
