// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
export var Urgency;
(function (Urgency) {
    Urgency[Urgency["UNKNOWN"] = 0] = "UNKNOWN";
    Urgency[Urgency["IMMEDIATE"] = 1] = "IMMEDIATE";
    Urgency[Urgency["EXPECTED"] = 2] = "EXPECTED";
    Urgency[Urgency["FUTURE"] = 3] = "FUTURE";
    Urgency[Urgency["PAST"] = 4] = "PAST";
    Urgency[Urgency["UNKNOWN5"] = 5] = "UNKNOWN5";
})(Urgency || (Urgency = {}));
