// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Alert } from '../wk2/alert.js';
import { Metadata } from '../wk2/metadata.js';


export class WeatherAlert {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WeatherAlert {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWeatherAlert(bb:flatbuffers.ByteBuffer, obj?:WeatherAlert):WeatherAlert {
  return (obj || new WeatherAlert()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWeatherAlert(bb:flatbuffers.ByteBuffer, obj?:WeatherAlert):WeatherAlert {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WeatherAlert()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

metadata(obj?:Metadata):Metadata|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Metadata()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

detailsUrl():string|null
detailsUrl(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
detailsUrl(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

alerts(index: number, obj?:Alert):Alert|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Alert()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

alertsLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startWeatherAlert(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addMetadata(builder:flatbuffers.Builder, metadataOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, metadataOffset, 0);
}

static addDetailsUrl(builder:flatbuffers.Builder, detailsUrlOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, detailsUrlOffset, 0);
}

static addAlerts(builder:flatbuffers.Builder, alertsOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, alertsOffset, 0);
}

static createAlertsVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startAlertsVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endWeatherAlert(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWeatherAlert(builder:flatbuffers.Builder, metadataOffset:flatbuffers.Offset, detailsUrlOffset:flatbuffers.Offset, alertsOffset:flatbuffers.Offset):flatbuffers.Offset {
  WeatherAlert.startWeatherAlert(builder);
  WeatherAlert.addMetadata(builder, metadataOffset);
  WeatherAlert.addDetailsUrl(builder, detailsUrlOffset);
  WeatherAlert.addAlerts(builder, alertsOffset);
  return WeatherAlert.endWeatherAlert(builder);
}
}
