// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from "../../../node_modules/flatbuffers/mjs/flatbuffers.js";
export class WeatherAlert {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsWeatherAlert(bb, obj) {
        return (obj || new WeatherAlert()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsWeatherAlert(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new WeatherAlert()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static startWeatherAlert(builder) {
        builder.startObject(0);
    }
    static endWeatherAlert(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createWeatherAlert(builder) {
        WeatherAlert.startWeatherAlert(builder);
        return WeatherAlert.endWeatherAlert(builder);
    }
}
