// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from "../../../node_modules/flatbuffers/mjs/flatbuffers.js";
export class weatherChanges {
    bb = null;
    bb_pos = 0;
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsweatherChanges(bb, obj) {
        return (obj || new weatherChanges()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsweatherChanges(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new weatherChanges()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static startweatherChanges(builder) {
        builder.startObject(0);
    }
    static endweatherChanges(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createweatherChanges(builder) {
        weatherChanges.startweatherChanges(builder);
        return weatherChanges.endweatherChanges(builder);
    }
}
