// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,keep_enum_prefix,output_javascript
// @generated from protobuf file "apple.parsec.siri.v2alpha.SiriPegasusContext.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { DeviceState } from "./apple.parsec.siri.v2alpha.DeviceState";
/**
 * @generated from protobuf message SiriPegasusContext
 */
export interface SiriPegasusContext {
    /**
     * @generated from protobuf field: DeviceState deviceState = 1;
     */
    deviceState?: DeviceState;
    /**
     * @generated from protobuf field: string restrictions = 8;
     */
    restrictions: string;
    /**
     * multiUserContext = 9;
     * contentRatingRestrictions = 10;
     *
     * @generated from protobuf field: N14 conversationContext = 14;
     */
    conversationContext?: N14;
}
/**
 * @generated from protobuf message N14
 */
export interface N14 {
    /**
     * @generated from protobuf field: string cc = 1;
     */
    cc: string;
}
declare class SiriPegasusContext$Type extends MessageType<SiriPegasusContext> {
    constructor();
}
/**
 * @generated MessageType for protobuf message SiriPegasusContext
 */
export declare const SiriPegasusContext: SiriPegasusContext$Type;
declare class N14$Type extends MessageType<N14> {
    constructor();
}
/**
 * @generated MessageType for protobuf message N14
 */
export declare const N14: N14$Type;
export {};
