// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,output_javascript
// @generated from protobuf file "apple.parsec.siri.v2alpha.DeviceState.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message DeviceState
 */
export interface DeviceState {
    /**
     * @generated from protobuf field: optional string companionName = 1;
     */
    companionName?: string;
    /**
     * @generated from protobuf field: optional string deviceName = 2;
     */
    deviceName?: string;
    /**
     * @generated from protobuf field: optional string inputOrigin = 3;
     */
    inputOrigin?: string;
    /**
     * @generated from protobuf field: optional bool isAppleTv = 4;
     */
    isAppleTv?: boolean;
    /**
     * @generated from protobuf field: optional bool isCarDnd = 5;
     */
    isCarDnd?: boolean;
    /**
     * @generated from protobuf field: optional bool isCarPlay = 6;
     */
    isCarPlay?: boolean;
    /**
     * @generated from protobuf field: optional bool isEyesFree = 7;
     */
    isEyesFree?: boolean;
    /**
     * @generated from protobuf field: optional bool isHomePod = 8;
     */
    isHomePod?: boolean;
    /**
     * @generated from protobuf field: optional bool isLockedWithPasscode = 9;
     */
    isLockedWithPasscode?: boolean;
    /**
     * @generated from protobuf field: optional bool isMac = 10;
     */
    isMac?: boolean;
    /**
     * @generated from protobuf field: optional bool isMultiUser = 11;
     */
    isMultiUser?: boolean;
    /**
     * @generated from protobuf field: optional bool isPad = 12;
     */
    isPad?: boolean;
    /**
     * @generated from protobuf field: optional bool isPhone = 13;
     */
    isPhone?: boolean;
    /**
     * @generated from protobuf field: optional bool isTextToSpeechEnabled = 14;
     */
    isTextToSpeechEnabled?: boolean;
    /**
     * @generated from protobuf field: optional bool isVox = 15;
     */
    isVox?: boolean;
    /**
     * @generated from protobuf field: optional bool isVoiceGenderFemale = 16;
     */
    isVoiceGenderFemale?: boolean;
    /**
     * @generated from protobuf field: optional bool isVoiceGenderMale = 17;
     */
    isVoiceGenderMale?: boolean;
    /**
     * @generated from protobuf field: optional bool isVoiceGenderUnknown = 18;
     */
    isVoiceGenderUnknown?: boolean;
    /**
     * @generated from protobuf field: optional bool isVoiceTriggerEnabled = 19;
     */
    isVoiceTriggerEnabled?: boolean;
    /**
     * @generated from protobuf field: optional bool isWatch = 20;
     */
    isWatch?: boolean;
    /**
     * @generated from protobuf field: optional int32 siriLocale = 21;
     */
    siriLocale?: number;
}
declare class DeviceState$Type extends MessageType<DeviceState> {
    constructor();
}
/**
 * @generated MessageType for protobuf message DeviceState
 */
export declare const DeviceState: DeviceState$Type;
export {};
