// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,keep_enum_prefix,output_javascript
// @generated from protobuf file "apple.parsec.siri.context.ClientConversationContextInfo.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * clientDisplayHints = 1;
 * clientApplicationContext = 2;
 * onDeviceContext = 3;
 * promptContext = 4;
 *
 * @generated from protobuf message ClientConversationContextInfo
 */
export interface ClientConversationContextInfo {
}
declare class ClientConversationContextInfo$Type extends MessageType<ClientConversationContextInfo> {
    constructor();
}
/**
 * @generated MessageType for protobuf message ClientConversationContextInfo
 */
export declare const ClientConversationContextInfo: ClientConversationContextInfo$Type;
export {};
