// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,keep_enum_prefix,output_javascript
// @generated from protobuf file "GEOPDPlaceRequest.proto" (syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf enum PDPlaceRequest.RequestType
 */
export var PDPlaceRequest_RequestType;
(function (PDPlaceRequest_RequestType) {
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN = 0;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_UNKNOWN"] = 0] = "REQUEST_TYPE_UNKNOWN";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_SEARCH = 1;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_SEARCH"] = 1] = "REQUEST_TYPE_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_GEOCODING = 2;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_GEOCODING"] = 2] = "REQUEST_TYPE_GEOCODING";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_CANONICAL_LOCATION_SEARCH = 3;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_CANONICAL_LOCATION_SEARCH"] = 3] = "REQUEST_TYPE_CANONICAL_LOCATION_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_REVERSE_GEOCODING = 4;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_REVERSE_GEOCODING"] = 4] = "REQUEST_TYPE_REVERSE_GEOCODING";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_PLACE_LOOKUP = 5;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_PLACE_LOOKUP"] = 5] = "REQUEST_TYPE_PLACE_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_MERCHANT_LOOKUP = 6;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_MERCHANT_LOOKUP"] = 6] = "REQUEST_TYPE_MERCHANT_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_PLACE_REFINEMENT = 7;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_PLACE_REFINEMENT"] = 7] = "REQUEST_TYPE_PLACE_REFINEMENT";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_SIRI_SEARCH = 8;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_SIRI_SEARCH"] = 8] = "REQUEST_TYPE_SIRI_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_LOCATION_DIRECTED_SEARCH = 9;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_LOCATION_DIRECTED_SEARCH"] = 9] = "REQUEST_TYPE_LOCATION_DIRECTED_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_AUTOCOMPLETE = 10;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_AUTOCOMPLETE"] = 10] = "REQUEST_TYPE_AUTOCOMPLETE";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_BROWSE_CATEGORY_SUGGESTION = 11;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_BROWSE_CATEGORY_SUGGESTION"] = 11] = "REQUEST_TYPE_BROWSE_CATEGORY_SUGGESTION";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_CATEGORY_SEARCH = 12;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_CATEGORY_SEARCH"] = 12] = "REQUEST_TYPE_CATEGORY_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_POPULAR_NEARBY_SEARCH = 13;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_POPULAR_NEARBY_SEARCH"] = 13] = "REQUEST_TYPE_POPULAR_NEARBY_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_ZERO_KEYWORD_CATEGORY_SUGGESTION = 14;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_ZERO_KEYWORD_CATEGORY_SUGGESTION"] = 14] = "REQUEST_TYPE_ZERO_KEYWORD_CATEGORY_SUGGESTION";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_SEARCH_FIELD_PLACEHOLDER = 15;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_SEARCH_FIELD_PLACEHOLDER"] = 15] = "REQUEST_TYPE_SEARCH_FIELD_PLACEHOLDER";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_BATCH_POPULAR_NEARBY_SEARCH = 16;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_BATCH_POPULAR_NEARBY_SEARCH"] = 16] = "REQUEST_TYPE_BATCH_POPULAR_NEARBY_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_VENDOR_SPECIFIC_PLACE_REFINEMENT = 17;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_VENDOR_SPECIFIC_PLACE_REFINEMENT"] = 17] = "REQUEST_TYPE_VENDOR_SPECIFIC_PLACE_REFINEMENT";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_NEARBY_SEARCH = 18;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_NEARBY_SEARCH"] = 18] = "REQUEST_TYPE_NEARBY_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_ADDRESS_OBJECT_GEOCODING = 19;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_ADDRESS_OBJECT_GEOCODING"] = 19] = "REQUEST_TYPE_ADDRESS_OBJECT_GEOCODING";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_ZERO_KEYWORD_WITH_SEARCH_RESULTS_SUGGESTION = 20;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_ZERO_KEYWORD_WITH_SEARCH_RESULTS_SUGGESTION"] = 20] = "REQUEST_TYPE_ZERO_KEYWORD_WITH_SEARCH_RESULTS_SUGGESTION";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_EXTERNAL_TRANSIT_LOOKUP = 21;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_EXTERNAL_TRANSIT_LOOKUP"] = 21] = "REQUEST_TYPE_EXTERNAL_TRANSIT_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_FEATURE_ID_GEOCODING = 22;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_FEATURE_ID_GEOCODING"] = 22] = "REQUEST_TYPE_FEATURE_ID_GEOCODING";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_MAPS_IDENTIFIER_PLACE_LOOKUP = 23;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_MAPS_IDENTIFIER_PLACE_LOOKUP"] = 23] = "REQUEST_TYPE_MAPS_IDENTIFIER_PLACE_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_DATASET_STATUS_CHECK = 24;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_DATASET_STATUS_CHECK"] = 24] = "REQUEST_TYPE_DATASET_STATUS_CHECK";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_OFFLINE_AREA_LOOKUP = 25;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_OFFLINE_AREA_LOOKUP"] = 25] = "REQUEST_TYPE_OFFLINE_AREA_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_CLUSTER_GEOCODING = 26;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_CLUSTER_GEOCODING"] = 26] = "REQUEST_TYPE_CLUSTER_GEOCODING";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_OFFLINE_SUGGESTED_REGIONS = 27;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_OFFLINE_SUGGESTED_REGIONS"] = 27] = "REQUEST_TYPE_OFFLINE_SUGGESTED_REGIONS";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_OFFLINE_POLYGON_QUAD_NODES = 28;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_OFFLINE_POLYGON_QUAD_NODES"] = 28] = "REQUEST_TYPE_OFFLINE_POLYGON_QUAD_NODES";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_OFFLINE_PROACTIVE_REGIONS = 29;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_OFFLINE_PROACTIVE_REGIONS"] = 29] = "REQUEST_TYPE_OFFLINE_PROACTIVE_REGIONS";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_BRAND_LOOKUP = 30;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_BRAND_LOOKUP"] = 30] = "REQUEST_TYPE_BRAND_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_OFFLINE_UPDATE_MANIFEST = 31;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_OFFLINE_UPDATE_MANIFEST"] = 31] = "REQUEST_TYPE_OFFLINE_UPDATE_MANIFEST";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_WIFI_FINGERPRINT_LOOKUP = 32;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_WIFI_FINGERPRINT_LOOKUP"] = 32] = "REQUEST_TYPE_WIFI_FINGERPRINT_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_INITIAL_OFFLINE_SUGGESTION = 33;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_INITIAL_OFFLINE_SUGGESTION"] = 33] = "REQUEST_TYPE_INITIAL_OFFLINE_SUGGESTION";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_IP_GEO_LOOKUP = 34;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_IP_GEO_LOOKUP"] = 34] = "REQUEST_TYPE_IP_GEO_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_GROUND_VIEW_LABEL = 35;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_GROUND_VIEW_LABEL"] = 35] = "REQUEST_TYPE_GROUND_VIEW_LABEL";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_BATCH_SPATIAL_LOOKUP = 36;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_BATCH_SPATIAL_LOOKUP"] = 36] = "REQUEST_TYPE_BATCH_SPATIAL_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_TRANSIT_VEHICLE_POSITION = 37;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_TRANSIT_VEHICLE_POSITION"] = 37] = "REQUEST_TYPE_TRANSIT_VEHICLE_POSITION";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_PLACE_COLLECTION_LOOKUP = 38;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_PLACE_COLLECTION_LOOKUP"] = 38] = "REQUEST_TYPE_PLACE_COLLECTION_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_TRANSIT_SCHEDULE_LOOKUP = 39;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_TRANSIT_SCHEDULE_LOOKUP"] = 39] = "REQUEST_TYPE_TRANSIT_SCHEDULE_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_BATCH_CATEGORY_LOOKUP = 40;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_BATCH_CATEGORY_LOOKUP"] = 40] = "REQUEST_TYPE_BATCH_CATEGORY_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_BATCH_MERCHANT_LOOKUP_BRAND = 41;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_BATCH_MERCHANT_LOOKUP_BRAND"] = 41] = "REQUEST_TYPE_BATCH_MERCHANT_LOOKUP_BRAND";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_CHILD_PLACE_LOOKUP_BY_CATEGORY = 42;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_CHILD_PLACE_LOOKUP_BY_CATEGORY"] = 42] = "REQUEST_TYPE_CHILD_PLACE_LOOKUP_BY_CATEGORY";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_COLLECTION_SUGGESTION = 43;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_COLLECTION_SUGGESTION"] = 43] = "REQUEST_TYPE_COLLECTION_SUGGESTION";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_MAPS_SEARCH_HOME = 44;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_MAPS_SEARCH_HOME"] = 44] = "REQUEST_TYPE_MAPS_SEARCH_HOME";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_PLACE_QUESTIONNAIRE_LOOKUP = 45;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_PLACE_QUESTIONNAIRE_LOOKUP"] = 45] = "REQUEST_TYPE_PLACE_QUESTIONNAIRE_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_PUBLISHER_VIEW = 46;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_PUBLISHER_VIEW"] = 46] = "REQUEST_TYPE_PUBLISHER_VIEW";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_ALL_COLLECTIONS_VIEW = 47;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_ALL_COLLECTIONS_VIEW"] = 47] = "REQUEST_TYPE_ALL_COLLECTIONS_VIEW";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_AIRPORT_ENTITY_PLACE_LOOKUP = 48;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["REQUEST_TYPE_AIRPORT_ENTITY_PLACE_LOOKUP"] = 48] = "REQUEST_TYPE_AIRPORT_ENTITY_PLACE_LOOKUP";
    /**
     * @generated from protobuf enum value: UNKNOWN49 = 49;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN49"] = 49] = "UNKNOWN49";
    /**
     * @generated from protobuf enum value: UNKNOWN50 = 50;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN50"] = 50] = "UNKNOWN50";
    /**
     * @generated from protobuf enum value: UNKNOWN51 = 51;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN51"] = 51] = "UNKNOWN51";
    /**
     * @generated from protobuf enum value: UNKNOWN52 = 52;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN52"] = 52] = "UNKNOWN52";
    /**
     * @generated from protobuf enum value: UNKNOWN53 = 53;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN53"] = 53] = "UNKNOWN53";
    /**
     * @generated from protobuf enum value: UNKNOWN54 = 54;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN54"] = 54] = "UNKNOWN54";
    /**
     * @generated from protobuf enum value: UNKNOWN55 = 55;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN55"] = 55] = "UNKNOWN55";
    /**
     * @generated from protobuf enum value: UNKNOWN56 = 56;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN56"] = 56] = "UNKNOWN56";
    /**
     * @generated from protobuf enum value: UNKNOWN57 = 57;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN57"] = 57] = "UNKNOWN57";
    /**
     * @generated from protobuf enum value: UNKNOWN58 = 58;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN58"] = 58] = "UNKNOWN58";
    /**
     * @generated from protobuf enum value: UNKNOWN59 = 59;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN59"] = 59] = "UNKNOWN59";
    /**
     * @generated from protobuf enum value: UNKNOWN60 = 60;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN60"] = 60] = "UNKNOWN60";
    /**
     * @generated from protobuf enum value: UNKNOWN61 = 61;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN61"] = 61] = "UNKNOWN61";
    /**
     * @generated from protobuf enum value: UNKNOWN62 = 62;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN62"] = 62] = "UNKNOWN62";
    /**
     * @generated from protobuf enum value: UNKNOWN63 = 63;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN63"] = 63] = "UNKNOWN63";
    /**
     * @generated from protobuf enum value: UNKNOWN64 = 64;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN64"] = 64] = "UNKNOWN64";
    /**
     * @generated from protobuf enum value: UNKNOWN65 = 65;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN65"] = 65] = "UNKNOWN65";
    /**
     * @generated from protobuf enum value: UNKNOWN66 = 66;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN66"] = 66] = "UNKNOWN66";
    /**
     * @generated from protobuf enum value: UNKNOWN67 = 67;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN67"] = 67] = "UNKNOWN67";
    /**
     * @generated from protobuf enum value: UNKNOWN68 = 68;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN68"] = 68] = "UNKNOWN68";
    /**
     * @generated from protobuf enum value: UNKNOWN69 = 69;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN69"] = 69] = "UNKNOWN69";
    /**
     * @generated from protobuf enum value: UNKNOWN70 = 70;
     */
    PDPlaceRequest_RequestType[PDPlaceRequest_RequestType["UNKNOWN70"] = 70] = "UNKNOWN70";
})(PDPlaceRequest_RequestType || (PDPlaceRequest_RequestType = {}));
/**
 * @generated from protobuf enum GeoServiceTag.ServiceType
 */
export var GeoServiceTag_ServiceType;
(function (GeoServiceTag_ServiceType) {
    /**
     * @generated from protobuf enum value: SERVICE_UNKNOWN = 0;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["SERVICE_UNKNOWN"] = 0] = "SERVICE_UNKNOWN";
    /**
     * @generated from protobuf enum value: REV_GEO = 1;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["REV_GEO"] = 1] = "REV_GEO";
    /**
     * @generated from protobuf enum value: FWD_GEO = 2;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["FWD_GEO"] = 2] = "FWD_GEO";
    /**
     * @generated from protobuf enum value: SEARCH = 3;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["SEARCH"] = 3] = "SEARCH";
    /**
     * @generated from protobuf enum value: ROUTING = 4;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["ROUTING"] = 4] = "ROUTING";
    /**
     * @generated from protobuf enum value: LOCATION_SERVICE = 5;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["LOCATION_SERVICE"] = 5] = "LOCATION_SERVICE";
    /**
     * @generated from protobuf enum value: COLLECTION = 6;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["COLLECTION"] = 6] = "COLLECTION";
    /**
     * @generated from protobuf enum value: CELL_WIFI_HARVEST = 7;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["CELL_WIFI_HARVEST"] = 7] = "CELL_WIFI_HARVEST";
    /**
     * @generated from protobuf enum value: TRACE_HARVEST = 8;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["TRACE_HARVEST"] = 8] = "TRACE_HARVEST";
    /**
     * @generated from protobuf enum value: TRAFFIC_TILES = 9;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["TRAFFIC_TILES"] = 9] = "TRAFFIC_TILES";
    /**
     * @generated from protobuf enum value: RASTER = 10;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["RASTER"] = 10] = "RASTER";
    /**
     * @generated from protobuf enum value: AUTO_COMPLETE = 11;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["AUTO_COMPLETE"] = 11] = "AUTO_COMPLETE";
    /**
     * @generated from protobuf enum value: DASHBOARD_TEST = 12;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["DASHBOARD_TEST"] = 12] = "DASHBOARD_TEST";
    /**
     * @generated from protobuf enum value: VECTOR = 13;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["VECTOR"] = 13] = "VECTOR";
    /**
     * @generated from protobuf enum value: ADDR_PTS_HARVEST = 14;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["ADDR_PTS_HARVEST"] = 14] = "ADDR_PTS_HARVEST";
    /**
     * @generated from protobuf enum value: DISPATCHER = 15;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["DISPATCHER"] = 15] = "DISPATCHER";
    /**
     * @generated from protobuf enum value: PLACE_LOOKUP = 16;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["PLACE_LOOKUP"] = 16] = "PLACE_LOOKUP";
    /**
     * @generated from protobuf enum value: PARSEC = 17;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["PARSEC"] = 17] = "PARSEC";
    /**
     * @generated from protobuf enum value: GEO_SERVICES_FRAMEWORK = 18;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["GEO_SERVICES_FRAMEWORK"] = 18] = "GEO_SERVICES_FRAMEWORK";
    /**
     * @generated from protobuf enum value: SIRI = 19;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["SIRI"] = 19] = "SIRI";
    /**
     * @generated from protobuf enum value: MERCHANT_LOOKUP = 20;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["MERCHANT_LOOKUP"] = 20] = "MERCHANT_LOOKUP";
    /**
     * @generated from protobuf enum value: GEO_SEARCH = 21;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["GEO_SEARCH"] = 21] = "GEO_SEARCH";
    /**
     * @generated from protobuf enum value: TRAFFIC_ETA = 22;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["TRAFFIC_ETA"] = 22] = "TRAFFIC_ETA";
    /**
     * @generated from protobuf enum value: COMMUNITY = 23;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["COMMUNITY"] = 23] = "COMMUNITY";
    /**
     * @generated from protobuf enum value: LOCUS = 24;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["LOCUS"] = 24] = "LOCUS";
    /**
     * @generated from protobuf enum value: AUTONAVI_FRONTDOOR = 25;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["AUTONAVI_FRONTDOOR"] = 25] = "AUTONAVI_FRONTDOOR";
    /**
     * @generated from protobuf enum value: UNKNOWN26 = 26;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN26"] = 26] = "UNKNOWN26";
    /**
     * @generated from protobuf enum value: UNKNOWN27 = 27;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN27"] = 27] = "UNKNOWN27";
    /**
     * @generated from protobuf enum value: UNKNOWN28 = 28;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN28"] = 28] = "UNKNOWN28";
    /**
     * @generated from protobuf enum value: UNKNOWN29 = 29;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN29"] = 29] = "UNKNOWN29";
    /**
     * @generated from protobuf enum value: UNKNOWN30 = 30;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN30"] = 30] = "UNKNOWN30";
    /**
     * @generated from protobuf enum value: UNKNOWN31 = 31;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN31"] = 31] = "UNKNOWN31";
    /**
     * @generated from protobuf enum value: UNKNOWN32 = 32;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN32"] = 32] = "UNKNOWN32";
    /**
     * @generated from protobuf enum value: UNKNOWN33 = 33;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN33"] = 33] = "UNKNOWN33";
    /**
     * @generated from protobuf enum value: UNKNOWN34 = 34;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN34"] = 34] = "UNKNOWN34";
    /**
     * @generated from protobuf enum value: UNKNOWN35 = 35;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN35"] = 35] = "UNKNOWN35";
    /**
     * @generated from protobuf enum value: UNKNOWN36 = 36;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN36"] = 36] = "UNKNOWN36";
    /**
     * @generated from protobuf enum value: UNKNOWN37 = 37;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN37"] = 37] = "UNKNOWN37";
    /**
     * @generated from protobuf enum value: UNKNOWN38 = 38;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN38"] = 38] = "UNKNOWN38";
    /**
     * @generated from protobuf enum value: UNKNOWN39 = 39;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN39"] = 39] = "UNKNOWN39";
    /**
     * @generated from protobuf enum value: UNKNOWN40 = 40;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN40"] = 40] = "UNKNOWN40";
    /**
     * @generated from protobuf enum value: UNKNOWN41 = 41;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN41"] = 41] = "UNKNOWN41";
    /**
     * @generated from protobuf enum value: UNKNOWN42 = 42;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN42"] = 42] = "UNKNOWN42";
    /**
     * @generated from protobuf enum value: UNKNOWN43 = 43;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN43"] = 43] = "UNKNOWN43";
    /**
     * @generated from protobuf enum value: UNKNOWN44 = 44;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN44"] = 44] = "UNKNOWN44";
    /**
     * @generated from protobuf enum value: UNKNOWN45 = 45;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN45"] = 45] = "UNKNOWN45";
    /**
     * @generated from protobuf enum value: UNKNOWN46 = 46;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN46"] = 46] = "UNKNOWN46";
    /**
     * @generated from protobuf enum value: UNKNOWN47 = 47;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN47"] = 47] = "UNKNOWN47";
    /**
     * @generated from protobuf enum value: UNKNOWN48 = 48;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN48"] = 48] = "UNKNOWN48";
    /**
     * @generated from protobuf enum value: UNKNOWN49 = 49;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN49"] = 49] = "UNKNOWN49";
    /**
     * @generated from protobuf enum value: UNKNOWN50 = 50;
     */
    GeoServiceTag_ServiceType[GeoServiceTag_ServiceType["UNKNOWN50"] = 50] = "UNKNOWN50";
})(GeoServiceTag_ServiceType || (GeoServiceTag_ServiceType = {}));
// @generated message type with reflection information, may provide speed optimized methods
class PDPlaceRequest$Type extends MessageType {
    constructor() {
        super("PDPlaceRequest", [
            { no: 2, name: "clientMetadata", kind: "message", T: () => PDClientMetadata },
            { no: 3, name: "displayLanguage", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "spokenLanguage", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "suppressResultsRequiringAttribution", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "requestType", kind: "enum", T: () => ["PDPlaceRequest.RequestType", PDPlaceRequest_RequestType] },
            { no: 9, name: "displayRegion", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.displayLanguage = [];
        message.spokenLanguage = [];
        message.requestType = 0;
        message.displayRegion = "";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* PDClientMetadata clientMetadata */ 2:
                    message.clientMetadata = PDClientMetadata.internalBinaryRead(reader, reader.uint32(), options, message.clientMetadata);
                    break;
                case /* repeated string displayLanguage */ 3:
                    message.displayLanguage.push(reader.string());
                    break;
                case /* repeated string spokenLanguage */ 4:
                    message.spokenLanguage.push(reader.string());
                    break;
                case /* optional int32 suppressResultsRequiringAttribution */ 6:
                    message.suppressResultsRequiringAttribution = reader.int32();
                    break;
                case /* PDPlaceRequest.RequestType requestType */ 7:
                    message.requestType = reader.int32();
                    break;
                case /* string displayRegion */ 9:
                    message.displayRegion = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* PDClientMetadata clientMetadata = 2; */
        if (message.clientMetadata)
            PDClientMetadata.internalBinaryWrite(message.clientMetadata, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated string displayLanguage = 3; */
        for (let i = 0; i < message.displayLanguage.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.displayLanguage[i]);
        /* repeated string spokenLanguage = 4; */
        for (let i = 0; i < message.spokenLanguage.length; i++)
            writer.tag(4, WireType.LengthDelimited).string(message.spokenLanguage[i]);
        /* optional int32 suppressResultsRequiringAttribution = 6; */
        if (message.suppressResultsRequiringAttribution !== undefined)
            writer.tag(6, WireType.Varint).int32(message.suppressResultsRequiringAttribution);
        /* PDPlaceRequest.RequestType requestType = 7; */
        if (message.requestType !== 0)
            writer.tag(7, WireType.Varint).int32(message.requestType);
        /* string displayRegion = 9; */
        if (message.displayRegion !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.displayRegion);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PDPlaceRequest
 */
export const PDPlaceRequest = new PDPlaceRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PDAnalyticMetadata$Type extends MessageType {
    constructor() {
        super("PDAnalyticMetadata", [
            { no: 1, name: "appIdentifier", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "appMajorVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "appMinorVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "hardwareModel", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "osVersion", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "isInternalTool", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "isInternalInstall", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 9, name: "sequenceNumber", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "requestSource", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 12, name: "isFromApi", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 13, name: "serviceTag", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => GeoServiceTag },
            { no: 14, name: "productName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 15, name: "loggedAbExperiment", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "relativeTimestamp", kind: "scalar", opt: true, T: 1 /*ScalarType.DOUBLE*/ },
            { no: 19, name: "isSiriOriginalRequest", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.appIdentifier = "";
        message.appMajorVersion = "";
        message.appMinorVersion = "";
        message.hardwareModel = "";
        message.osVersion = "";
        message.isInternalInstall = 0;
        message.isFromApi = 0;
        message.serviceTag = [];
        message.productName = "";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string appIdentifier */ 1:
                    message.appIdentifier = reader.string();
                    break;
                case /* string appMajorVersion */ 2:
                    message.appMajorVersion = reader.string();
                    break;
                case /* string appMinorVersion */ 3:
                    message.appMinorVersion = reader.string();
                    break;
                case /* string hardwareModel */ 4:
                    message.hardwareModel = reader.string();
                    break;
                case /* string osVersion */ 5:
                    message.osVersion = reader.string();
                    break;
                case /* optional int32 isInternalTool */ 6:
                    message.isInternalTool = reader.int32();
                    break;
                case /* int32 isInternalInstall */ 7:
                    message.isInternalInstall = reader.int32();
                    break;
                case /* optional uint32 sequenceNumber */ 9:
                    message.sequenceNumber = reader.uint32();
                    break;
                case /* optional int32 requestSource */ 10:
                    message.requestSource = reader.int32();
                    break;
                case /* int32 isFromApi */ 12:
                    message.isFromApi = reader.int32();
                    break;
                case /* repeated GeoServiceTag serviceTag */ 13:
                    message.serviceTag.push(GeoServiceTag.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* string productName */ 14:
                    message.productName = reader.string();
                    break;
                case /* optional string loggedAbExperiment */ 15:
                    message.loggedAbExperiment = reader.string();
                    break;
                case /* optional double relativeTimestamp */ 18:
                    message.relativeTimestamp = reader.double();
                    break;
                case /* optional int32 isSiriOriginalRequest */ 19:
                    message.isSiriOriginalRequest = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string appIdentifier = 1; */
        if (message.appIdentifier !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.appIdentifier);
        /* string appMajorVersion = 2; */
        if (message.appMajorVersion !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.appMajorVersion);
        /* string appMinorVersion = 3; */
        if (message.appMinorVersion !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.appMinorVersion);
        /* string hardwareModel = 4; */
        if (message.hardwareModel !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.hardwareModel);
        /* string osVersion = 5; */
        if (message.osVersion !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.osVersion);
        /* optional int32 isInternalTool = 6; */
        if (message.isInternalTool !== undefined)
            writer.tag(6, WireType.Varint).int32(message.isInternalTool);
        /* int32 isInternalInstall = 7; */
        if (message.isInternalInstall !== 0)
            writer.tag(7, WireType.Varint).int32(message.isInternalInstall);
        /* optional uint32 sequenceNumber = 9; */
        if (message.sequenceNumber !== undefined)
            writer.tag(9, WireType.Varint).uint32(message.sequenceNumber);
        /* optional int32 requestSource = 10; */
        if (message.requestSource !== undefined)
            writer.tag(10, WireType.Varint).int32(message.requestSource);
        /* int32 isFromApi = 12; */
        if (message.isFromApi !== 0)
            writer.tag(12, WireType.Varint).int32(message.isFromApi);
        /* repeated GeoServiceTag serviceTag = 13; */
        for (let i = 0; i < message.serviceTag.length; i++)
            GeoServiceTag.internalBinaryWrite(message.serviceTag[i], writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        /* string productName = 14; */
        if (message.productName !== "")
            writer.tag(14, WireType.LengthDelimited).string(message.productName);
        /* optional string loggedAbExperiment = 15; */
        if (message.loggedAbExperiment !== undefined)
            writer.tag(15, WireType.LengthDelimited).string(message.loggedAbExperiment);
        /* optional double relativeTimestamp = 18; */
        if (message.relativeTimestamp !== undefined)
            writer.tag(18, WireType.Bit64).double(message.relativeTimestamp);
        /* optional int32 isSiriOriginalRequest = 19; */
        if (message.isSiriOriginalRequest !== undefined)
            writer.tag(19, WireType.Varint).int32(message.isSiriOriginalRequest);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PDAnalyticMetadata
 */
export const PDAnalyticMetadata = new PDAnalyticMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GeoServiceTag$Type extends MessageType {
    constructor() {
        super("GeoServiceTag", [
            { no: 1, name: "serviceType", kind: "enum", T: () => ["GeoServiceTag.ServiceType", GeoServiceTag_ServiceType] },
            { no: 2, name: "tag", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.serviceType = 0;
        message.tag = "";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* GeoServiceTag.ServiceType serviceType */ 1:
                    message.serviceType = reader.int32();
                    break;
                case /* string tag */ 2:
                    message.tag = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* GeoServiceTag.ServiceType serviceType = 1; */
        if (message.serviceType !== 0)
            writer.tag(1, WireType.Varint).int32(message.serviceType);
        /* string tag = 2; */
        if (message.tag !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.tag);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message GeoServiceTag
 */
export const GeoServiceTag = new GeoServiceTag$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PDClientMetadata$Type extends MessageType {
    constructor() {
        super("PDClientMetadata", [
            { no: 1, name: "deviceCountryCode", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "deviceDisplayLanguage", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "deviceKeyboardLanguage", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "deviceSpokenLanguage", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "timeSinceMapEnteredForeground", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "resultListAttributionSupport", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 11, name: "hourOfDay", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 12, name: "dayOfWeek", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 16, name: "requiredVersion", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 17, name: "debugApiKey", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 18, name: "knownClientResolvedTypeDeprecated", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ },
            { no: 22, name: "clientRevision", kind: "scalar", opt: true, T: 5 /*ScalarType.INT32*/ },
            { no: 24, name: "deviceSku", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.deviceCountryCode = "";
        message.deviceDisplayLanguage = "";
        message.resultListAttributionSupport = 0;
        message.dayOfWeek = 0;
        message.requiredVersion = 0;
        message.knownClientResolvedTypeDeprecated = [];
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string deviceCountryCode */ 1:
                    message.deviceCountryCode = reader.string();
                    break;
                case /* string deviceDisplayLanguage */ 3:
                    message.deviceDisplayLanguage = reader.string();
                    break;
                case /* optional string deviceKeyboardLanguage */ 4:
                    message.deviceKeyboardLanguage = reader.string();
                    break;
                case /* optional string deviceSpokenLanguage */ 5:
                    message.deviceSpokenLanguage = reader.string();
                    break;
                case /* optional uint32 timeSinceMapEnteredForeground */ 8:
                    message.timeSinceMapEnteredForeground = reader.uint32();
                    break;
                case /* int32 resultListAttributionSupport */ 10:
                    message.resultListAttributionSupport = reader.int32();
                    break;
                case /* optional uint32 hourOfDay */ 11:
                    message.hourOfDay = reader.uint32();
                    break;
                case /* uint32 dayOfWeek */ 12:
                    message.dayOfWeek = reader.uint32();
                    break;
                case /* int32 requiredVersion */ 16:
                    message.requiredVersion = reader.int32();
                    break;
                case /* optional string debugApiKey */ 17:
                    message.debugApiKey = reader.string();
                    break;
                case /* repeated int32 knownClientResolvedTypeDeprecated = 18 [deprecated = true];*/ 18:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.knownClientResolvedTypeDeprecated.push(reader.int32());
                    else
                        message.knownClientResolvedTypeDeprecated.push(reader.int32());
                    break;
                case /* optional int32 clientRevision */ 22:
                    message.clientRevision = reader.int32();
                    break;
                case /* optional string deviceSku */ 24:
                    message.deviceSku = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* string deviceCountryCode = 1; */
        if (message.deviceCountryCode !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.deviceCountryCode);
        /* string deviceDisplayLanguage = 3; */
        if (message.deviceDisplayLanguage !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.deviceDisplayLanguage);
        /* optional string deviceKeyboardLanguage = 4; */
        if (message.deviceKeyboardLanguage !== undefined)
            writer.tag(4, WireType.LengthDelimited).string(message.deviceKeyboardLanguage);
        /* optional string deviceSpokenLanguage = 5; */
        if (message.deviceSpokenLanguage !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.deviceSpokenLanguage);
        /* optional uint32 timeSinceMapEnteredForeground = 8; */
        if (message.timeSinceMapEnteredForeground !== undefined)
            writer.tag(8, WireType.Varint).uint32(message.timeSinceMapEnteredForeground);
        /* int32 resultListAttributionSupport = 10; */
        if (message.resultListAttributionSupport !== 0)
            writer.tag(10, WireType.Varint).int32(message.resultListAttributionSupport);
        /* optional uint32 hourOfDay = 11; */
        if (message.hourOfDay !== undefined)
            writer.tag(11, WireType.Varint).uint32(message.hourOfDay);
        /* uint32 dayOfWeek = 12; */
        if (message.dayOfWeek !== 0)
            writer.tag(12, WireType.Varint).uint32(message.dayOfWeek);
        /* int32 requiredVersion = 16; */
        if (message.requiredVersion !== 0)
            writer.tag(16, WireType.Varint).int32(message.requiredVersion);
        /* optional string debugApiKey = 17; */
        if (message.debugApiKey !== undefined)
            writer.tag(17, WireType.LengthDelimited).string(message.debugApiKey);
        /* repeated int32 knownClientResolvedTypeDeprecated = 18 [deprecated = true]; */
        if (message.knownClientResolvedTypeDeprecated.length) {
            writer.tag(18, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.knownClientResolvedTypeDeprecated.length; i++)
                writer.int32(message.knownClientResolvedTypeDeprecated[i]);
            writer.join();
        }
        /* optional int32 clientRevision = 22; */
        if (message.clientRevision !== undefined)
            writer.tag(22, WireType.Varint).int32(message.clientRevision);
        /* optional string deviceSku = 24; */
        if (message.deviceSku !== undefined)
            writer.tag(24, WireType.LengthDelimited).string(message.deviceSku);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PDClientMetadata
 */
export const PDClientMetadata = new PDClientMetadata$Type();
