// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,keep_enum_prefix,output_javascript
// @generated from protobuf file "GEOPDClientMetadata.proto" (syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message PDClientMetadata
 */
export interface PDClientMetadata {
    /**
     * @generated from protobuf field: string deviceCountryCode = 1;
     */
    deviceCountryCode: string;
    /**
     * @generated from protobuf field: string deviceDisplayLanguage = 3;
     */
    deviceDisplayLanguage: string;
    /**
     * @generated from protobuf field: optional string deviceKeyboardLanguage = 4;
     */
    deviceKeyboardLanguage?: string;
    /**
     * @generated from protobuf field: optional string deviceSpokenLanguage = 5;
     */
    deviceSpokenLanguage?: string;
    /**
     * @generated from protobuf field: optional uint32 timeSinceMapEnteredForeground = 8;
     */
    timeSinceMapEnteredForeground?: number;
    /**
     * AdditionalEnabledMarkets additionalEnabledMarkets = 9;
     *
     * @generated from protobuf field: int32 resultListAttributionSupport = 10;
     */
    resultListAttributionSupport: number;
    /**
     * @generated from protobuf field: optional uint32 hourOfDay = 11;
     */
    hourOfDay?: number;
    /**
     * @generated from protobuf field: uint32 dayOfWeek = 12;
     */
    dayOfWeek: number;
    /**
     * Location deviceExtendedLocation = 13;
     * repeated Location deviceHistoricalLocation = 15;
     *
     * @generated from protobuf field: int32 requiredVersion = 16;
     */
    requiredVersion: number;
    /**
     * @generated from protobuf field: optional string debugApiKey = 17;
     */
    debugApiKey?: string;
    /**
     * @deprecated
     * @generated from protobuf field: repeated int32 knownClientResolvedTypeDeprecated = 18 [deprecated = true];
     */
    knownClientResolvedTypeDeprecated: number[];
    /**
     * float enablePreflightVenues = 19; // 有问题, 不能按 bool 解析，可以按 float 解析，可能是deprecated导致的。
     *
     * @generated from protobuf field: repeated int32 knownClientResolvedType = 19;
     */
    knownClientResolvedType: number[];
    /**
     * repeated string businessChatPreflightIdentifier = 21;
     *
     * @generated from protobuf field: optional int32 clientRevision = 22;
     */
    clientRevision?: number;
    /**
     * LocalizationCapabilities localizationCapabilities = 23;
     *
     * @generated from protobuf field: optional string deviceSku = 24;
     */
    deviceSku?: string;
}
declare class PDClientMetadata$Type extends MessageType<PDClientMetadata> {
    constructor();
    create(value?: PartialMessage<PDClientMetadata>): PDClientMetadata;
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PDClientMetadata): PDClientMetadata;
    internalBinaryWrite(message: PDClientMetadata, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter;
}
/**
 * @generated MessageType for protobuf message PDClientMetadata
 */
export declare const PDClientMetadata: PDClientMetadata$Type;
export {};
