// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,keep_enum_prefix,output_javascript
// @generated from protobuf file "GEOPDPlaceRequest.proto" (syntax proto3)
// tslint:disable
import { WireType } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { GEOPDComponentInfo } from "./GEOPDComponentInfo";
import { GEOPDClientMetadata } from "./GEOPDClientMetadata";
/**
 * @generated from protobuf enum RequestType
 */
export var RequestType;
(function (RequestType) {
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN = 0;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN"] = 0] = "REQUEST_TYPE_UNKNOWN";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_SEARCH = 1;
     */
    RequestType[RequestType["REQUEST_TYPE_SEARCH"] = 1] = "REQUEST_TYPE_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_GEOCODING = 2;
     */
    RequestType[RequestType["REQUEST_TYPE_GEOCODING"] = 2] = "REQUEST_TYPE_GEOCODING";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_CANONICAL_LOCATION_SEARCH = 3;
     */
    RequestType[RequestType["REQUEST_TYPE_CANONICAL_LOCATION_SEARCH"] = 3] = "REQUEST_TYPE_CANONICAL_LOCATION_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_REVERSE_GEOCODING = 4;
     */
    RequestType[RequestType["REQUEST_TYPE_REVERSE_GEOCODING"] = 4] = "REQUEST_TYPE_REVERSE_GEOCODING";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_PLACE_LOOKUP = 5;
     */
    RequestType[RequestType["REQUEST_TYPE_PLACE_LOOKUP"] = 5] = "REQUEST_TYPE_PLACE_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_MERCHANT_LOOKUP = 6;
     */
    RequestType[RequestType["REQUEST_TYPE_MERCHANT_LOOKUP"] = 6] = "REQUEST_TYPE_MERCHANT_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_PLACE_REFINEMENT = 7;
     */
    RequestType[RequestType["REQUEST_TYPE_PLACE_REFINEMENT"] = 7] = "REQUEST_TYPE_PLACE_REFINEMENT";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_SIRI_SEARCH = 8;
     */
    RequestType[RequestType["REQUEST_TYPE_SIRI_SEARCH"] = 8] = "REQUEST_TYPE_SIRI_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_LOCATION_DIRECTED_SEARCH = 9;
     */
    RequestType[RequestType["REQUEST_TYPE_LOCATION_DIRECTED_SEARCH"] = 9] = "REQUEST_TYPE_LOCATION_DIRECTED_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_AUTOCOMPLETE = 10;
     */
    RequestType[RequestType["REQUEST_TYPE_AUTOCOMPLETE"] = 10] = "REQUEST_TYPE_AUTOCOMPLETE";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_BROWSE_CATEGORY_SUGGESTION = 11;
     */
    RequestType[RequestType["REQUEST_TYPE_BROWSE_CATEGORY_SUGGESTION"] = 11] = "REQUEST_TYPE_BROWSE_CATEGORY_SUGGESTION";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_CATEGORY_SEARCH = 12;
     */
    RequestType[RequestType["REQUEST_TYPE_CATEGORY_SEARCH"] = 12] = "REQUEST_TYPE_CATEGORY_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_POPULAR_NEARBY_SEARCH = 13;
     */
    RequestType[RequestType["REQUEST_TYPE_POPULAR_NEARBY_SEARCH"] = 13] = "REQUEST_TYPE_POPULAR_NEARBY_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_ZERO_KEYWORD_CATEGORY_SUGGESTION = 14;
     */
    RequestType[RequestType["REQUEST_TYPE_ZERO_KEYWORD_CATEGORY_SUGGESTION"] = 14] = "REQUEST_TYPE_ZERO_KEYWORD_CATEGORY_SUGGESTION";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_SEARCH_FIELD_PLACEHOLDER = 15;
     */
    RequestType[RequestType["REQUEST_TYPE_SEARCH_FIELD_PLACEHOLDER"] = 15] = "REQUEST_TYPE_SEARCH_FIELD_PLACEHOLDER";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_BATCH_POPULAR_NEARBY_SEARCH = 16;
     */
    RequestType[RequestType["REQUEST_TYPE_BATCH_POPULAR_NEARBY_SEARCH"] = 16] = "REQUEST_TYPE_BATCH_POPULAR_NEARBY_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_VENDOR_SPECIFIC_PLACE_REFINEMENT = 17;
     */
    RequestType[RequestType["REQUEST_TYPE_VENDOR_SPECIFIC_PLACE_REFINEMENT"] = 17] = "REQUEST_TYPE_VENDOR_SPECIFIC_PLACE_REFINEMENT";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_NEARBY_SEARCH = 18;
     */
    RequestType[RequestType["REQUEST_TYPE_NEARBY_SEARCH"] = 18] = "REQUEST_TYPE_NEARBY_SEARCH";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_ADDRESS_OBJECT_GEOCODING = 19;
     */
    RequestType[RequestType["REQUEST_TYPE_ADDRESS_OBJECT_GEOCODING"] = 19] = "REQUEST_TYPE_ADDRESS_OBJECT_GEOCODING";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_ZERO_KEYWORD_WITH_SEARCH_RESULTS_SUGGESTION = 20;
     */
    RequestType[RequestType["REQUEST_TYPE_ZERO_KEYWORD_WITH_SEARCH_RESULTS_SUGGESTION"] = 20] = "REQUEST_TYPE_ZERO_KEYWORD_WITH_SEARCH_RESULTS_SUGGESTION";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_EXTERNAL_TRANSIT_LOOKUP = 21;
     */
    RequestType[RequestType["REQUEST_TYPE_EXTERNAL_TRANSIT_LOOKUP"] = 21] = "REQUEST_TYPE_EXTERNAL_TRANSIT_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_FEATURE_ID_GEOCODING = 22;
     */
    RequestType[RequestType["REQUEST_TYPE_FEATURE_ID_GEOCODING"] = 22] = "REQUEST_TYPE_FEATURE_ID_GEOCODING";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_MAPS_IDENTIFIER_PLACE_LOOKUP = 23;
     */
    RequestType[RequestType["REQUEST_TYPE_MAPS_IDENTIFIER_PLACE_LOOKUP"] = 23] = "REQUEST_TYPE_MAPS_IDENTIFIER_PLACE_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_DATASET_STATUS_CHECK = 24;
     */
    RequestType[RequestType["REQUEST_TYPE_DATASET_STATUS_CHECK"] = 24] = "REQUEST_TYPE_DATASET_STATUS_CHECK";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_OFFLINE_AREA_LOOKUP = 25;
     */
    RequestType[RequestType["REQUEST_TYPE_OFFLINE_AREA_LOOKUP"] = 25] = "REQUEST_TYPE_OFFLINE_AREA_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_CLUSTER_GEOCODING = 26;
     */
    RequestType[RequestType["REQUEST_TYPE_CLUSTER_GEOCODING"] = 26] = "REQUEST_TYPE_CLUSTER_GEOCODING";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_OFFLINE_SUGGESTED_REGIONS = 27;
     */
    RequestType[RequestType["REQUEST_TYPE_OFFLINE_SUGGESTED_REGIONS"] = 27] = "REQUEST_TYPE_OFFLINE_SUGGESTED_REGIONS";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_OFFLINE_POLYGON_QUAD_NODES = 28;
     */
    RequestType[RequestType["REQUEST_TYPE_OFFLINE_POLYGON_QUAD_NODES"] = 28] = "REQUEST_TYPE_OFFLINE_POLYGON_QUAD_NODES";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_OFFLINE_PROACTIVE_REGIONS = 29;
     */
    RequestType[RequestType["REQUEST_TYPE_OFFLINE_PROACTIVE_REGIONS"] = 29] = "REQUEST_TYPE_OFFLINE_PROACTIVE_REGIONS";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_BRAND_LOOKUP = 30;
     */
    RequestType[RequestType["REQUEST_TYPE_BRAND_LOOKUP"] = 30] = "REQUEST_TYPE_BRAND_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_OFFLINE_UPDATE_MANIFEST = 31;
     */
    RequestType[RequestType["REQUEST_TYPE_OFFLINE_UPDATE_MANIFEST"] = 31] = "REQUEST_TYPE_OFFLINE_UPDATE_MANIFEST";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_WIFI_FINGERPRINT_LOOKUP = 32;
     */
    RequestType[RequestType["REQUEST_TYPE_WIFI_FINGERPRINT_LOOKUP"] = 32] = "REQUEST_TYPE_WIFI_FINGERPRINT_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_INITIAL_OFFLINE_SUGGESTION = 33;
     */
    RequestType[RequestType["REQUEST_TYPE_INITIAL_OFFLINE_SUGGESTION"] = 33] = "REQUEST_TYPE_INITIAL_OFFLINE_SUGGESTION";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_IP_GEO_LOOKUP = 34;
     */
    RequestType[RequestType["REQUEST_TYPE_IP_GEO_LOOKUP"] = 34] = "REQUEST_TYPE_IP_GEO_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_GROUND_VIEW_LABEL = 35;
     */
    RequestType[RequestType["REQUEST_TYPE_GROUND_VIEW_LABEL"] = 35] = "REQUEST_TYPE_GROUND_VIEW_LABEL";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_BATCH_SPATIAL_LOOKUP = 36;
     */
    RequestType[RequestType["REQUEST_TYPE_BATCH_SPATIAL_LOOKUP"] = 36] = "REQUEST_TYPE_BATCH_SPATIAL_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_TRANSIT_VEHICLE_POSITION = 37;
     */
    RequestType[RequestType["REQUEST_TYPE_TRANSIT_VEHICLE_POSITION"] = 37] = "REQUEST_TYPE_TRANSIT_VEHICLE_POSITION";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_PLACE_COLLECTION_LOOKUP = 38;
     */
    RequestType[RequestType["REQUEST_TYPE_PLACE_COLLECTION_LOOKUP"] = 38] = "REQUEST_TYPE_PLACE_COLLECTION_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_TRANSIT_SCHEDULE_LOOKUP = 39;
     */
    RequestType[RequestType["REQUEST_TYPE_TRANSIT_SCHEDULE_LOOKUP"] = 39] = "REQUEST_TYPE_TRANSIT_SCHEDULE_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_BATCH_CATEGORY_LOOKUP = 40;
     */
    RequestType[RequestType["REQUEST_TYPE_BATCH_CATEGORY_LOOKUP"] = 40] = "REQUEST_TYPE_BATCH_CATEGORY_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_BATCH_MERCHANT_LOOKUP_BRAND = 41;
     */
    RequestType[RequestType["REQUEST_TYPE_BATCH_MERCHANT_LOOKUP_BRAND"] = 41] = "REQUEST_TYPE_BATCH_MERCHANT_LOOKUP_BRAND";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_CHILD_PLACE_LOOKUP_BY_CATEGORY = 42;
     */
    RequestType[RequestType["REQUEST_TYPE_CHILD_PLACE_LOOKUP_BY_CATEGORY"] = 42] = "REQUEST_TYPE_CHILD_PLACE_LOOKUP_BY_CATEGORY";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_COLLECTION_SUGGESTION = 43;
     */
    RequestType[RequestType["REQUEST_TYPE_COLLECTION_SUGGESTION"] = 43] = "REQUEST_TYPE_COLLECTION_SUGGESTION";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_MAPS_SEARCH_HOME = 44;
     */
    RequestType[RequestType["REQUEST_TYPE_MAPS_SEARCH_HOME"] = 44] = "REQUEST_TYPE_MAPS_SEARCH_HOME";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_PLACE_QUESTIONNAIRE_LOOKUP = 45;
     */
    RequestType[RequestType["REQUEST_TYPE_PLACE_QUESTIONNAIRE_LOOKUP"] = 45] = "REQUEST_TYPE_PLACE_QUESTIONNAIRE_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_PUBLISHER_VIEW = 46;
     */
    RequestType[RequestType["REQUEST_TYPE_PUBLISHER_VIEW"] = 46] = "REQUEST_TYPE_PUBLISHER_VIEW";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_ALL_COLLECTIONS_VIEW = 47;
     */
    RequestType[RequestType["REQUEST_TYPE_ALL_COLLECTIONS_VIEW"] = 47] = "REQUEST_TYPE_ALL_COLLECTIONS_VIEW";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_AIRPORT_ENTITY_PLACE_LOOKUP = 48;
     */
    RequestType[RequestType["REQUEST_TYPE_AIRPORT_ENTITY_PLACE_LOOKUP"] = 48] = "REQUEST_TYPE_AIRPORT_ENTITY_PLACE_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_TERRITORY_LOOKUP = 49;
     */
    RequestType[RequestType["REQUEST_TYPE_TERRITORY_LOOKUP"] = 49] = "REQUEST_TYPE_TERRITORY_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_TRANSIT_NEARBY_SCHEDULE_LOOKUP = 50;
     */
    RequestType[RequestType["REQUEST_TYPE_TRANSIT_NEARBY_SCHEDULE_LOOKUP"] = 50] = "REQUEST_TYPE_TRANSIT_NEARBY_SCHEDULE_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_MAPS_HOME = 51;
     */
    RequestType[RequestType["REQUEST_TYPE_MAPS_HOME"] = 51] = "REQUEST_TYPE_MAPS_HOME";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_ALL_GUIDES_LOCATIONS = 52;
     */
    RequestType[RequestType["REQUEST_TYPE_ALL_GUIDES_LOCATIONS"] = 52] = "REQUEST_TYPE_ALL_GUIDES_LOCATIONS";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_GUIDES_HOME = 53;
     */
    RequestType[RequestType["REQUEST_TYPE_GUIDES_HOME"] = 53] = "REQUEST_TYPE_GUIDES_HOME";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_EXTENDED_GEO_LOOKUP = 54;
     */
    RequestType[RequestType["REQUEST_TYPE_EXTENDED_GEO_LOOKUP"] = 54] = "REQUEST_TYPE_EXTENDED_GEO_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_QUERY_UNDERSTANDING = 55;
     */
    RequestType[RequestType["REQUEST_TYPE_QUERY_UNDERSTANDING"] = 55] = "REQUEST_TYPE_QUERY_UNDERSTANDING";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_POI_AT_ADDRESS_LOOKUP = 56;
     */
    RequestType[RequestType["REQUEST_TYPE_POI_AT_ADDRESS_LOOKUP"] = 56] = "REQUEST_TYPE_POI_AT_ADDRESS_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_TRANSIT_NEARBY_PAYMENT_METHOD_LOOKUP = 57;
     */
    RequestType[RequestType["REQUEST_TYPE_TRANSIT_NEARBY_PAYMENT_METHOD_LOOKUP"] = 57] = "REQUEST_TYPE_TRANSIT_NEARBY_PAYMENT_METHOD_LOOKUP";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_PLACECARD_ENRICHMENT = 58;
     */
    RequestType[RequestType["REQUEST_TYPE_PLACECARD_ENRICHMENT"] = 58] = "REQUEST_TYPE_PLACECARD_ENRICHMENT";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN59 = 59;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN59"] = 59] = "REQUEST_TYPE_UNKNOWN59";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN60 = 60;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN60"] = 60] = "REQUEST_TYPE_UNKNOWN60";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN61 = 61;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN61"] = 61] = "REQUEST_TYPE_UNKNOWN61";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN62 = 62;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN62"] = 62] = "REQUEST_TYPE_UNKNOWN62";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN63 = 63;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN63"] = 63] = "REQUEST_TYPE_UNKNOWN63";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN64 = 64;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN64"] = 64] = "REQUEST_TYPE_UNKNOWN64";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN65 = 65;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN65"] = 65] = "REQUEST_TYPE_UNKNOWN65";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN66 = 66;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN66"] = 66] = "REQUEST_TYPE_UNKNOWN66";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN67 = 67;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN67"] = 67] = "REQUEST_TYPE_UNKNOWN67";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN68 = 68;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN68"] = 68] = "REQUEST_TYPE_UNKNOWN68";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN69 = 69;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN69"] = 69] = "REQUEST_TYPE_UNKNOWN69";
    /**
     * @generated from protobuf enum value: REQUEST_TYPE_UNKNOWN70 = 70;
     */
    RequestType[RequestType["REQUEST_TYPE_UNKNOWN70"] = 70] = "REQUEST_TYPE_UNKNOWN70";
})(RequestType || (RequestType = {}));
// @generated message type with reflection information, may provide speed optimized methods
class PDPlaceRequest$Type extends MessageType {
    constructor() {
        super("PDPlaceRequest", [
            { no: 2, name: "clientMetadata", kind: "message", T: () => GEOPDClientMetadata },
            { no: 3, name: "displayLanguages", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "spokenLanguages", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "requestedComponents", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => GEOPDComponentInfo },
            { no: 6, name: "suppressResultsRequiringAttribution", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 7, name: "requestType", kind: "enum", T: () => ["RequestType", RequestType] },
            { no: 9, name: "displayRegion", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value) {
        const message = globalThis.Object.create((this.messagePrototype));
        message.displayLanguages = [];
        message.spokenLanguages = [];
        message.requestedComponents = [];
        message.requestType = 0;
        message.displayRegion = "";
        if (value !== undefined)
            reflectionMergePartial(this, message, value);
        return message;
    }
    internalBinaryRead(reader, length, options, target) {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* GEOPDClientMetadata clientMetadata */ 2:
                    message.clientMetadata = GEOPDClientMetadata.internalBinaryRead(reader, reader.uint32(), options, message.clientMetadata);
                    break;
                case /* repeated string displayLanguages */ 3:
                    message.displayLanguages.push(reader.string());
                    break;
                case /* repeated string spokenLanguages */ 4:
                    message.spokenLanguages.push(reader.string());
                    break;
                case /* repeated GEOPDComponentInfo requestedComponents */ 5:
                    message.requestedComponents.push(GEOPDComponentInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional bool suppressResultsRequiringAttribution */ 6:
                    message.suppressResultsRequiringAttribution = reader.bool();
                    break;
                case /* RequestType requestType */ 7:
                    message.requestType = reader.int32();
                    break;
                case /* string displayRegion */ 9:
                    message.displayRegion = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message, writer, options) {
        /* GEOPDClientMetadata clientMetadata = 2; */
        if (message.clientMetadata)
            GEOPDClientMetadata.internalBinaryWrite(message.clientMetadata, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated string displayLanguages = 3; */
        for (let i = 0; i < message.displayLanguages.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.displayLanguages[i]);
        /* repeated string spokenLanguages = 4; */
        for (let i = 0; i < message.spokenLanguages.length; i++)
            writer.tag(4, WireType.LengthDelimited).string(message.spokenLanguages[i]);
        /* repeated GEOPDComponentInfo requestedComponents = 5; */
        for (let i = 0; i < message.requestedComponents.length; i++)
            GEOPDComponentInfo.internalBinaryWrite(message.requestedComponents[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* optional bool suppressResultsRequiringAttribution = 6; */
        if (message.suppressResultsRequiringAttribution !== undefined)
            writer.tag(6, WireType.Varint).bool(message.suppressResultsRequiringAttribution);
        /* RequestType requestType = 7; */
        if (message.requestType !== 0)
            writer.tag(7, WireType.Varint).int32(message.requestType);
        /* string displayRegion = 9; */
        if (message.displayRegion !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.displayRegion);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message PDPlaceRequest
 */
export const PDPlaceRequest = new PDPlaceRequest$Type();
