// @generated by protobuf-ts 2.9.4 with parameter generate_dependencies,long_type_number,keep_enum_prefix,output_javascript
// @generated from protobuf file "GEOResourceManifestDownload.proto" (package "com.apple.geo.protobuf.geo", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { TileSet } from "./com.apple.geobuf.geo.proto";
import { TileSetRegion } from "./com.apple.geobuf.geo.proto";
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.RegionalResource
 */
export interface RegionalResource {
    /**
     * @generated from protobuf field: uint32 x = 1;
     */
    x: number;
    /**
     * @generated from protobuf field: uint32 y = 2;
     */
    y: number;
    /**
     * @generated from protobuf field: uint32 z = 3;
     */
    z: number;
    /**
     * @generated from protobuf field: repeated string icon = 4;
     */
    icon: string[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.Attribution attribution = 6;
     */
    attribution: Attribution[];
    /**
     * @generated from protobuf field: repeated string iconChecksum = 7;
     */
    iconChecksum: string[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.TileSetRegion tileRange = 29;
     */
    tileRange: TileSetRegion[];
    /**
     * @generated from protobuf field: repeated uint32 validSubManifestVersion = 30;
     */
    validSubManifestVersion: number[];
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.RegionalResourceIndex
 */
export interface RegionalResourceIndex {
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.RegionalResourceTile
 */
export interface RegionalResourceTile {
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.RegionalResourceRegion
 */
export interface RegionalResourceRegion {
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.TileGroup
 */
export interface TileGroup {
    /**
     * @generated from protobuf field: uint32 identifier = 1;
     */
    identifier: number;
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.TileGroup.VersionedTileSet tileSet = 2;
     */
    tileSet: TileGroup_VersionedTileSet[];
    /**
     * @generated from protobuf field: repeated uint32 styleSheetIndex = 3 [packed = false];
     */
    styleSheetIndex: number[];
    /**
     * @generated from protobuf field: repeated uint32 textureIndex = 4 [packed = false];
     */
    textureIndex: number[];
    /**
     * @generated from protobuf field: repeated uint32 fontIndex = 5 [packed = false];
     */
    fontIndex: number[];
    /**
     * @generated from protobuf field: repeated uint32 iconIndex = 6 [packed = false];
     */
    iconIndex: number[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.RegionalResourceIndex regionalResourceIndex = 7;
     */
    regionalResourceIndex: RegionalResourceIndex[];
    /**
     * @generated from protobuf field: repeated uint32 xmlIndex = 8 [packed = false];
     */
    xmlIndex: number[];
    /**
     * @generated from protobuf field: repeated uint32 attributionIndex = 10 [packed = false];
     */
    attributionIndex: number[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.TileSetRegion hybridUnavailableRegion = 11;
     */
    hybridUnavailableRegion: TileSetRegion[];
    /**
     * @generated from protobuf field: repeated uint32 resourceIndex = 12 [packed = false];
     */
    resourceIndex: number[];
    /**
     * @generated from protobuf field: uint32 muninVersion = 14;
     */
    muninVersion: number;
    /**
     * @generated from protobuf field: uint32 offlineMetadataIndex = 15;
     */
    offlineMetadataIndex: number;
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.TileGroup.VersionedTileSet
 */
export interface TileGroup_VersionedTileSet {
    /**
     * @generated from protobuf field: uint32 tileSetIndex = 1;
     */
    tileSetIndex: number;
    /**
     * @generated from protobuf field: uint32 identifier = 2;
     */
    identifier: number;
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.ResourceFilter
 */
export interface ResourceFilter {
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.ResourceFilter.Scale scale = 1;
     */
    scale: ResourceFilter_Scale[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.ResourceFilter.Scenario scenario = 2;
     */
    scenario: ResourceFilter_Scenario[];
}
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.ResourceFilter.Scale
 */
export declare enum ResourceFilter_Scale {
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCALE_UNKNOWN = 0;
     */
    RESOURCE_FILTER_SCALE_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCALE_1X = 1;
     */
    RESOURCE_FILTER_SCALE_1X = 1,
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCALE_2X = 2;
     */
    RESOURCE_FILTER_SCALE_2X = 2,
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCALE_3X = 3;
     */
    RESOURCE_FILTER_SCALE_3X = 3
}
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.ResourceFilter.Scenario
 */
export declare enum ResourceFilter_Scenario {
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_UNKNOWN = 0;
     */
    RESOURCE_FILTER_SCENARIO_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_CARPLAY = 1;
     */
    RESOURCE_FILTER_SCENARIO_CARPLAY = 1,
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_NAVIGATION = 2;
     */
    RESOURCE_FILTER_SCENARIO_NAVIGATION = 2,
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_HIGHVISIBILITY = 3;
     */
    RESOURCE_FILTER_SCENARIO_HIGHVISIBILITY = 3,
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_EXPLICIT = 4;
     */
    RESOURCE_FILTER_SCENARIO_EXPLICIT = 4
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.Resource
 */
export interface Resource {
    /**
     * @generated from protobuf field: com.apple.geo.protobuf.geo.Resource.ResourceType resourceType = 1;
     */
    resourceType: Resource_ResourceType;
    /**
     * @generated from protobuf field: string filename = 2;
     */
    filename: string;
    /**
     * @generated from protobuf field: bytes checksum = 3;
     */
    checksum: Uint8Array;
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.TileSetRegion region = 4;
     */
    region: TileSetRegion[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.ResourceFilter filter = 5;
     */
    filter: ResourceFilter[];
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.Resource.ConnectionType connectionType = 6;
     */
    connectionType?: Resource_ConnectionType;
    /**
     * @generated from protobuf field: optional uint32 preferWiFiAllowedStaleThreshold = 7;
     */
    preferWiFiAllowedStaleThreshold?: number;
    /**
     * @generated from protobuf field: com.apple.geo.protobuf.geo.Resource.ValidationMethod validationMethod = 8;
     */
    validationMethod: Resource_ValidationMethod;
    /**
     * @generated from protobuf field: optional uint32 alternateResourceURLIndex = 9;
     */
    alternateResourceURLIndex?: number;
    /**
     * @generated from protobuf field: com.apple.geo.protobuf.geo.Resource.UpdateMethod updateMethod = 10;
     */
    updateMethod: Resource_UpdateMethod;
    /**
     * @generated from protobuf field: optional uint32 timeToLiveSeconds = 11;
     */
    timeToLiveSeconds?: number;
}
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.Resource.ResourceType
 */
export declare enum Resource_ResourceType {
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_STYLESHEET = 0;
     */
    RESOURCE_TYPE_STYLESHEET = 0,
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_TEXTURE = 1;
     */
    RESOURCE_TYPE_TEXTURE = 1,
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_FONT = 2;
     */
    RESOURCE_TYPE_FONT = 2,
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_ICON = 3;
     */
    RESOURCE_TYPE_ICON = 3,
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_XML = 4;
     */
    RESOURCE_TYPE_XML = 4,
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_ATTRIBUTION_LOGO = 5;
     */
    RESOURCE_TYPE_ATTRIBUTION_LOGO = 5,
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_ATTRIBUTION_BADGE = 6;
     */
    RESOURCE_TYPE_ATTRIBUTION_BADGE = 6,
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_OTHER = 7;
     */
    RESOURCE_TYPE_OTHER = 7
}
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.Resource.ConnectionType
 */
export declare enum Resource_ConnectionType {
    /**
     * @generated from protobuf enum value: RESOURCE_DOWNLOAD_CONNECTION_TYPE_UNKNOWN = 0;
     */
    RESOURCE_DOWNLOAD_CONNECTION_TYPE_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: RESOURCE_DOWNLOAD_CONNECTION_TYPE_CELLULAR = 1;
     */
    RESOURCE_DOWNLOAD_CONNECTION_TYPE_CELLULAR = 1,
    /**
     * @generated from protobuf enum value: RESOURCE_DOWNLOAD_CONNECTION_TYPE_PREFER_WIFI = 2;
     */
    RESOURCE_DOWNLOAD_CONNECTION_TYPE_PREFER_WIFI = 2,
    /**
     * @generated from protobuf enum value: RESOURCE_DOWNLOAD_CONNECTION_TYPE_WIFI_ONLY = 3;
     */
    RESOURCE_DOWNLOAD_CONNECTION_TYPE_WIFI_ONLY = 3
}
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.Resource.ValidationMethod
 */
export declare enum Resource_ValidationMethod {
    /**
     * @generated from protobuf enum value: SHA1 = 0;
     */
    SHA1 = 0,
    /**
     * @generated from protobuf enum value: CMS = 1;
     */
    CMS = 1
}
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.Resource.UpdateMethod
 */
export declare enum Resource_UpdateMethod {
    /**
     * @generated from protobuf enum value: VERSIONED = 0;
     */
    VERSIONED = 0,
    /**
     * @generated from protobuf enum value: ETAG = 1;
     */
    ETAG = 1
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.Attribution
 */
export interface Attribution {
    /**
     * @generated from protobuf field: optional string badge = 1;
     */
    badge?: string;
    /**
     * @generated from protobuf field: optional string logo = 2;
     */
    logo?: string;
    /**
     * @generated from protobuf field: string name = 3;
     */
    name: string;
    /**
     * @generated from protobuf field: string url = 4;
     */
    url: string;
    /**
     * @generated from protobuf field: optional string badgeChecksum = 5;
     */
    badgeChecksum?: string;
    /**
     * @generated from protobuf field: optional string logoChecksum = 6;
     */
    logoChecksum?: string;
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.Resource resource = 7;
     */
    resource: Resource[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.TileSetRegion region = 8;
     */
    region: TileSetRegion[];
    /**
     * @generated from protobuf field: optional uint32 dataSet = 9;
     */
    dataSet?: number;
    /**
     * @generated from protobuf field: optional uint32 linkDisplayStringIndex = 10;
     */
    linkDisplayStringIndex?: number;
    /**
     * @generated from protobuf field: optional string plainTextURL = 11;
     */
    plainTextURL?: string;
    /**
     * @generated from protobuf field: optional bytes plainTextURLSHA256Checksum = 12;
     */
    plainTextURLSHA256Checksum?: Uint8Array;
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.ServiceVersion
 */
export interface ServiceVersion {
    /**
     * @generated from protobuf field: repeated string versionDomain = 1;
     */
    versionDomain: string[];
    /**
     * @generated from protobuf field: uint32 minimumVersion = 2;
     */
    minimumVersion: number;
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.VersionManifest
 */
export interface VersionManifest {
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.ServiceVersion serviceVersion = 1;
     */
    serviceVersion: ServiceVersion[];
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.DataSetDescription
 */
export interface DataSetDescription {
    /**
     * @generated from protobuf field: uint32 identifier = 1;
     */
    identifier: number;
    /**
     * @generated from protobuf field: string dataSetDescription = 2;
     */
    dataSetDescription: string;
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.DataSetURLOverride
 */
export interface DataSetURLOverride {
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.MuninVersion
 */
export interface MuninVersion {
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.URLInfo
 */
export interface URLInfo {
    /**
     * @generated from protobuf field: string url = 1;
     */
    url: string;
    /**
     * @generated from protobuf field: optional bool useAuthProxy = 2;
     */
    useAuthProxy?: boolean;
    /**
     * @generated from protobuf field: bool supportsMultipathTCP = 3;
     */
    supportsMultipathTCP: boolean;
    /**
     * @generated from protobuf field: optional uint32 alternativeMultipathTCPPort = 4;
     */
    alternativeMultipathTCPPort?: number;
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.URLInfoSet
 */
export interface URLInfoSet {
    /**
     * @generated from protobuf field: optional uint32 dataSet = 1;
     */
    dataSet?: number;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo resourcesURL = 2;
     */
    resourcesURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo searchAttributionManifestURL = 3;
     */
    searchAttributionManifestURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo directionsURL = 4;
     */
    directionsURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo etaURL = 5;
     */
    etaURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo batchReverseGeocoderURL = 6;
     */
    batchReverseGeocoderURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo simpleETAURL = 7;
     */
    simpleETAURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo addressCorrectionInitURL = 8;
     */
    addressCorrectionInitURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo addressCorrectionUpdateURL = 9;
     */
    addressCorrectionUpdateURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo polyLocationShiftURL = 10;
     */
    polyLocationShiftURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo problemSubmissionURL = 11;
     */
    problemSubmissionURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo problemStatusURL = 12;
     */
    problemStatusURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo reverseGeocoderVersionsURL = 13;
     */
    reverseGeocoderVersionsURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo problemCategoriesURL = 14;
     */
    problemCategoriesURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo announcementsURL = 15;
     */
    announcementsURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo dispatcherURL = 16;
     */
    dispatcherURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo problemOptInURL = 17;
     */
    problemOptInURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo abExperimentURL = 18;
     */
    abExperimentURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo businessPortalBaseURL = 19;
     */
    businessPortalBaseURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo logMessageUsageURL = 20;
     */
    logMessageUsageURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo spatialLookupURL = 21;
     */
    spatialLookupURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo realtimeTrafficProbeURL = 22;
     */
    realtimeTrafficProbeURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo batchTrafficProbeURL = 23;
     */
    batchTrafficProbeURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo proactiveRoutingURL = 24;
     */
    proactiveRoutingURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo logMessageUsageV3URL = 25;
     */
    logMessageUsageV3URL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo backgroundDispatcherURL = 26;
     */
    backgroundDispatcherURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo bluePOIDispatcherURL = 27;
     */
    bluePOIDispatcherURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo backgroundRevGeoURL = 28;
     */
    backgroundRevGeoURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo wifiConnectionQualityProbeURL = 29;
     */
    wifiConnectionQualityProbeURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo muninBaseURL = 30;
     */
    muninBaseURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo authProxyURL = 31;
     */
    authProxyURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo wifiQualityURL = 32;
     */
    wifiQualityURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo feedbackSubmissionURL = 33;
     */
    feedbackSubmissionURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo feedbackLookupURL = 34;
     */
    feedbackLookupURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo junctionImageServiceURL = 35;
     */
    junctionImageServiceURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo analyticsCohortSessionURL = 36;
     */
    analyticsCohortSessionURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo analyticsLongSessionURL = 37;
     */
    analyticsLongSessionURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo analyticsShortSessionURL = 38;
     */
    analyticsShortSessionURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo analyticsSessionlessURL = 39;
     */
    analyticsSessionlessURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo webModuleBaseURL = 40;
     */
    webModuleBaseURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo wifiQualityTileURL = 41;
     */
    wifiQualityTileURL?: URLInfo;
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.URLInfo alternateResourcesURL = 42;
     */
    alternateResourcesURL: URLInfo[];
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo tokenAuthenticationURL = 43;
     */
    tokenAuthenticationURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo authenticatedClientFeatureFlagURL = 44;
     */
    authenticatedClientFeatureFlagURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo addressCorrectionTaggedLocationURL = 45;
     */
    addressCorrectionTaggedLocationURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo proactiveAppClipURL = 46;
     */
    proactiveAppClipURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo enrichmentSubmissionURL = 47;
     */
    enrichmentSubmissionURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo ugcLogDiscardURL = 48;
     */
    ugcLogDiscardURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo batchReverseGeocoderPlaceRequestURL = 49;
     */
    batchReverseGeocoderPlaceRequestURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo pressureProbeDataURL = 50;
     */
    pressureProbeDataURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo poiBusynessActivityCollectionURL = 51;
     */
    poiBusynessActivityCollectionURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo rapWebBundleURL = 52;
     */
    rapWebBundleURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo networkSelectionHarvestURL = 53;
     */
    networkSelectionHarvestURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo offlineDataBatchListURL = 54;
     */
    offlineDataBatchListURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo offlineDataSizeURL = 55;
     */
    offlineDataSizeURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo offlineDataDownloadBaseURL = 56;
     */
    offlineDataDownloadBaseURL?: URLInfo;
    /**
     * @generated from protobuf field: optional com.apple.geo.protobuf.geo.URLInfo bcxDispatcherURL = 57;
     */
    bcxDispatcherURL?: URLInfo;
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.MuninBucket
 */
export interface MuninBucket {
    /**
     * @generated from protobuf field: uint32 bucketID = 3;
     */
    bucketID: number;
    /**
     * @generated from protobuf field: string bucketURL = 4;
     */
    bucketURL: string;
    /**
     * @generated from protobuf field: optional uint32 lodLevel = 5;
     */
    lodLevel?: number;
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.DisplayString
 */
export interface DisplayString {
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.LocalizedString localizedString = 1;
     */
    localizedString: LocalizedString[];
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.LocalizedString
 */
export interface LocalizedString {
    /**
     * @generated from protobuf field: string locale = 1;
     */
    locale: string;
    /**
     * @generated from protobuf field: string stringValue = 3;
     */
    stringValue: string;
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.MapRegion
 */
export interface MapRegion {
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.OfflineMetadata
 */
export interface OfflineMetadata {
    /**
     * @generated from protobuf field: uint64 dataVersion = 1;
     */
    dataVersion: number;
    /**
     * @generated from protobuf field: uint32 regulatoryRegionId = 2;
     */
    regulatoryRegionId: number;
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.Resources
 */
export interface Resources {
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.TileGroup tileGroup = 1;
     */
    tileGroup: TileGroup[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.TileSet tileSet = 2;
     */
    tileSet: TileSet[];
    /**
     * @generated from protobuf field: repeated string styleSheet = 3;
     */
    styleSheet: string[];
    /**
     * @generated from protobuf field: repeated string texture = 4;
     */
    texture: string[];
    /**
     * @generated from protobuf field: repeated string font = 5;
     */
    font: string[];
    /**
     * @generated from protobuf field: repeated string icon = 6;
     */
    icon: string[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.RegionalResource regionalResource = 8;
     */
    regionalResource: RegionalResource[];
    /**
     * @generated from protobuf field: repeated string xml = 9;
     */
    xml: string[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.Attribution attribution = 11;
     */
    attribution: Attribution[];
    /**
     * @generated from protobuf field: string authToken = 30;
     */
    authToken: string;
    /**
     * @generated from protobuf field: optional string resourcesURL = 31;
     */
    resourcesURL?: string;
    /**
     * @generated from protobuf field: optional string searchURL = 32;
     */
    searchURL?: string;
    /**
     * @generated from protobuf field: optional string searchAttributionManifestURL = 33;
     */
    searchAttributionManifestURL?: string;
    /**
     * @generated from protobuf field: optional string autocompleteURL = 34;
     */
    autocompleteURL?: string;
    /**
     * @generated from protobuf field: optional string reverseGeocoderURL = 35;
     */
    reverseGeocoderURL?: string;
    /**
     * @generated from protobuf field: optional string forwardGeocoderURL = 36;
     */
    forwardGeocoderURL?: string;
    /**
     * @generated from protobuf field: optional string directionsURL = 37;
     */
    directionsURL?: string;
    /**
     * @generated from protobuf field: optional string etaURL = 38;
     */
    etaURL?: string;
    /**
     * @generated from protobuf field: optional string locationShiftURL = 39;
     */
    locationShiftURL?: string;
    /**
     * @generated from protobuf field: string releaseInfo = 40;
     */
    releaseInfo: string;
    /**
     * @generated from protobuf field: optional string batchReverseGeocoderURL = 41;
     */
    batchReverseGeocoderURL?: string;
    /**
     * @generated from protobuf field: optional string mapMatchURL = 42;
     */
    mapMatchURL?: string;
    /**
     * @generated from protobuf field: optional string simpleETAURL = 43;
     */
    simpleETAURL?: string;
    /**
     * @generated from protobuf field: repeated string styleSheetChecksum = 44;
     */
    styleSheetChecksum: string[];
    /**
     * @generated from protobuf field: repeated string textureChecksum = 45;
     */
    textureChecksum: string[];
    /**
     * @generated from protobuf field: repeated string fontChecksum = 46;
     */
    fontChecksum: string[];
    /**
     * @generated from protobuf field: repeated string iconChecksum = 47;
     */
    iconChecksum: string[];
    /**
     * @generated from protobuf field: repeated string xmlChecksum = 48;
     */
    xmlChecksum: string[];
    /**
     * @generated from protobuf field: optional string addressCorrectionInitURL = 49;
     */
    addressCorrectionInitURL?: string;
    /**
     * @generated from protobuf field: optional string addressCorrectionUpdateURL = 50;
     */
    addressCorrectionUpdateURL?: string;
    /**
     * @generated from protobuf field: optional string polyLocationShiftURL = 51;
     */
    polyLocationShiftURL?: string;
    /**
     * @generated from protobuf field: optional string problemSubmissionURL = 52;
     */
    problemSubmissionURL?: string;
    /**
     * @generated from protobuf field: optional string problemStatusURL = 53;
     */
    problemStatusURL?: string;
    /**
     * @generated from protobuf field: optional string reverseGeocoderVersionsURL = 54;
     */
    reverseGeocoderVersionsURL?: string;
    /**
     * @generated from protobuf field: optional string problemCategoriesURL = 55;
     */
    problemCategoriesURL?: string;
    /**
     * @generated from protobuf field: optional string usageURL = 56;
     */
    usageURL?: string;
    /**
     * @generated from protobuf field: optional string businessCallerIDURL = 58;
     */
    businessCallerIDURL?: string;
    /**
     * @generated from protobuf field: optional string problemNotificationAvailabilityURL = 59;
     */
    problemNotificationAvailabilityURL?: string;
    /**
     * @generated from protobuf field: optional string announcementsURL = 61;
     */
    announcementsURL?: string;
    /**
     * @generated from protobuf field: repeated string announcementsSupportedLanguage = 62;
     */
    announcementsSupportedLanguage: string[];
    /**
     * @generated from protobuf field: optional string businessNameResolutionURL = 63;
     */
    businessNameResolutionURL?: string;
    /**
     * @generated from protobuf field: optional string dispatcherURL = 64;
     */
    dispatcherURL?: string;
    /**
     * @generated from protobuf field: optional string problemOptInURL = 65;
     */
    problemOptInURL?: string;
    /**
     * @generated from protobuf field: com.apple.geo.protobuf.geo.VersionManifest versionManifest = 66;
     */
    versionManifest?: VersionManifest;
    /**
     * @generated from protobuf field: optional string abExperimentURL = 67;
     */
    abExperimentURL?: string;
    /**
     * @generated from protobuf field: optional string businessPortalBaseURL = 68;
     */
    businessPortalBaseURL?: string;
    /**
     * @generated from protobuf field: optional string logMessageUsageURL = 69;
     */
    logMessageUsageURL?: string;
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.MapRegion locationShiftEnabledRegion = 70;
     */
    locationShiftEnabledRegion: MapRegion[];
    /**
     * @generated from protobuf field: optional uint32 locationShiftVersion = 71;
     */
    locationShiftVersion?: number;
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.Resource resource = 72;
     */
    resource: Resource[];
    /**
     * @generated from protobuf field: optional string spatialLookupURL = 73;
     */
    spatialLookupURL?: string;
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.DataSetDescription dataSet = 74;
     */
    dataSet: DataSetDescription[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.DataSetURLOverride dataSetURLOverride = 75;
     */
    dataSetURLOverride: DataSetURLOverride[];
    /**
     * @generated from protobuf field: optional string realtimeTrafficProbeURL = 77;
     */
    realtimeTrafficProbeURL?: string;
    /**
     * @generated from protobuf field: optional string batchTrafficProbeURL = 78;
     */
    batchTrafficProbeURL?: string;
    /**
     * @generated from protobuf field: optional string proactiveRoutingURL = 79;
     */
    proactiveRoutingURL?: string;
    /**
     * @generated from protobuf field: optional string logMessageUsageV3URL = 80;
     */
    logMessageUsageV3URL?: string;
    /**
     * @generated from protobuf field: optional string backgroundDispatcherURL = 81;
     */
    backgroundDispatcherURL?: string;
    /**
     * @generated from protobuf field: optional string bluePOIDispatcherURL = 82;
     */
    bluePOIDispatcherURL?: string;
    /**
     * @generated from protobuf field: optional string backgroundRevGeoURL = 83;
     */
    backgroundRevGeoURL?: string;
    /**
     * @generated from protobuf field: optional string wifiConnectionQualityProbeURL = 85;
     */
    wifiConnectionQualityProbeURL?: string;
    /**
     * @generated from protobuf field: optional string muninBaseURL = 88;
     */
    muninBaseURL?: string;
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.MuninVersion muninVersion = 89;
     */
    muninVersion: MuninVersion[];
    /**
     * @generated from protobuf field: optional string authProxyURL = 91;
     */
    authProxyURL?: string;
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.URLInfoSet urlInfoSet = 92;
     */
    urlInfoSet: URLInfoSet[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.MuninBucket muninBucket = 93;
     */
    muninBucket: MuninBucket[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.DisplayString displayString = 94;
     */
    displayString: DisplayString[];
    /**
     * @generated from protobuf field: repeated com.apple.geo.protobuf.geo.OfflineMetadata offlineMetadata = 95;
     */
    offlineMetadata: OfflineMetadata[];
}
/**
 * @generated from protobuf message com.apple.geo.protobuf.geo.ResourceManifestDownload
 */
export interface ResourceManifestDownload {
    /**
     * @generated from protobuf field: com.apple.geo.protobuf.geo.Resources resources = 1;
     */
    resources?: Resources;
}
declare class RegionalResource$Type extends MessageType<RegionalResource> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.RegionalResource
 */
export declare const RegionalResource: RegionalResource$Type;
declare class RegionalResourceIndex$Type extends MessageType<RegionalResourceIndex> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.RegionalResourceIndex
 */
export declare const RegionalResourceIndex: RegionalResourceIndex$Type;
declare class RegionalResourceTile$Type extends MessageType<RegionalResourceTile> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.RegionalResourceTile
 */
export declare const RegionalResourceTile: RegionalResourceTile$Type;
declare class RegionalResourceRegion$Type extends MessageType<RegionalResourceRegion> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.RegionalResourceRegion
 */
export declare const RegionalResourceRegion: RegionalResourceRegion$Type;
declare class TileGroup$Type extends MessageType<TileGroup> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.TileGroup
 */
export declare const TileGroup: TileGroup$Type;
declare class TileGroup_VersionedTileSet$Type extends MessageType<TileGroup_VersionedTileSet> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.TileGroup.VersionedTileSet
 */
export declare const TileGroup_VersionedTileSet: TileGroup_VersionedTileSet$Type;
declare class ResourceFilter$Type extends MessageType<ResourceFilter> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.ResourceFilter
 */
export declare const ResourceFilter: ResourceFilter$Type;
declare class Resource$Type extends MessageType<Resource> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.Resource
 */
export declare const Resource: Resource$Type;
declare class Attribution$Type extends MessageType<Attribution> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.Attribution
 */
export declare const Attribution: Attribution$Type;
declare class ServiceVersion$Type extends MessageType<ServiceVersion> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.ServiceVersion
 */
export declare const ServiceVersion: ServiceVersion$Type;
declare class VersionManifest$Type extends MessageType<VersionManifest> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.VersionManifest
 */
export declare const VersionManifest: VersionManifest$Type;
declare class DataSetDescription$Type extends MessageType<DataSetDescription> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.DataSetDescription
 */
export declare const DataSetDescription: DataSetDescription$Type;
declare class DataSetURLOverride$Type extends MessageType<DataSetURLOverride> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.DataSetURLOverride
 */
export declare const DataSetURLOverride: DataSetURLOverride$Type;
declare class MuninVersion$Type extends MessageType<MuninVersion> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.MuninVersion
 */
export declare const MuninVersion: MuninVersion$Type;
declare class URLInfo$Type extends MessageType<URLInfo> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.URLInfo
 */
export declare const URLInfo: URLInfo$Type;
declare class URLInfoSet$Type extends MessageType<URLInfoSet> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.URLInfoSet
 */
export declare const URLInfoSet: URLInfoSet$Type;
declare class MuninBucket$Type extends MessageType<MuninBucket> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.MuninBucket
 */
export declare const MuninBucket: MuninBucket$Type;
declare class DisplayString$Type extends MessageType<DisplayString> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.DisplayString
 */
export declare const DisplayString: DisplayString$Type;
declare class LocalizedString$Type extends MessageType<LocalizedString> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.LocalizedString
 */
export declare const LocalizedString: LocalizedString$Type;
declare class MapRegion$Type extends MessageType<MapRegion> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.MapRegion
 */
export declare const MapRegion: MapRegion$Type;
declare class OfflineMetadata$Type extends MessageType<OfflineMetadata> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.OfflineMetadata
 */
export declare const OfflineMetadata: OfflineMetadata$Type;
declare class Resources$Type extends MessageType<Resources> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.Resources
 */
export declare const Resources: Resources$Type;
declare class ResourceManifestDownload$Type extends MessageType<ResourceManifestDownload> {
    constructor();
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.ResourceManifestDownload
 */
export declare const ResourceManifestDownload: ResourceManifestDownload$Type;
export {};
