// @generated by protobuf-ts 2.9.3 with parameter long_type_string,use_proto_field_name,output_javascript,optimize_code_size
// @generated from protobuf file "Resources.proto" (package "com.apple.geo.protobuf.geo", syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.9.3 with parameter long_type_string,use_proto_field_name,output_javascript,optimize_code_size
// @generated from protobuf file "Resources.proto" (package "com.apple.geo.protobuf.geo", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.TileSet.TileSetVersionUpdateBehavior
 */
export var TileSet_TileSetVersionUpdateBehavior;
(function (TileSet_TileSetVersionUpdateBehavior) {
    /**
     * @generated from protobuf enum value: TILE_UPDATE_BEHAVIOR_FLUSH = 0;
     */
    TileSet_TileSetVersionUpdateBehavior[TileSet_TileSetVersionUpdateBehavior["TILE_UPDATE_BEHAVIOR_FLUSH"] = 0] = "TILE_UPDATE_BEHAVIOR_FLUSH";
    /**
     * @generated from protobuf enum value: TILE_UPDATE_BEHAVIOR_ETAG = 1;
     */
    TileSet_TileSetVersionUpdateBehavior[TileSet_TileSetVersionUpdateBehavior["TILE_UPDATE_BEHAVIOR_ETAG"] = 1] = "TILE_UPDATE_BEHAVIOR_ETAG";
})(TileSet_TileSetVersionUpdateBehavior || (TileSet_TileSetVersionUpdateBehavior = {}));
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.TileSet.TileSetChecksumType
 */
export var TileSet_TileSetChecksumType;
(function (TileSet_TileSetChecksumType) {
    /**
     * @generated from protobuf enum value: CHECKSUM_TYPE_NONE = 0;
     */
    TileSet_TileSetChecksumType[TileSet_TileSetChecksumType["CHECKSUM_TYPE_NONE"] = 0] = "CHECKSUM_TYPE_NONE";
    /**
     * @generated from protobuf enum value: CHECKSUM_TYPE_APPENDED_MD5 = 1;
     */
    TileSet_TileSetChecksumType[TileSet_TileSetChecksumType["CHECKSUM_TYPE_APPENDED_MD5"] = 1] = "CHECKSUM_TYPE_APPENDED_MD5";
})(TileSet_TileSetChecksumType || (TileSet_TileSetChecksumType = {}));
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.TileSet.TileRequestStyle
 */
export var TileSet_TileRequestStyle;
(function (TileSet_TileRequestStyle) {
    /**
     * @generated from protobuf enum value: REQUEST_STYLE_LEGACY = 0;
     */
    TileSet_TileRequestStyle[TileSet_TileRequestStyle["REQUEST_STYLE_LEGACY"] = 0] = "REQUEST_STYLE_LEGACY";
    /**
     * @generated from protobuf enum value: REQUEST_STYLE_HEADER_PARAMS_VERSION_BASED_HMAC_AUTH = 1;
     */
    TileSet_TileRequestStyle[TileSet_TileRequestStyle["REQUEST_STYLE_HEADER_PARAMS_VERSION_BASED_HMAC_AUTH"] = 1] = "REQUEST_STYLE_HEADER_PARAMS_VERSION_BASED_HMAC_AUTH";
})(TileSet_TileRequestStyle || (TileSet_TileRequestStyle = {}));
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.ResourceFilter.Scale
 */
export var ResourceFilter_Scale;
(function (ResourceFilter_Scale) {
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCALE_UNKNOWN = 0;
     */
    ResourceFilter_Scale[ResourceFilter_Scale["RESOURCE_FILTER_SCALE_UNKNOWN"] = 0] = "RESOURCE_FILTER_SCALE_UNKNOWN";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCALE_1X = 1;
     */
    ResourceFilter_Scale[ResourceFilter_Scale["RESOURCE_FILTER_SCALE_1X"] = 1] = "RESOURCE_FILTER_SCALE_1X";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCALE_2X = 2;
     */
    ResourceFilter_Scale[ResourceFilter_Scale["RESOURCE_FILTER_SCALE_2X"] = 2] = "RESOURCE_FILTER_SCALE_2X";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCALE_3X = 3;
     */
    ResourceFilter_Scale[ResourceFilter_Scale["RESOURCE_FILTER_SCALE_3X"] = 3] = "RESOURCE_FILTER_SCALE_3X";
})(ResourceFilter_Scale || (ResourceFilter_Scale = {}));
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.ResourceFilter.Scenario
 */
export var ResourceFilter_Scenario;
(function (ResourceFilter_Scenario) {
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_UNKNOWN = 0;
     */
    ResourceFilter_Scenario[ResourceFilter_Scenario["RESOURCE_FILTER_SCENARIO_UNKNOWN"] = 0] = "RESOURCE_FILTER_SCENARIO_UNKNOWN";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_CARPLAY = 1;
     */
    ResourceFilter_Scenario[ResourceFilter_Scenario["RESOURCE_FILTER_SCENARIO_CARPLAY"] = 1] = "RESOURCE_FILTER_SCENARIO_CARPLAY";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_NAVIGATION = 2;
     */
    ResourceFilter_Scenario[ResourceFilter_Scenario["RESOURCE_FILTER_SCENARIO_NAVIGATION"] = 2] = "RESOURCE_FILTER_SCENARIO_NAVIGATION";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_HIGHVISIBILITY = 3;
     */
    ResourceFilter_Scenario[ResourceFilter_Scenario["RESOURCE_FILTER_SCENARIO_HIGHVISIBILITY"] = 3] = "RESOURCE_FILTER_SCENARIO_HIGHVISIBILITY";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_EXPLICIT = 4;
     */
    ResourceFilter_Scenario[ResourceFilter_Scenario["RESOURCE_FILTER_SCENARIO_EXPLICIT"] = 4] = "RESOURCE_FILTER_SCENARIO_EXPLICIT";
})(ResourceFilter_Scenario || (ResourceFilter_Scenario = {}));
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.Resource.ResourceType
 */
export var Resource_ResourceType;
(function (Resource_ResourceType) {
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_STYLESHEET = 0;
     */
    Resource_ResourceType[Resource_ResourceType["STYLESHEET"] = 0] = "STYLESHEET";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_TEXTURE = 1;
     */
    Resource_ResourceType[Resource_ResourceType["TEXTURE"] = 1] = "TEXTURE";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_FONT = 2;
     */
    Resource_ResourceType[Resource_ResourceType["FONT"] = 2] = "FONT";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_ICON = 3;
     */
    Resource_ResourceType[Resource_ResourceType["ICON"] = 3] = "ICON";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_XML = 4;
     */
    Resource_ResourceType[Resource_ResourceType["XML"] = 4] = "XML";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_ATTRIBUTION_LOGO = 5;
     */
    Resource_ResourceType[Resource_ResourceType["ATTRIBUTION_LOGO"] = 5] = "ATTRIBUTION_LOGO";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_ATTRIBUTION_BADGE = 6;
     */
    Resource_ResourceType[Resource_ResourceType["ATTRIBUTION_BADGE"] = 6] = "ATTRIBUTION_BADGE";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_OTHER = 7;
     */
    Resource_ResourceType[Resource_ResourceType["OTHER"] = 7] = "OTHER";
})(Resource_ResourceType || (Resource_ResourceType = {}));
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.Resource.ConnectionType
 */
export var Resource_ConnectionType;
(function (Resource_ConnectionType) {
    /**
     * @generated from protobuf enum value: RESOURCE_DOWNLOAD_CONNECTION_TYPE_UNKNOWN = 0;
     */
    Resource_ConnectionType[Resource_ConnectionType["RESOURCE_DOWNLOAD_CONNECTION_TYPE_UNKNOWN"] = 0] = "RESOURCE_DOWNLOAD_CONNECTION_TYPE_UNKNOWN";
    /**
     * @generated from protobuf enum value: RESOURCE_DOWNLOAD_CONNECTION_TYPE_CELLULAR = 1;
     */
    Resource_ConnectionType[Resource_ConnectionType["RESOURCE_DOWNLOAD_CONNECTION_TYPE_CELLULAR"] = 1] = "RESOURCE_DOWNLOAD_CONNECTION_TYPE_CELLULAR";
    /**
     * @generated from protobuf enum value: RESOURCE_DOWNLOAD_CONNECTION_TYPE_PREFER_WIFI = 2;
     */
    Resource_ConnectionType[Resource_ConnectionType["RESOURCE_DOWNLOAD_CONNECTION_TYPE_PREFER_WIFI"] = 2] = "RESOURCE_DOWNLOAD_CONNECTION_TYPE_PREFER_WIFI";
    /**
     * @generated from protobuf enum value: RESOURCE_DOWNLOAD_CONNECTION_TYPE_WIFI_ONLY = 3;
     */
    Resource_ConnectionType[Resource_ConnectionType["RESOURCE_DOWNLOAD_CONNECTION_TYPE_WIFI_ONLY"] = 3] = "RESOURCE_DOWNLOAD_CONNECTION_TYPE_WIFI_ONLY";
})(Resource_ConnectionType || (Resource_ConnectionType = {}));
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.Resource.ValidationMethod
 */
export var Resource_ValidationMethod;
(function (Resource_ValidationMethod) {
    /**
     * @generated from protobuf enum value: SHA1 = 0;
     */
    Resource_ValidationMethod[Resource_ValidationMethod["SHA1"] = 0] = "SHA1";
    /**
     * @generated from protobuf enum value: CMS = 1;
     */
    Resource_ValidationMethod[Resource_ValidationMethod["CMS"] = 1] = "CMS";
})(Resource_ValidationMethod || (Resource_ValidationMethod = {}));
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.Resource.UpdateMethod
 */
export var Resource_UpdateMethod;
(function (Resource_UpdateMethod) {
    /**
     * @generated from protobuf enum value: VERSIONED = 0;
     */
    Resource_UpdateMethod[Resource_UpdateMethod["VERSIONED"] = 0] = "VERSIONED";
    /**
     * @generated from protobuf enum value: ETAG = 1;
     */
    Resource_UpdateMethod[Resource_UpdateMethod["ETAG"] = 1] = "ETAG";
})(Resource_UpdateMethod || (Resource_UpdateMethod = {}));
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.TileSetStyle
 */
export var TileSetStyle;
(function (TileSetStyle) {
    /**
     * @generated from protobuf enum value: RASTER_STANDARD = 0;
     */
    TileSetStyle[TileSetStyle["RASTER_STANDARD"] = 0] = "RASTER_STANDARD";
    /**
     * @generated from protobuf enum value: VECTOR_STANDARD = 1;
     */
    TileSetStyle[TileSetStyle["VECTOR_STANDARD"] = 1] = "VECTOR_STANDARD";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_SEGMENTS_FOR_RASTER = 2;
     */
    TileSetStyle[TileSetStyle["VECTOR_TRAFFIC_SEGMENTS_FOR_RASTER"] = 2] = "VECTOR_TRAFFIC_SEGMENTS_FOR_RASTER";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_INCIDENTS_FOR_RASTER = 3;
     */
    TileSetStyle[TileSetStyle["VECTOR_TRAFFIC_INCIDENTS_FOR_RASTER"] = 3] = "VECTOR_TRAFFIC_INCIDENTS_FOR_RASTER";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_SEGMENTS_AND_INCIDENTS_FOR_RASTER = 4;
     */
    TileSetStyle[TileSetStyle["VECTOR_TRAFFIC_SEGMENTS_AND_INCIDENTS_FOR_RASTER"] = 4] = "VECTOR_TRAFFIC_SEGMENTS_AND_INCIDENTS_FOR_RASTER";
    /**
     * @generated from protobuf enum value: RASTER_STANDARD_BACKGROUND = 5;
     */
    TileSetStyle[TileSetStyle["RASTER_STANDARD_BACKGROUND"] = 5] = "RASTER_STANDARD_BACKGROUND";
    /**
     * @generated from protobuf enum value: RASTER_HYBRID = 6;
     */
    TileSetStyle[TileSetStyle["RASTER_HYBRID"] = 6] = "RASTER_HYBRID";
    /**
     * @generated from protobuf enum value: RASTER_SATELLITE = 7;
     */
    TileSetStyle[TileSetStyle["RASTER_SATELLITE"] = 7] = "RASTER_SATELLITE";
    /**
     * @generated from protobuf enum value: RASTER_TERRAIN = 8;
     */
    TileSetStyle[TileSetStyle["RASTER_TERRAIN"] = 8] = "RASTER_TERRAIN";
    /**
     * @generated from protobuf enum value: VECTOR_BUILDINGS = 11;
     */
    TileSetStyle[TileSetStyle["VECTOR_BUILDINGS"] = 11] = "VECTOR_BUILDINGS";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC = 12;
     */
    TileSetStyle[TileSetStyle["VECTOR_TRAFFIC"] = 12] = "VECTOR_TRAFFIC";
    /**
     * @generated from protobuf enum value: VECTOR_POI = 13;
     */
    TileSetStyle[TileSetStyle["VECTOR_POI"] = 13] = "VECTOR_POI";
    /**
     * @generated from protobuf enum value: SPUTNIK_METADATA = 14;
     */
    TileSetStyle[TileSetStyle["SPUTNIK_METADATA"] = 14] = "SPUTNIK_METADATA";
    /**
     * @generated from protobuf enum value: SPUTNIK_C3M = 15;
     */
    TileSetStyle[TileSetStyle["SPUTNIK_C3M"] = 15] = "SPUTNIK_C3M";
    /**
     * @generated from protobuf enum value: SPUTNIK_DSM = 16;
     */
    TileSetStyle[TileSetStyle["SPUTNIK_DSM"] = 16] = "SPUTNIK_DSM";
    /**
     * @generated from protobuf enum value: SPUTNIK_DSM_GLOBAL = 17;
     */
    TileSetStyle[TileSetStyle["SPUTNIK_DSM_GLOBAL"] = 17] = "SPUTNIK_DSM_GLOBAL";
    /**
     * @generated from protobuf enum value: VECTOR_REALISTIC = 18;
     */
    TileSetStyle[TileSetStyle["VECTOR_REALISTIC"] = 18] = "VECTOR_REALISTIC";
    /**
     * @generated from protobuf enum value: VECTOR_LEGACY_REALISTIC = 19;
     */
    TileSetStyle[TileSetStyle["VECTOR_LEGACY_REALISTIC"] = 19] = "VECTOR_LEGACY_REALISTIC";
    /**
     * @generated from protobuf enum value: VECTOR_ROADS = 20;
     */
    TileSetStyle[TileSetStyle["VECTOR_ROADS"] = 20] = "VECTOR_ROADS";
    /**
     * @generated from protobuf enum value: RASTER_VEGETATION = 21;
     */
    TileSetStyle[TileSetStyle["RASTER_VEGETATION"] = 21] = "RASTER_VEGETATION";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_SKELETON = 22;
     */
    TileSetStyle[TileSetStyle["VECTOR_TRAFFIC_SKELETON"] = 22] = "VECTOR_TRAFFIC_SKELETON";
    /**
     * @generated from protobuf enum value: RASTER_COASTLINE_MASK = 23;
     */
    TileSetStyle[TileSetStyle["RASTER_COASTLINE_MASK"] = 23] = "RASTER_COASTLINE_MASK";
    /**
     * @generated from protobuf enum value: RASTER_HILLSHADE = 24;
     */
    TileSetStyle[TileSetStyle["RASTER_HILLSHADE"] = 24] = "RASTER_HILLSHADE";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_WITH_GREEN = 25;
     */
    TileSetStyle[TileSetStyle["VECTOR_TRAFFIC_WITH_GREEN"] = 25] = "VECTOR_TRAFFIC_WITH_GREEN";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_STATIC = 26;
     */
    TileSetStyle[TileSetStyle["VECTOR_TRAFFIC_STATIC"] = 26] = "VECTOR_TRAFFIC_STATIC";
    /**
     * @generated from protobuf enum value: RASTER_COASTLINE_DROP_MASK = 27;
     */
    TileSetStyle[TileSetStyle["RASTER_COASTLINE_DROP_MASK"] = 27] = "RASTER_COASTLINE_DROP_MASK";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_SKELETON_WITH_HISTORICAL = 28;
     */
    TileSetStyle[TileSetStyle["VECTOR_TRAFFIC_SKELETON_WITH_HISTORICAL"] = 28] = "VECTOR_TRAFFIC_SKELETON_WITH_HISTORICAL";
    /**
     * @generated from protobuf enum value: VECTOR_SPEED_PROFILES = 29;
     */
    TileSetStyle[TileSetStyle["VECTOR_SPEED_PROFILES"] = 29] = "VECTOR_SPEED_PROFILES";
    /**
     * @generated from protobuf enum value: VECTOR_VENUES = 30;
     */
    TileSetStyle[TileSetStyle["VECTOR_VENUES"] = 30] = "VECTOR_VENUES";
    /**
     * @generated from protobuf enum value: RASTER_DOWN_SAMPLED = 31;
     */
    TileSetStyle[TileSetStyle["RASTER_DOWN_SAMPLED"] = 31] = "RASTER_DOWN_SAMPLED";
    /**
     * @generated from protobuf enum value: RASTER_COLOR_BALANCED = 32;
     */
    TileSetStyle[TileSetStyle["RASTER_COLOR_BALANCED"] = 32] = "RASTER_COLOR_BALANCED";
    /**
     * @generated from protobuf enum value: RASTER_SATELLITE_NIGHT = 33;
     */
    TileSetStyle[TileSetStyle["RASTER_SATELLITE_NIGHT"] = 33] = "RASTER_SATELLITE_NIGHT";
    /**
     * @generated from protobuf enum value: SPUTNIK_VECTOR_BORDER = 34;
     */
    TileSetStyle[TileSetStyle["SPUTNIK_VECTOR_BORDER"] = 34] = "SPUTNIK_VECTOR_BORDER";
    /**
     * @generated from protobuf enum value: RASTER_SATELLITE_DIGITIZE = 35;
     */
    TileSetStyle[TileSetStyle["RASTER_SATELLITE_DIGITIZE"] = 35] = "RASTER_SATELLITE_DIGITIZE";
    /**
     * @generated from protobuf enum value: RASTER_HILLSHADE_PARKS = 36;
     */
    TileSetStyle[TileSetStyle["RASTER_HILLSHADE_PARKS"] = 36] = "RASTER_HILLSHADE_PARKS";
    /**
     * @generated from protobuf enum value: VECTOR_TRANSIT = 37;
     */
    TileSetStyle[TileSetStyle["VECTOR_TRANSIT"] = 37] = "VECTOR_TRANSIT";
    /**
     * @generated from protobuf enum value: RASTER_STANDARD_BASE = 38;
     */
    TileSetStyle[TileSetStyle["RASTER_STANDARD_BASE"] = 38] = "RASTER_STANDARD_BASE";
    /**
     * @generated from protobuf enum value: RASTER_STANDARD_LABELS = 39;
     */
    TileSetStyle[TileSetStyle["RASTER_STANDARD_LABELS"] = 39] = "RASTER_STANDARD_LABELS";
    /**
     * @generated from protobuf enum value: RASTER_HYBRID_ROADS = 40;
     */
    TileSetStyle[TileSetStyle["RASTER_HYBRID_ROADS"] = 40] = "RASTER_HYBRID_ROADS";
    /**
     * @generated from protobuf enum value: RASTER_HYBRID_LABELS = 41;
     */
    TileSetStyle[TileSetStyle["RASTER_HYBRID_LABELS"] = 41] = "RASTER_HYBRID_LABELS";
    /**
     * @generated from protobuf enum value: FLYOVER_C3M_MESH = 42;
     */
    TileSetStyle[TileSetStyle["FLYOVER_C3M_MESH"] = 42] = "FLYOVER_C3M_MESH";
    /**
     * @generated from protobuf enum value: FLYOVER_C3M_JPEG_TEXTURE = 43;
     */
    TileSetStyle[TileSetStyle["FLYOVER_C3M_JPEG_TEXTURE"] = 43] = "FLYOVER_C3M_JPEG_TEXTURE";
    /**
     * @generated from protobuf enum value: FLYOVER_C3M_ASTC_TEXTURE = 44;
     */
    TileSetStyle[TileSetStyle["FLYOVER_C3M_ASTC_TEXTURE"] = 44] = "FLYOVER_C3M_ASTC_TEXTURE";
    /**
     * @generated from protobuf enum value: RASTER_SATELLITE_ASTC = 45;
     */
    TileSetStyle[TileSetStyle["RASTER_SATELLITE_ASTC"] = 45] = "RASTER_SATELLITE_ASTC";
    /**
     * @generated from protobuf enum value: RASTER_HYBRID_ROADS_AND_LABELS = 46;
     */
    TileSetStyle[TileSetStyle["RASTER_HYBRID_ROADS_AND_LABELS"] = 46] = "RASTER_HYBRID_ROADS_AND_LABELS";
    /**
     * @generated from protobuf enum value: VECTOR_TRANSIT_SELECTION = 47;
     */
    TileSetStyle[TileSetStyle["VECTOR_TRANSIT_SELECTION"] = 47] = "VECTOR_TRANSIT_SELECTION";
    /**
     * @generated from protobuf enum value: VECTOR_COVERAGE = 48;
     */
    TileSetStyle[TileSetStyle["VECTOR_COVERAGE"] = 48] = "VECTOR_COVERAGE";
    /**
     * @generated from protobuf enum value: FLYOVER_VISIBILITY = 49;
     */
    TileSetStyle[TileSetStyle["FLYOVER_VISIBILITY"] = 49] = "FLYOVER_VISIBILITY";
    /**
     * @generated from protobuf enum value: FLYOVER_SKYBOX = 50;
     */
    TileSetStyle[TileSetStyle["FLYOVER_SKYBOX"] = 50] = "FLYOVER_SKYBOX";
    /**
     * @generated from protobuf enum value: FLYOVER_NAVGRAPH = 51;
     */
    TileSetStyle[TileSetStyle["FLYOVER_NAVGRAPH"] = 51] = "FLYOVER_NAVGRAPH";
    /**
     * @generated from protobuf enum value: FLYOVER_METADATA = 52;
     */
    TileSetStyle[TileSetStyle["FLYOVER_METADATA"] = 52] = "FLYOVER_METADATA";
    /**
     * @generated from protobuf enum value: VECTOR_ROAD_NETWORK = 53;
     */
    TileSetStyle[TileSetStyle["VECTOR_ROAD_NETWORK"] = 53] = "VECTOR_ROAD_NETWORK";
    /**
     * @generated from protobuf enum value: VECTOR_LAND_COVER = 54;
     */
    TileSetStyle[TileSetStyle["VECTOR_LAND_COVER"] = 54] = "VECTOR_LAND_COVER";
    /**
     * @generated from protobuf enum value: VECTOR_DEBUG = 55;
     */
    TileSetStyle[TileSetStyle["VECTOR_DEBUG"] = 55] = "VECTOR_DEBUG";
    /**
     * @generated from protobuf enum value: VECTOR_STREET_POI = 56;
     */
    TileSetStyle[TileSetStyle["VECTOR_STREET_POI"] = 56] = "VECTOR_STREET_POI";
    /**
     * @generated from protobuf enum value: MUNIN_METADATA = 57;
     */
    TileSetStyle[TileSetStyle["MUNIN_METADATA"] = 57] = "MUNIN_METADATA";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_MERCATOR = 58;
     */
    TileSetStyle[TileSetStyle["VECTOR_SPR_MERCATOR"] = 58] = "VECTOR_SPR_MERCATOR";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_MODELS = 59;
     */
    TileSetStyle[TileSetStyle["VECTOR_SPR_MODELS"] = 59] = "VECTOR_SPR_MODELS";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_MATERIALS = 60;
     */
    TileSetStyle[TileSetStyle["VECTOR_SPR_MATERIALS"] = 60] = "VECTOR_SPR_MATERIALS";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_METADATA = 61;
     */
    TileSetStyle[TileSetStyle["VECTOR_SPR_METADATA"] = 61] = "VECTOR_SPR_METADATA";
    /**
     * @generated from protobuf enum value: VECTOR_TRACKS = 62;
     */
    TileSetStyle[TileSetStyle["VECTOR_TRACKS"] = 62] = "VECTOR_TRACKS";
    /**
     * @generated from protobuf enum value: VECTOR_RESERVED_2 = 63;
     */
    TileSetStyle[TileSetStyle["VECTOR_RESERVED_2"] = 63] = "VECTOR_RESERVED_2";
    /**
     * @generated from protobuf enum value: VECTOR_STREET_LANDMARKS = 64;
     */
    TileSetStyle[TileSetStyle["VECTOR_STREET_LANDMARKS"] = 64] = "VECTOR_STREET_LANDMARKS";
    /**
     * @generated from protobuf enum value: COARSE_LOCATION_POLYGONS = 65;
     */
    TileSetStyle[TileSetStyle["COARSE_LOCATION_POLYGONS"] = 65] = "COARSE_LOCATION_POLYGONS";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_ROADS = 66;
     */
    TileSetStyle[TileSetStyle["VECTOR_SPR_ROADS"] = 66] = "VECTOR_SPR_ROADS";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_STANDARD = 67;
     */
    TileSetStyle[TileSetStyle["VECTOR_SPR_STANDARD"] = 67] = "VECTOR_SPR_STANDARD";
    /**
     * @generated from protobuf enum value: VECTOR_POI_V2 = 68;
     */
    TileSetStyle[TileSetStyle["VECTOR_POI_V2"] = 68] = "VECTOR_POI_V2";
    /**
     * @generated from protobuf enum value: VECTOR_POLYGON_SELECTION = 69;
     */
    TileSetStyle[TileSetStyle["VECTOR_POLYGON_SELECTION"] = 69] = "VECTOR_POLYGON_SELECTION";
    /**
     * @generated from protobuf enum value: VL_METADATA = 70;
     */
    TileSetStyle[TileSetStyle["VL_METADATA"] = 70] = "VL_METADATA";
    /**
     * @generated from protobuf enum value: VL_DATA = 71;
     */
    TileSetStyle[TileSetStyle["VL_DATA"] = 71] = "VL_DATA";
    /**
     * @generated from protobuf enum value: PROACTIVE_APP_CLIP = 72;
     */
    TileSetStyle[TileSetStyle["PROACTIVE_APP_CLIP"] = 72] = "PROACTIVE_APP_CLIP";
    /**
     * @generated from protobuf enum value: VECTOR_BUILDINGS_V2 = 73;
     */
    TileSetStyle[TileSetStyle["VECTOR_BUILDINGS_V2"] = 73] = "VECTOR_BUILDINGS_V2";
    /**
     * @generated from protobuf enum value: POI_BUSYNESS = 74;
     */
    TileSetStyle[TileSetStyle["POI_BUSYNESS"] = 74] = "POI_BUSYNESS";
    /**
     * @generated from protobuf enum value: POI_DP_BUSYNESS = 75;
     */
    TileSetStyle[TileSetStyle["POI_DP_BUSYNESS"] = 75] = "POI_DP_BUSYNESS";
    /**
     * @generated from protobuf enum value: SMART_INTERFACE_SELECTION = 76;
     */
    TileSetStyle[TileSetStyle["SMART_INTERFACE_SELECTION"] = 76] = "SMART_INTERFACE_SELECTION";
    /**
     * @generated from protobuf enum value: VECTOR_ASSETS = 77;
     */
    TileSetStyle[TileSetStyle["VECTOR_ASSETS"] = 77] = "VECTOR_ASSETS";
    /**
     * @generated from protobuf enum value: SPR_ASSET_METADATA = 78;
     */
    TileSetStyle[TileSetStyle["SPR_ASSET_METADATA"] = 78] = "SPR_ASSET_METADATA";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_POLAR = 79;
     */
    TileSetStyle[TileSetStyle["VECTOR_SPR_POLAR"] = 79] = "VECTOR_SPR_POLAR";
    /**
     * @generated from protobuf enum value: SMART_DATA_MODE = 80;
     */
    TileSetStyle[TileSetStyle["SMART_DATA_MODE"] = 80] = "SMART_DATA_MODE";
    /**
     * @generated from protobuf enum value: CELLULAR_PERFORMANCE_SCORE = 81;
     */
    TileSetStyle[TileSetStyle["CELLULAR_PERFORMANCE_SCORE"] = 81] = "CELLULAR_PERFORMANCE_SCORE";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_MODELS_OCCLUSION = 82;
     */
    TileSetStyle[TileSetStyle["VECTOR_SPR_MODELS_OCCLUSION"] = 82] = "VECTOR_SPR_MODELS_OCCLUSION";
    /**
     * @generated from protobuf enum value: VECTOR_TOPOGRAPHIC = 83;
     */
    TileSetStyle[TileSetStyle["VECTOR_TOPOGRAPHIC"] = 83] = "VECTOR_TOPOGRAPHIC";
    /**
     * @generated from protobuf enum value: VECTOR_POI_V2_UPDATE = 84;
     */
    TileSetStyle[TileSetStyle["VECTOR_POI_V2_UPDATE"] = 84] = "VECTOR_POI_V2_UPDATE";
    /**
     * @generated from protobuf enum value: VECTOR_LIVE_DATA_UPDATES = 85;
     */
    TileSetStyle[TileSetStyle["VECTOR_LIVE_DATA_UPDATES"] = 85] = "VECTOR_LIVE_DATA_UPDATES";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_V2 = 86;
     */
    TileSetStyle[TileSetStyle["VECTOR_TRAFFIC_V2"] = 86] = "VECTOR_TRAFFIC_V2";
    /**
     * @generated from protobuf enum value: VECTOR_ROAD_SELECTION = 87;
     */
    TileSetStyle[TileSetStyle["VECTOR_ROAD_SELECTION"] = 87] = "VECTOR_ROAD_SELECTION";
    /**
     * @generated from protobuf enum value: VECTOR_REGION_METADATA = 88;
     */
    TileSetStyle[TileSetStyle["VECTOR_REGION_METADATA"] = 88] = "VECTOR_REGION_METADATA";
    /**
     * @generated from protobuf enum value: RAY_TRACING = 89;
     */
    TileSetStyle[TileSetStyle["RAY_TRACING"] = 89] = "RAY_TRACING";
    /**
     * @generated from protobuf enum value: VECTOR_CONTOURS = 90;
     */
    TileSetStyle[TileSetStyle["VECTOR_CONTOURS"] = 90] = "VECTOR_CONTOURS";
    /**
     * @generated from protobuf enum value: UNUSED_91 = 91;
     */
    TileSetStyle[TileSetStyle["UNUSED_91"] = 91] = "UNUSED_91";
    /**
     * @generated from protobuf enum value: UNUSED_92 = 92;
     */
    TileSetStyle[TileSetStyle["UNUSED_92"] = 92] = "UNUSED_92";
    /**
     * @generated from protobuf enum value: UNUSED_93 = 93;
     */
    TileSetStyle[TileSetStyle["UNUSED_93"] = 93] = "UNUSED_93";
    /**
     * @generated from protobuf enum value: UNUSED_94 = 94;
     */
    TileSetStyle[TileSetStyle["UNUSED_94"] = 94] = "UNUSED_94";
    /**
     * @generated from protobuf enum value: UNUSED_95 = 95;
     */
    TileSetStyle[TileSetStyle["UNUSED_95"] = 95] = "UNUSED_95";
    /**
     * @generated from protobuf enum value: UNUSED_96 = 96;
     */
    TileSetStyle[TileSetStyle["UNUSED_96"] = 96] = "UNUSED_96";
    /**
     * @generated from protobuf enum value: UNUSED_97 = 97;
     */
    TileSetStyle[TileSetStyle["UNUSED_97"] = 97] = "UNUSED_97";
    /**
     * @generated from protobuf enum value: UNUSED_98 = 98;
     */
    TileSetStyle[TileSetStyle["UNUSED_98"] = 98] = "UNUSED_98";
    /**
     * @generated from protobuf enum value: UNUSED_99 = 99;
     */
    TileSetStyle[TileSetStyle["UNUSED_99"] = 99] = "UNUSED_99";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_MERCATOR = 58;
     */
    TileSetStyle[TileSetStyle["DAVINCI_DEV1"] = 58] = "DAVINCI_DEV1";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_MODELS = 59;
     */
    TileSetStyle[TileSetStyle["DAVINCI_DEV2"] = 59] = "DAVINCI_DEV2";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_MATERIALS = 60;
     */
    TileSetStyle[TileSetStyle["DAVINCI_DEV3"] = 60] = "DAVINCI_DEV3";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_METADATA = 61;
     */
    TileSetStyle[TileSetStyle["DAVINCI_DEV4"] = 61] = "DAVINCI_DEV4";
    /**
     * @generated from protobuf enum value: VECTOR_RESERVED_2 = 63;
     */
    TileSetStyle[TileSetStyle["DAVINCI_DEV6"] = 63] = "DAVINCI_DEV6";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_ROADS = 66;
     */
    TileSetStyle[TileSetStyle["DAVINCI_DEV7"] = 66] = "DAVINCI_DEV7";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_STANDARD = 67;
     */
    TileSetStyle[TileSetStyle["DAVINCI_DEV8"] = 67] = "DAVINCI_DEV8";
    /**
     * @generated from protobuf enum value: VECTOR_POI_V2 = 68;
     */
    TileSetStyle[TileSetStyle["DAVINCI_DEV9"] = 68] = "DAVINCI_DEV9";
    /**
     * @generated from protobuf enum value: VECTOR_BUILDINGS_V2 = 73;
     */
    TileSetStyle[TileSetStyle["DAVINCI_BUILDINGS"] = 73] = "DAVINCI_BUILDINGS";
    /**
     * @generated from protobuf enum value: VECTOR_TRACKS = 62;
     */
    TileSetStyle[TileSetStyle["VECTOR_RESERVED_1"] = 62] = "VECTOR_RESERVED_1";
})(TileSetStyle || (TileSetStyle = {}));
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.TileScale
 */
export var TileScale;
(function (TileScale) {
    /**
     * @generated from protobuf enum value: NODPI = 0;
     */
    TileScale[TileScale["NODPI"] = 0] = "NODPI";
    /**
     * @generated from protobuf enum value: LODPI = 1;
     */
    TileScale[TileScale["LODPI"] = 1] = "LODPI";
    /**
     * @generated from protobuf enum value: HIDPI = 2;
     */
    TileScale[TileScale["HIDPI"] = 2] = "HIDPI";
})(TileScale || (TileScale = {}));
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.TileSize
 */
export var TileSize;
(function (TileSize) {
    /**
     * @generated from protobuf enum value: PX128 = 0;
     */
    TileSize[TileSize["PX128"] = 0] = "PX128";
    /**
     * @generated from protobuf enum value: PX256 = 1;
     */
    TileSize[TileSize["PX256"] = 1] = "PX256";
    /**
     * @generated from protobuf enum value: PX512 = 2;
     */
    TileSize[TileSize["PX512"] = 2] = "PX512";
})(TileSize || (TileSize = {}));
/**
 * @generated from protobuf enum com.apple.geo.protobuf.geo.GenericTileType
 */
export var GenericTileType;
(function (GenericTileType) {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    GenericTileType[GenericTileType["UNKNOWN"] = 0] = "UNKNOWN";
    /**
     * @generated from protobuf enum value: WATER = 1;
     */
    GenericTileType[GenericTileType["WATER"] = 1] = "WATER";
    /**
     * @generated from protobuf enum value: NO_TILE = 2;
     */
    GenericTileType[GenericTileType["NO_TILE"] = 2] = "NO_TILE";
})(GenericTileType || (GenericTileType = {}));
// @generated message type with reflection information, may provide speed optimized methods
class RegionalResource$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.RegionalResource", [
            { no: 1, name: "x", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "y", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "z", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "icon", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "attribution", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Attribution },
            { no: 7, name: "iconChecksum", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 29, name: "tileRange", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSetRegion },
            { no: 30, name: "validSubManifestVersion", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.RegionalResource
 */
export const RegionalResource = new RegionalResource$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegionalResourceIndex$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.RegionalResourceIndex", []);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.RegionalResourceIndex
 */
export const RegionalResourceIndex = new RegionalResourceIndex$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegionalResourceTile$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.RegionalResourceTile", []);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.RegionalResourceTile
 */
export const RegionalResourceTile = new RegionalResourceTile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegionalResourceRegion$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.RegionalResourceRegion", []);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.RegionalResourceRegion
 */
export const RegionalResourceRegion = new RegionalResourceRegion$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TileGroup$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.TileGroup", [
            { no: 1, name: "identifier", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "tileSet", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileGroup_VersionedTileSet },
            { no: 3, name: "styleSheetIndex", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "textureIndex", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "fontIndex", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 13 /*ScalarType.UINT32*/ },
            { no: 6, name: "iconIndex", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 13 /*ScalarType.UINT32*/ },
            { no: 7, name: "regionalResourceIndex", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => RegionalResourceIndex },
            { no: 8, name: "xmlIndex", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "attributionIndex", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 13 /*ScalarType.UINT32*/ },
            { no: 11, name: "hybridUnavailableRegion", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSetRegion },
            { no: 12, name: "resourceIndex", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 13 /*ScalarType.UINT32*/ },
            { no: 14, name: "muninVersion", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 15, name: "offlineMetadataIndex", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.TileGroup
 */
export const TileGroup = new TileGroup$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TileGroup_VersionedTileSet$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.TileGroup.VersionedTileSet", [
            { no: 1, name: "tileSetIndex", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "identifier", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.TileGroup.VersionedTileSet
 */
export const TileGroup_VersionedTileSet = new TileGroup_VersionedTileSet$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GenericTile$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.GenericTile", [
            { no: 1, name: "tileType", kind: "enum", T: () => ["com.apple.geo.protobuf.geo.GenericTileType", GenericTileType] },
            { no: 2, name: "textureIndex", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "resourceIndex", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.GenericTile
 */
export const GenericTile = new GenericTile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TileSetRegion$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.TileSetRegion", [
            { no: 1, name: "minX", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "minY", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "maxX", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "maxY", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "minZ", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 6, name: "maxZ", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.TileSetRegion
 */
export const TileSetRegion = new TileSetRegion$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TileSetVersion$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.TileSetVersion", [
            { no: 1, name: "identifier", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "availableTiles", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSetRegion },
            { no: 3, name: "timeToLiveSeconds", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "genericTile", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => GenericTile },
            { no: 5, name: "supportedLanguagesVersion", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.TileSetVersion
 */
export const TileSetVersion = new TileSetVersion$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TileSet$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.TileSet", [
            { no: 1, name: "baseURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "multiTileURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "style", kind: "enum", T: () => ["com.apple.geo.protobuf.geo.TileSetStyle", TileSetStyle] },
            { no: 5, name: "validVersion", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSetVersion },
            { no: 6, name: "scale", kind: "enum", T: () => ["com.apple.geo.protobuf.geo.TileScale", TileScale] },
            { no: 7, name: "size", kind: "enum", T: () => ["com.apple.geo.protobuf.geo.TileSize", TileSize] },
            { no: 9, name: "localizationURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "supportedLanguage", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSet_Language },
            { no: 11, name: "multiTileURLUsesStatusCodes", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 12, name: "updateBehavior", kind: "enum", opt: true, T: () => ["com.apple.geo.protobuf.geo.TileSet.TileSetVersionUpdateBehavior", TileSet_TileSetVersionUpdateBehavior] },
            { no: 13, name: "countryRegionWhitelist", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSet_CountryRegionTuple },
            { no: 14, name: "checksumType", kind: "enum", T: () => ["com.apple.geo.protobuf.geo.TileSet.TileSetChecksumType", TileSet_TileSetChecksumType] },
            { no: 15, name: "dataSet", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 16, name: "requestStyle", kind: "enum", T: () => ["com.apple.geo.protobuf.geo.TileSet.TileRequestStyle", TileSet_TileRequestStyle] },
            { no: 17, name: "useAuthProxy", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 18, name: "supportsMultipathTCP", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 19, name: "alternativeMultipathTCPPort", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 20, name: "deviceSKUWhitelist", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.TileSet
 */
export const TileSet = new TileSet$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TileSet_Language$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.TileSet.Language", [
            { no: 1, name: "identifier", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "language", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.TileSet.Language
 */
export const TileSet_Language = new TileSet_Language$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TileSet_CountryRegionTuple$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.TileSet.CountryRegionTuple", [
            { no: 1, name: "countryCode", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "region", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.TileSet.CountryRegionTuple
 */
export const TileSet_CountryRegionTuple = new TileSet_CountryRegionTuple$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ResourceFilter$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.ResourceFilter", [
            { no: 1, name: "scale", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["com.apple.geo.protobuf.geo.ResourceFilter.Scale", ResourceFilter_Scale] },
            { no: 2, name: "scenario", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["com.apple.geo.protobuf.geo.ResourceFilter.Scenario", ResourceFilter_Scenario] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.ResourceFilter
 */
export const ResourceFilter = new ResourceFilter$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Resource$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.Resource", [
            { no: 1, name: "resourceType", kind: "enum", T: () => ["com.apple.geo.protobuf.geo.Resource.ResourceType", Resource_ResourceType, "RESOURCE_TYPE_"] },
            { no: 2, name: "filename", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "checksum", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 4, name: "region", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSetRegion },
            { no: 5, name: "filter", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ResourceFilter },
            { no: 6, name: "connectionType", kind: "enum", opt: true, T: () => ["com.apple.geo.protobuf.geo.Resource.ConnectionType", Resource_ConnectionType] },
            { no: 7, name: "preferWiFiAllowedStaleThreshold", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 8, name: "validationMethod", kind: "enum", T: () => ["com.apple.geo.protobuf.geo.Resource.ValidationMethod", Resource_ValidationMethod] },
            { no: 9, name: "alternateResourceURLIndex", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "updateMethod", kind: "enum", T: () => ["com.apple.geo.protobuf.geo.Resource.UpdateMethod", Resource_UpdateMethod] },
            { no: 11, name: "timeToLiveSeconds", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.Resource
 */
export const Resource = new Resource$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Attribution$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.Attribution", [
            { no: 1, name: "badge", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "logo", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "badgeChecksum", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "logoChecksum", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "resource", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Resource },
            { no: 8, name: "region", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSetRegion },
            { no: 9, name: "dataSet", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "linkDisplayStringIndex", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 11, name: "plainTextURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 12, name: "plainTextURLSHA256Checksum", kind: "scalar", opt: true, T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.Attribution
 */
export const Attribution = new Attribution$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ServiceVersion$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.ServiceVersion", [
            { no: 1, name: "versionDomain", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "minimumVersion", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.ServiceVersion
 */
export const ServiceVersion = new ServiceVersion$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VersionManifest$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.VersionManifest", [
            { no: 1, name: "serviceVersion", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ServiceVersion }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.VersionManifest
 */
export const VersionManifest = new VersionManifest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DataSetDescription$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.DataSetDescription", [
            { no: 1, name: "identifier", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "dataSetDescription", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.DataSetDescription
 */
export const DataSetDescription = new DataSetDescription$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DataSetURLOverride$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.DataSetURLOverride", []);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.DataSetURLOverride
 */
export const DataSetURLOverride = new DataSetURLOverride$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MuninVersion$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.MuninVersion", []);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.MuninVersion
 */
export const MuninVersion = new MuninVersion$Type();
// @generated message type with reflection information, may provide speed optimized methods
class URLInfo$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.URLInfo", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "useAuthProxy", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "supportsMultipathTCP", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "alternativeMultipathTCPPort", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.URLInfo
 */
export const URLInfo = new URLInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class URLInfoSet$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.URLInfoSet", [
            { no: 1, name: "dataSet", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "resourcesURL", kind: "message", T: () => URLInfo },
            { no: 3, name: "searchAttributionManifestURL", kind: "message", T: () => URLInfo },
            { no: 4, name: "directionsURL", kind: "message", T: () => URLInfo },
            { no: 5, name: "etaURL", kind: "message", T: () => URLInfo },
            { no: 6, name: "batchReverseGeocoderURL", kind: "message", T: () => URLInfo },
            { no: 7, name: "simpleETAURL", kind: "message", T: () => URLInfo },
            { no: 8, name: "addressCorrectionInitURL", kind: "message", T: () => URLInfo },
            { no: 9, name: "addressCorrectionUpdateURL", kind: "message", T: () => URLInfo },
            { no: 10, name: "polyLocationShiftURL", kind: "message", T: () => URLInfo },
            { no: 11, name: "problemSubmissionURL", kind: "message", T: () => URLInfo },
            { no: 12, name: "problemStatusURL", kind: "message", T: () => URLInfo },
            { no: 13, name: "reverseGeocoderVersionsURL", kind: "message", T: () => URLInfo },
            { no: 14, name: "problemCategoriesURL", kind: "message", T: () => URLInfo },
            { no: 15, name: "announcementsURL", kind: "message", T: () => URLInfo },
            { no: 16, name: "dispatcherURL", kind: "message", T: () => URLInfo },
            { no: 17, name: "problemOptInURL", kind: "message", T: () => URLInfo },
            { no: 18, name: "abExperimentURL", kind: "message", T: () => URLInfo },
            { no: 19, name: "businessPortalBaseURL", kind: "message", T: () => URLInfo },
            { no: 20, name: "logMessageUsageURL", kind: "message", T: () => URLInfo },
            { no: 21, name: "spatialLookupURL", kind: "message", T: () => URLInfo },
            { no: 22, name: "realtimeTrafficProbeURL", kind: "message", T: () => URLInfo },
            { no: 23, name: "batchTrafficProbeURL", kind: "message", T: () => URLInfo },
            { no: 24, name: "proactiveRoutingURL", kind: "message", T: () => URLInfo },
            { no: 25, name: "logMessageUsageV3URL", kind: "message", T: () => URLInfo },
            { no: 26, name: "backgroundDispatcherURL", kind: "message", T: () => URLInfo },
            { no: 27, name: "bluePOIDispatcherURL", kind: "message", T: () => URLInfo },
            { no: 28, name: "backgroundRevGeoURL", kind: "message", T: () => URLInfo },
            { no: 29, name: "wifiConnectionQualityProbeURL", kind: "message", T: () => URLInfo },
            { no: 30, name: "muninBaseURL", kind: "message", T: () => URLInfo },
            { no: 31, name: "authProxyURL", kind: "message", T: () => URLInfo },
            { no: 32, name: "wifiQualityURL", kind: "message", T: () => URLInfo },
            { no: 33, name: "feedbackSubmissionURL", kind: "message", T: () => URLInfo },
            { no: 34, name: "feedbackLookupURL", kind: "message", T: () => URLInfo },
            { no: 35, name: "junctionImageServiceURL", kind: "message", T: () => URLInfo },
            { no: 36, name: "analyticsCohortSessionURL", kind: "message", T: () => URLInfo },
            { no: 37, name: "analyticsLongSessionURL", kind: "message", T: () => URLInfo },
            { no: 38, name: "analyticsShortSessionURL", kind: "message", T: () => URLInfo },
            { no: 39, name: "analyticsSessionlessURL", kind: "message", T: () => URLInfo },
            { no: 40, name: "webModuleBaseURL", kind: "message", T: () => URLInfo },
            { no: 41, name: "wifiQualityTileURL", kind: "message", T: () => URLInfo },
            { no: 42, name: "alternateResourcesURL", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => URLInfo },
            { no: 43, name: "tokenAuthenticationURL", kind: "message", T: () => URLInfo },
            { no: 44, name: "authenticatedClientFeatureFlagURL", kind: "message", T: () => URLInfo },
            { no: 45, name: "addressCorrectionTaggedLocationURL", kind: "message", T: () => URLInfo },
            { no: 46, name: "proactiveAppClipURL", kind: "message", T: () => URLInfo },
            { no: 47, name: "enrichmentSubmissionURL", kind: "message", T: () => URLInfo },
            { no: 48, name: "ugcLogDiscardURL", kind: "message", T: () => URLInfo },
            { no: 49, name: "batchReverseGeocoderPlaceRequestURL", kind: "message", T: () => URLInfo },
            { no: 50, name: "pressureProbeDataURL", kind: "message", T: () => URLInfo },
            { no: 51, name: "poiBusynessActivityCollectionURL", kind: "message", T: () => URLInfo },
            { no: 52, name: "rapWebBundleURL", kind: "message", T: () => URLInfo },
            { no: 53, name: "networkSelectionHarvestURL", kind: "message", T: () => URLInfo },
            { no: 54, name: "offlineDataBatchListURL", kind: "message", T: () => URLInfo },
            { no: 55, name: "offlineDataSizeURL", kind: "message", T: () => URLInfo },
            { no: 56, name: "offlineDataDownloadBaseURL", kind: "message", T: () => URLInfo },
            { no: 57, name: "bcxDispatcherURL", kind: "message", T: () => URLInfo }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.URLInfoSet
 */
export const URLInfoSet = new URLInfoSet$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MuninBucket$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.MuninBucket", [
            { no: 3, name: "bucketID", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "bucketURL", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "lodLevel", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.MuninBucket
 */
export const MuninBucket = new MuninBucket$Type();
// @generated message type with reflection information, may provide speed optimized methods
class DisplayString$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.DisplayString", [
            { no: 1, name: "localizedString", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => LocalizedString }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.DisplayString
 */
export const DisplayString = new DisplayString$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalizedString$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.LocalizedString", [
            { no: 1, name: "locale", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "stringValue", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.LocalizedString
 */
export const LocalizedString = new LocalizedString$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MapRegion$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.MapRegion", []);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.MapRegion
 */
export const MapRegion = new MapRegion$Type();
// @generated message type with reflection information, may provide speed optimized methods
class OfflineMetadata$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.OfflineMetadata", [
            { no: 1, name: "dataVersion", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "regulatoryRegionId", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.OfflineMetadata
 */
export const OfflineMetadata = new OfflineMetadata$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Resources$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.Resources", [
            { no: 1, name: "tileGroup", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileGroup },
            { no: 2, name: "tileSet", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSet },
            { no: 3, name: "styleSheet", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "texture", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "font", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "icon", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 8, name: "regionalResource", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => RegionalResource },
            { no: 9, name: "xml", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 11, name: "attribution", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Attribution },
            { no: 30, name: "authToken", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 31, name: "resourcesURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 32, name: "searchURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 33, name: "searchAttributionManifestURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 34, name: "autocompleteURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 35, name: "reverseGeocoderURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 36, name: "forwardGeocoderURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 37, name: "directionsURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 38, name: "etaURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 39, name: "locationShiftURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 40, name: "releaseInfo", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 41, name: "batchReverseGeocoderURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 42, name: "mapMatchURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 43, name: "simpleETAURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 44, name: "styleSheetChecksum", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 45, name: "textureChecksum", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 46, name: "fontChecksum", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 47, name: "iconChecksum", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 48, name: "xmlChecksum", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 49, name: "addressCorrectionInitURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 50, name: "addressCorrectionUpdateURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 51, name: "polyLocationShiftURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 52, name: "problemSubmissionURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 53, name: "problemStatusURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 54, name: "reverseGeocoderVersionsURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 55, name: "problemCategoriesURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 56, name: "usageURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 58, name: "businessCallerIDURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 59, name: "problemNotificationAvailabilityURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 61, name: "announcementsURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 62, name: "announcementsSupportedLanguage", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 63, name: "businessNameResolutionURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 64, name: "dispatcherURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 65, name: "problemOptInURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 66, name: "versionManifest", kind: "message", T: () => VersionManifest },
            { no: 67, name: "abExperimentURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 68, name: "businessPortalBaseURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 69, name: "logMessageUsageURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 70, name: "locationShiftEnabledRegion", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MapRegion },
            { no: 71, name: "locationShiftVersion", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 72, name: "resource", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Resource },
            { no: 73, name: "spatialLookupURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 74, name: "dataSet", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => DataSetDescription },
            { no: 75, name: "dataSetURLOverride", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => DataSetURLOverride },
            { no: 77, name: "realtimeTrafficProbeURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 78, name: "batchTrafficProbeURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 79, name: "proactiveRoutingURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 80, name: "logMessageUsageV3URL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 81, name: "backgroundDispatcherURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 82, name: "bluePOIDispatcherURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 83, name: "backgroundRevGeoURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 85, name: "wifiConnectionQualityProbeURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 88, name: "muninBaseURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 89, name: "muninVersion", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MuninVersion },
            { no: 91, name: "authProxyURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 92, name: "urlInfoSet", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => URLInfoSet },
            { no: 93, name: "muninBucket", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MuninBucket },
            { no: 94, name: "displayString", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => DisplayString },
            { no: 95, name: "offlineMetadata", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => OfflineMetadata }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.Resources
 */
export const Resources = new Resources$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ResourceManifestDownload$Type extends MessageType {
    constructor() {
        super("com.apple.geo.protobuf.geo.ResourceManifestDownload", [
            { no: 1, name: "resources", kind: "message", T: () => Resources }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message com.apple.geo.protobuf.geo.ResourceManifestDownload
 */
export const ResourceManifestDownload = new ResourceManifestDownload$Type();
