// @generated by protobuf-ts 2.9.3 with parameter use_proto_field_name,output_javascript,optimize_code_size
// @generated from protobuf file "Resources.proto" (syntax proto3)
// tslint:disable
// @generated by protobuf-ts 2.9.3 with parameter use_proto_field_name,output_javascript,optimize_code_size
// @generated from protobuf file "Resources.proto" (syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf enum TileSet.Style
 */
export var TileSet_Style;
(function (TileSet_Style) {
    /**
     * @generated from protobuf enum value: RASTER_STANDARD = 0;
     */
    TileSet_Style[TileSet_Style["RASTER_STANDARD"] = 0] = "RASTER_STANDARD";
    /**
     * @generated from protobuf enum value: VECTOR_STANDARD = 1;
     */
    TileSet_Style[TileSet_Style["VECTOR_STANDARD"] = 1] = "VECTOR_STANDARD";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_SEGMENTS_FOR_RASTER = 2;
     */
    TileSet_Style[TileSet_Style["VECTOR_TRAFFIC_SEGMENTS_FOR_RASTER"] = 2] = "VECTOR_TRAFFIC_SEGMENTS_FOR_RASTER";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_INCIDENTS_FOR_RASTER = 3;
     */
    TileSet_Style[TileSet_Style["VECTOR_TRAFFIC_INCIDENTS_FOR_RASTER"] = 3] = "VECTOR_TRAFFIC_INCIDENTS_FOR_RASTER";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_SEGMENTS_AND_INCIDENTS_FOR_RASTER = 4;
     */
    TileSet_Style[TileSet_Style["VECTOR_TRAFFIC_SEGMENTS_AND_INCIDENTS_FOR_RASTER"] = 4] = "VECTOR_TRAFFIC_SEGMENTS_AND_INCIDENTS_FOR_RASTER";
    /**
     * @generated from protobuf enum value: RASTER_STANDARD_BACKGROUND = 5;
     */
    TileSet_Style[TileSet_Style["RASTER_STANDARD_BACKGROUND"] = 5] = "RASTER_STANDARD_BACKGROUND";
    /**
     * @generated from protobuf enum value: RASTER_HYBRID = 6;
     */
    TileSet_Style[TileSet_Style["RASTER_HYBRID"] = 6] = "RASTER_HYBRID";
    /**
     * @generated from protobuf enum value: RASTER_SATELLITE = 7;
     */
    TileSet_Style[TileSet_Style["RASTER_SATELLITE"] = 7] = "RASTER_SATELLITE";
    /**
     * @generated from protobuf enum value: RASTER_TERRAIN = 8;
     */
    TileSet_Style[TileSet_Style["RASTER_TERRAIN"] = 8] = "RASTER_TERRAIN";
    /**
     * @generated from protobuf enum value: VECTOR_BUILDINGS = 11;
     */
    TileSet_Style[TileSet_Style["VECTOR_BUILDINGS"] = 11] = "VECTOR_BUILDINGS";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC = 12;
     */
    TileSet_Style[TileSet_Style["VECTOR_TRAFFIC"] = 12] = "VECTOR_TRAFFIC";
    /**
     * @generated from protobuf enum value: VECTOR_POI = 13;
     */
    TileSet_Style[TileSet_Style["VECTOR_POI"] = 13] = "VECTOR_POI";
    /**
     * @generated from protobuf enum value: SPUTNIK_METADATA = 14;
     */
    TileSet_Style[TileSet_Style["SPUTNIK_METADATA"] = 14] = "SPUTNIK_METADATA";
    /**
     * @generated from protobuf enum value: SPUTNIK_C3M = 15;
     */
    TileSet_Style[TileSet_Style["SPUTNIK_C3M"] = 15] = "SPUTNIK_C3M";
    /**
     * @generated from protobuf enum value: SPUTNIK_DSM = 16;
     */
    TileSet_Style[TileSet_Style["SPUTNIK_DSM"] = 16] = "SPUTNIK_DSM";
    /**
     * @generated from protobuf enum value: SPUTNIK_DSM_GLOBAL = 17;
     */
    TileSet_Style[TileSet_Style["SPUTNIK_DSM_GLOBAL"] = 17] = "SPUTNIK_DSM_GLOBAL";
    /**
     * @generated from protobuf enum value: VECTOR_REALISTIC = 18;
     */
    TileSet_Style[TileSet_Style["VECTOR_REALISTIC"] = 18] = "VECTOR_REALISTIC";
    /**
     * @generated from protobuf enum value: VECTOR_LEGACY_REALISTIC = 19;
     */
    TileSet_Style[TileSet_Style["VECTOR_LEGACY_REALISTIC"] = 19] = "VECTOR_LEGACY_REALISTIC";
    /**
     * @generated from protobuf enum value: VECTOR_ROADS = 20;
     */
    TileSet_Style[TileSet_Style["VECTOR_ROADS"] = 20] = "VECTOR_ROADS";
    /**
     * @generated from protobuf enum value: RASTER_VEGETATION = 21;
     */
    TileSet_Style[TileSet_Style["RASTER_VEGETATION"] = 21] = "RASTER_VEGETATION";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_SKELETON = 22;
     */
    TileSet_Style[TileSet_Style["VECTOR_TRAFFIC_SKELETON"] = 22] = "VECTOR_TRAFFIC_SKELETON";
    /**
     * @generated from protobuf enum value: RASTER_COASTLINE_MASK = 23;
     */
    TileSet_Style[TileSet_Style["RASTER_COASTLINE_MASK"] = 23] = "RASTER_COASTLINE_MASK";
    /**
     * @generated from protobuf enum value: RASTER_HILLSHADE = 24;
     */
    TileSet_Style[TileSet_Style["RASTER_HILLSHADE"] = 24] = "RASTER_HILLSHADE";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_WITH_GREEN = 25;
     */
    TileSet_Style[TileSet_Style["VECTOR_TRAFFIC_WITH_GREEN"] = 25] = "VECTOR_TRAFFIC_WITH_GREEN";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_STATIC = 26;
     */
    TileSet_Style[TileSet_Style["VECTOR_TRAFFIC_STATIC"] = 26] = "VECTOR_TRAFFIC_STATIC";
    /**
     * @generated from protobuf enum value: RASTER_COASTLINE_DROP_MASK = 27;
     */
    TileSet_Style[TileSet_Style["RASTER_COASTLINE_DROP_MASK"] = 27] = "RASTER_COASTLINE_DROP_MASK";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_SKELETON_WITH_HISTORICAL = 28;
     */
    TileSet_Style[TileSet_Style["VECTOR_TRAFFIC_SKELETON_WITH_HISTORICAL"] = 28] = "VECTOR_TRAFFIC_SKELETON_WITH_HISTORICAL";
    /**
     * @generated from protobuf enum value: VECTOR_SPEED_PROFILES = 29;
     */
    TileSet_Style[TileSet_Style["VECTOR_SPEED_PROFILES"] = 29] = "VECTOR_SPEED_PROFILES";
    /**
     * @generated from protobuf enum value: VECTOR_VENUES = 30;
     */
    TileSet_Style[TileSet_Style["VECTOR_VENUES"] = 30] = "VECTOR_VENUES";
    /**
     * @generated from protobuf enum value: RASTER_DOWN_SAMPLED = 31;
     */
    TileSet_Style[TileSet_Style["RASTER_DOWN_SAMPLED"] = 31] = "RASTER_DOWN_SAMPLED";
    /**
     * @generated from protobuf enum value: RASTER_COLOR_BALANCED = 32;
     */
    TileSet_Style[TileSet_Style["RASTER_COLOR_BALANCED"] = 32] = "RASTER_COLOR_BALANCED";
    /**
     * @generated from protobuf enum value: RASTER_SATELLITE_NIGHT = 33;
     */
    TileSet_Style[TileSet_Style["RASTER_SATELLITE_NIGHT"] = 33] = "RASTER_SATELLITE_NIGHT";
    /**
     * @generated from protobuf enum value: SPUTNIK_VECTOR_BORDER = 34;
     */
    TileSet_Style[TileSet_Style["SPUTNIK_VECTOR_BORDER"] = 34] = "SPUTNIK_VECTOR_BORDER";
    /**
     * @generated from protobuf enum value: RASTER_SATELLITE_DIGITIZE = 35;
     */
    TileSet_Style[TileSet_Style["RASTER_SATELLITE_DIGITIZE"] = 35] = "RASTER_SATELLITE_DIGITIZE";
    /**
     * @generated from protobuf enum value: RASTER_HILLSHADE_PARKS = 36;
     */
    TileSet_Style[TileSet_Style["RASTER_HILLSHADE_PARKS"] = 36] = "RASTER_HILLSHADE_PARKS";
    /**
     * @generated from protobuf enum value: VECTOR_TRANSIT = 37;
     */
    TileSet_Style[TileSet_Style["VECTOR_TRANSIT"] = 37] = "VECTOR_TRANSIT";
    /**
     * @generated from protobuf enum value: RASTER_STANDARD_BASE = 38;
     */
    TileSet_Style[TileSet_Style["RASTER_STANDARD_BASE"] = 38] = "RASTER_STANDARD_BASE";
    /**
     * @generated from protobuf enum value: RASTER_STANDARD_LABELS = 39;
     */
    TileSet_Style[TileSet_Style["RASTER_STANDARD_LABELS"] = 39] = "RASTER_STANDARD_LABELS";
    /**
     * @generated from protobuf enum value: RASTER_HYBRID_ROADS = 40;
     */
    TileSet_Style[TileSet_Style["RASTER_HYBRID_ROADS"] = 40] = "RASTER_HYBRID_ROADS";
    /**
     * @generated from protobuf enum value: RASTER_HYBRID_LABELS = 41;
     */
    TileSet_Style[TileSet_Style["RASTER_HYBRID_LABELS"] = 41] = "RASTER_HYBRID_LABELS";
    /**
     * @generated from protobuf enum value: FLYOVER_C3M_MESH = 42;
     */
    TileSet_Style[TileSet_Style["FLYOVER_C3M_MESH"] = 42] = "FLYOVER_C3M_MESH";
    /**
     * @generated from protobuf enum value: FLYOVER_C3M_JPEG_TEXTURE = 43;
     */
    TileSet_Style[TileSet_Style["FLYOVER_C3M_JPEG_TEXTURE"] = 43] = "FLYOVER_C3M_JPEG_TEXTURE";
    /**
     * @generated from protobuf enum value: FLYOVER_C3M_ASTC_TEXTURE = 44;
     */
    TileSet_Style[TileSet_Style["FLYOVER_C3M_ASTC_TEXTURE"] = 44] = "FLYOVER_C3M_ASTC_TEXTURE";
    /**
     * @generated from protobuf enum value: RASTER_SATELLITE_ASTC = 45;
     */
    TileSet_Style[TileSet_Style["RASTER_SATELLITE_ASTC"] = 45] = "RASTER_SATELLITE_ASTC";
    /**
     * @generated from protobuf enum value: RASTER_HYBRID_ROADS_AND_LABELS = 46;
     */
    TileSet_Style[TileSet_Style["RASTER_HYBRID_ROADS_AND_LABELS"] = 46] = "RASTER_HYBRID_ROADS_AND_LABELS";
    /**
     * @generated from protobuf enum value: VECTOR_TRANSIT_SELECTION = 47;
     */
    TileSet_Style[TileSet_Style["VECTOR_TRANSIT_SELECTION"] = 47] = "VECTOR_TRANSIT_SELECTION";
    /**
     * @generated from protobuf enum value: VECTOR_COVERAGE = 48;
     */
    TileSet_Style[TileSet_Style["VECTOR_COVERAGE"] = 48] = "VECTOR_COVERAGE";
    /**
     * @generated from protobuf enum value: FLYOVER_METADATA = 52;
     */
    TileSet_Style[TileSet_Style["FLYOVER_METADATA"] = 52] = "FLYOVER_METADATA";
    /**
     * @generated from protobuf enum value: VECTOR_ROAD_NETWORK = 53;
     */
    TileSet_Style[TileSet_Style["VECTOR_ROAD_NETWORK"] = 53] = "VECTOR_ROAD_NETWORK";
    /**
     * @generated from protobuf enum value: VECTOR_LAND_COVER = 54;
     */
    TileSet_Style[TileSet_Style["VECTOR_LAND_COVER"] = 54] = "VECTOR_LAND_COVER";
    /**
     * @generated from protobuf enum value: VECTOR_DEBUG = 55;
     */
    TileSet_Style[TileSet_Style["VECTOR_DEBUG"] = 55] = "VECTOR_DEBUG";
    /**
     * @generated from protobuf enum value: VECTOR_STREET_POI = 56;
     */
    TileSet_Style[TileSet_Style["VECTOR_STREET_POI"] = 56] = "VECTOR_STREET_POI";
    /**
     * @generated from protobuf enum value: MUNIN_METADATA = 57;
     */
    TileSet_Style[TileSet_Style["MUNIN_METADATA"] = 57] = "MUNIN_METADATA";
    /**
     * @generated from protobuf enum value: DAVINCI_DEV1 = 58;
     */
    TileSet_Style[TileSet_Style["DAVINCI_DEV1"] = 58] = "DAVINCI_DEV1";
    /**
     * @generated from protobuf enum value: DAVINCI_DEV2 = 59;
     */
    TileSet_Style[TileSet_Style["DAVINCI_DEV2"] = 59] = "DAVINCI_DEV2";
    /**
     * @generated from protobuf enum value: DAVINCI_DEV3 = 60;
     */
    TileSet_Style[TileSet_Style["DAVINCI_DEV3"] = 60] = "DAVINCI_DEV3";
    /**
     * @generated from protobuf enum value: DAVINCI_DEV4 = 61;
     */
    TileSet_Style[TileSet_Style["DAVINCI_DEV4"] = 61] = "DAVINCI_DEV4";
    /**
     * @generated from protobuf enum value: DAVINCI_DEV5 = 62;
     */
    TileSet_Style[TileSet_Style["DAVINCI_DEV5"] = 62] = "DAVINCI_DEV5";
    /**
     * @generated from protobuf enum value: DAVINCI_DEV6 = 63;
     */
    TileSet_Style[TileSet_Style["DAVINCI_DEV6"] = 63] = "DAVINCI_DEV6";
    /**
     * @generated from protobuf enum value: VECTOR_STREET_LANDMARKS = 64;
     */
    TileSet_Style[TileSet_Style["VECTOR_STREET_LANDMARKS"] = 64] = "VECTOR_STREET_LANDMARKS";
    /**
     * @generated from protobuf enum value: COARSE_LOCATION_POLYGONS = 65;
     */
    TileSet_Style[TileSet_Style["COARSE_LOCATION_POLYGONS"] = 65] = "COARSE_LOCATION_POLYGONS";
    /**
     * @generated from protobuf enum value: DAVINCI_DEV7 = 66;
     */
    TileSet_Style[TileSet_Style["DAVINCI_DEV7"] = 66] = "DAVINCI_DEV7";
    /**
     * @generated from protobuf enum value: DAVINCI_DEV8 = 67;
     */
    TileSet_Style[TileSet_Style["DAVINCI_DEV8"] = 67] = "DAVINCI_DEV8";
    /**
     * @generated from protobuf enum value: DAVINCI_DEV9 = 68;
     */
    TileSet_Style[TileSet_Style["DAVINCI_DEV9"] = 68] = "DAVINCI_DEV9";
    /**
     * @generated from protobuf enum value: VECTOR_POLYGON_SELECTION = 69;
     */
    TileSet_Style[TileSet_Style["VECTOR_POLYGON_SELECTION"] = 69] = "VECTOR_POLYGON_SELECTION";
    /**
     * @generated from protobuf enum value: VL_METADATA = 70;
     */
    TileSet_Style[TileSet_Style["VL_METADATA"] = 70] = "VL_METADATA";
    /**
     * @generated from protobuf enum value: VL_DATA = 71;
     */
    TileSet_Style[TileSet_Style["VL_DATA"] = 71] = "VL_DATA";
    /**
     * @generated from protobuf enum value: PROACTIVE_APP_CLIP = 72;
     */
    TileSet_Style[TileSet_Style["PROACTIVE_APP_CLIP"] = 72] = "PROACTIVE_APP_CLIP";
    /**
     * @generated from protobuf enum value: VECTOR_BUILDINGS_V2 = 73;
     */
    TileSet_Style[TileSet_Style["VECTOR_BUILDINGS_V2"] = 73] = "VECTOR_BUILDINGS_V2";
    /**
     * @generated from protobuf enum value: POI_BUSYNESS = 74;
     */
    TileSet_Style[TileSet_Style["POI_BUSYNESS"] = 74] = "POI_BUSYNESS";
    /**
     * @generated from protobuf enum value: POI_DP_BUSYNESS = 75;
     */
    TileSet_Style[TileSet_Style["POI_DP_BUSYNESS"] = 75] = "POI_DP_BUSYNESS";
    /**
     * @generated from protobuf enum value: SMART_INTERFACE_SELECTION = 76;
     */
    TileSet_Style[TileSet_Style["SMART_INTERFACE_SELECTION"] = 76] = "SMART_INTERFACE_SELECTION";
    /**
     * @generated from protobuf enum value: VECTOR_ASSETS = 77;
     */
    TileSet_Style[TileSet_Style["VECTOR_ASSETS"] = 77] = "VECTOR_ASSETS";
    /**
     * @generated from protobuf enum value: SPR_ASSET_METADATA = 78;
     */
    TileSet_Style[TileSet_Style["SPR_ASSET_METADATA"] = 78] = "SPR_ASSET_METADATA";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_POLAR = 79;
     */
    TileSet_Style[TileSet_Style["VECTOR_SPR_POLAR"] = 79] = "VECTOR_SPR_POLAR";
    /**
     * @generated from protobuf enum value: SMART_DATA_MODE = 80;
     */
    TileSet_Style[TileSet_Style["SMART_DATA_MODE"] = 80] = "SMART_DATA_MODE";
    /**
     * @generated from protobuf enum value: CELLULAR_PERFORMANCE_SCORE = 81;
     */
    TileSet_Style[TileSet_Style["CELLULAR_PERFORMANCE_SCORE"] = 81] = "CELLULAR_PERFORMANCE_SCORE";
    /**
     * @generated from protobuf enum value: VECTOR_SPR_MODELS_OCCLUSION = 82;
     */
    TileSet_Style[TileSet_Style["VECTOR_SPR_MODELS_OCCLUSION"] = 82] = "VECTOR_SPR_MODELS_OCCLUSION";
    /**
     * @generated from protobuf enum value: VECTOR_TOPOGRAPHIC = 83;
     */
    TileSet_Style[TileSet_Style["VECTOR_TOPOGRAPHIC"] = 83] = "VECTOR_TOPOGRAPHIC";
    /**
     * @generated from protobuf enum value: VECTOR_POI_V2_UPDATE = 84;
     */
    TileSet_Style[TileSet_Style["VECTOR_POI_V2_UPDATE"] = 84] = "VECTOR_POI_V2_UPDATE";
    /**
     * @generated from protobuf enum value: VECTOR_LIVE_DATA_UPDATES = 85;
     */
    TileSet_Style[TileSet_Style["VECTOR_LIVE_DATA_UPDATES"] = 85] = "VECTOR_LIVE_DATA_UPDATES";
    /**
     * @generated from protobuf enum value: VECTOR_TRAFFIC_V2 = 86;
     */
    TileSet_Style[TileSet_Style["VECTOR_TRAFFIC_V2"] = 86] = "VECTOR_TRAFFIC_V2";
    /**
     * @generated from protobuf enum value: VECTOR_ROAD_SELECTION = 87;
     */
    TileSet_Style[TileSet_Style["VECTOR_ROAD_SELECTION"] = 87] = "VECTOR_ROAD_SELECTION";
    /**
     * @generated from protobuf enum value: VECTOR_REGION_METADATA = 88;
     */
    TileSet_Style[TileSet_Style["VECTOR_REGION_METADATA"] = 88] = "VECTOR_REGION_METADATA";
    /**
     * @generated from protobuf enum value: RAY_TRACING = 89;
     */
    TileSet_Style[TileSet_Style["RAY_TRACING"] = 89] = "RAY_TRACING";
    /**
     * @generated from protobuf enum value: VECTOR_CONTOURS = 90;
     */
    TileSet_Style[TileSet_Style["VECTOR_CONTOURS"] = 90] = "VECTOR_CONTOURS";
    /**
     * @generated from protobuf enum value: UNUSED_91 = 91;
     */
    TileSet_Style[TileSet_Style["UNUSED_91"] = 91] = "UNUSED_91";
    /**
     * @generated from protobuf enum value: UNUSED_92 = 92;
     */
    TileSet_Style[TileSet_Style["UNUSED_92"] = 92] = "UNUSED_92";
    /**
     * @generated from protobuf enum value: UNUSED_93 = 93;
     */
    TileSet_Style[TileSet_Style["UNUSED_93"] = 93] = "UNUSED_93";
    /**
     * @generated from protobuf enum value: UNUSED_94 = 94;
     */
    TileSet_Style[TileSet_Style["UNUSED_94"] = 94] = "UNUSED_94";
    /**
     * @generated from protobuf enum value: UNUSED_95 = 95;
     */
    TileSet_Style[TileSet_Style["UNUSED_95"] = 95] = "UNUSED_95";
    /**
     * @generated from protobuf enum value: UNUSED_96 = 96;
     */
    TileSet_Style[TileSet_Style["UNUSED_96"] = 96] = "UNUSED_96";
    /**
     * @generated from protobuf enum value: UNUSED_97 = 97;
     */
    TileSet_Style[TileSet_Style["UNUSED_97"] = 97] = "UNUSED_97";
    /**
     * @generated from protobuf enum value: UNUSED_98 = 98;
     */
    TileSet_Style[TileSet_Style["UNUSED_98"] = 98] = "UNUSED_98";
    /**
     * @generated from protobuf enum value: UNUSED_99 = 99;
     */
    TileSet_Style[TileSet_Style["UNUSED_99"] = 99] = "UNUSED_99";
})(TileSet_Style || (TileSet_Style = {}));
/**
 * @generated from protobuf enum TileSet.Size
 */
export var TileSet_Size;
(function (TileSet_Size) {
    /**
     * @generated from protobuf enum value: PX128 = 0;
     */
    TileSet_Size[TileSet_Size["PX128"] = 0] = "PX128";
    /**
     * @generated from protobuf enum value: PX256 = 1;
     */
    TileSet_Size[TileSet_Size["PX256"] = 1] = "PX256";
    /**
     * @generated from protobuf enum value: PX512 = 2;
     */
    TileSet_Size[TileSet_Size["PX512"] = 2] = "PX512";
})(TileSet_Size || (TileSet_Size = {}));
/**
 * @generated from protobuf enum TileSet.Scale
 */
export var TileSet_Scale;
(function (TileSet_Scale) {
    /**
     * @generated from protobuf enum value: NODPI = 0;
     */
    TileSet_Scale[TileSet_Scale["NODPI"] = 0] = "NODPI";
    /**
     * @generated from protobuf enum value: LODPI = 1;
     */
    TileSet_Scale[TileSet_Scale["LODPI"] = 1] = "LODPI";
    /**
     * @generated from protobuf enum value: HIDPI = 2;
     */
    TileSet_Scale[TileSet_Scale["HIDPI"] = 2] = "HIDPI";
})(TileSet_Scale || (TileSet_Scale = {}));
/**
 * @generated from protobuf enum TileSet.RequestStyle
 */
export var TileSet_RequestStyle;
(function (TileSet_RequestStyle) {
    /**
     * @generated from protobuf enum value: REQUEST_STYLE_LEGACY = 0;
     */
    TileSet_RequestStyle[TileSet_RequestStyle["LEGACY"] = 0] = "LEGACY";
    /**
     * @generated from protobuf enum value: REQUEST_STYLE_HEADERS_PARAMS_VERSION_BASED_HMAC_AUTH = 1;
     */
    TileSet_RequestStyle[TileSet_RequestStyle["HEADERS_PARAMS_VERSION_BASED_HMAC_AUTH"] = 1] = "HEADERS_PARAMS_VERSION_BASED_HMAC_AUTH";
})(TileSet_RequestStyle || (TileSet_RequestStyle = {}));
/**
 * @generated from protobuf enum TileSet.ChecksumType
 */
export var TileSet_ChecksumType;
(function (TileSet_ChecksumType) {
    /**
     * @generated from protobuf enum value: CHECKSUM_TYPE_NONE = 0;
     */
    TileSet_ChecksumType[TileSet_ChecksumType["NONE"] = 0] = "NONE";
    /**
     * @generated from protobuf enum value: CHECKSUM_TYPE_APPENDED_MD5 = 1;
     */
    TileSet_ChecksumType[TileSet_ChecksumType["APPENDED_MD5"] = 1] = "APPENDED_MD5";
})(TileSet_ChecksumType || (TileSet_ChecksumType = {}));
/**
 * @generated from protobuf enum TileSet.UpdateBehavior
 */
export var TileSet_UpdateBehavior;
(function (TileSet_UpdateBehavior) {
    /**
     * @generated from protobuf enum value: TILE_UPDATE_BEHAVIOR_FLUSH = 0;
     */
    TileSet_UpdateBehavior[TileSet_UpdateBehavior["TILE_UPDATE_BEHAVIOR_FLUSH"] = 0] = "TILE_UPDATE_BEHAVIOR_FLUSH";
    /**
     * @generated from protobuf enum value: TILE_UPDATE_BEHAVIOR_ETAG = 1;
     */
    TileSet_UpdateBehavior[TileSet_UpdateBehavior["TILE_UPDATE_BEHAVIOR_ETAG"] = 1] = "TILE_UPDATE_BEHAVIOR_ETAG";
})(TileSet_UpdateBehavior || (TileSet_UpdateBehavior = {}));
/**
 * @generated from protobuf enum GenericTile.TileType
 */
export var GenericTile_TileType;
(function (GenericTile_TileType) {
    /**
     * @generated from protobuf enum value: UNKNOWN = 0;
     */
    GenericTile_TileType[GenericTile_TileType["UNKNOWN"] = 0] = "UNKNOWN";
    /**
     * @generated from protobuf enum value: WATER = 1;
     */
    GenericTile_TileType[GenericTile_TileType["WATER"] = 1] = "WATER";
    /**
     * @generated from protobuf enum value: NO_TILE = 2;
     */
    GenericTile_TileType[GenericTile_TileType["NO_TILE"] = 2] = "NO_TILE";
})(GenericTile_TileType || (GenericTile_TileType = {}));
/**
 * @generated from protobuf enum Resource.ResourceType
 */
export var Resource_ResourceType;
(function (Resource_ResourceType) {
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_STYLESHEET = 0;
     */
    Resource_ResourceType[Resource_ResourceType["STYLESHEET"] = 0] = "STYLESHEET";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_TEXTURE = 1;
     */
    Resource_ResourceType[Resource_ResourceType["TEXTURE"] = 1] = "TEXTURE";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_FONT = 2;
     */
    Resource_ResourceType[Resource_ResourceType["FONT"] = 2] = "FONT";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_ICON = 3;
     */
    Resource_ResourceType[Resource_ResourceType["ICON"] = 3] = "ICON";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_XML = 4;
     */
    Resource_ResourceType[Resource_ResourceType["XML"] = 4] = "XML";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_ATTRIBUTION_LOGO = 5;
     */
    Resource_ResourceType[Resource_ResourceType["ATTRIBUTION_LOGO"] = 5] = "ATTRIBUTION_LOGO";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_ATTRIBUTION_BADGE = 6;
     */
    Resource_ResourceType[Resource_ResourceType["ATTRIBUTION_BADGE"] = 6] = "ATTRIBUTION_BADGE";
    /**
     * @generated from protobuf enum value: RESOURCE_TYPE_OTHER = 7;
     */
    Resource_ResourceType[Resource_ResourceType["OTHER"] = 7] = "OTHER";
})(Resource_ResourceType || (Resource_ResourceType = {}));
/**
 * @generated from protobuf enum Resource.ConnectionType
 */
export var Resource_ConnectionType;
(function (Resource_ConnectionType) {
    /**
     * @generated from protobuf enum value: RESOURCE_DOWNLOAD_CONNECTION_TYPE_UNKNOWN = 0;
     */
    Resource_ConnectionType[Resource_ConnectionType["RESOURCE_DOWNLOAD_CONNECTION_TYPE_UNKNOWN"] = 0] = "RESOURCE_DOWNLOAD_CONNECTION_TYPE_UNKNOWN";
    /**
     * @generated from protobuf enum value: RESOURCE_DOWNLOAD_CONNECTION_TYPE_CELLULAR = 1;
     */
    Resource_ConnectionType[Resource_ConnectionType["RESOURCE_DOWNLOAD_CONNECTION_TYPE_CELLULAR"] = 1] = "RESOURCE_DOWNLOAD_CONNECTION_TYPE_CELLULAR";
    /**
     * @generated from protobuf enum value: RESOURCE_DOWNLOAD_CONNECTION_TYPE_PREFER_WIFI = 2;
     */
    Resource_ConnectionType[Resource_ConnectionType["RESOURCE_DOWNLOAD_CONNECTION_TYPE_PREFER_WIFI"] = 2] = "RESOURCE_DOWNLOAD_CONNECTION_TYPE_PREFER_WIFI";
    /**
     * @generated from protobuf enum value: RESOURCE_DOWNLOAD_CONNECTION_TYPE_WIFI_ONLY = 3;
     */
    Resource_ConnectionType[Resource_ConnectionType["RESOURCE_DOWNLOAD_CONNECTION_TYPE_WIFI_ONLY"] = 3] = "RESOURCE_DOWNLOAD_CONNECTION_TYPE_WIFI_ONLY";
})(Resource_ConnectionType || (Resource_ConnectionType = {}));
/**
 * @generated from protobuf enum Resource.ValidationMethod
 */
export var Resource_ValidationMethod;
(function (Resource_ValidationMethod) {
    /**
     * @generated from protobuf enum value: SHA1 = 0;
     */
    Resource_ValidationMethod[Resource_ValidationMethod["SHA1"] = 0] = "SHA1";
    /**
     * @generated from protobuf enum value: CMS = 1;
     */
    Resource_ValidationMethod[Resource_ValidationMethod["CMS"] = 1] = "CMS";
})(Resource_ValidationMethod || (Resource_ValidationMethod = {}));
/**
 * @generated from protobuf enum Resource.UpdateMethod
 */
export var Resource_UpdateMethod;
(function (Resource_UpdateMethod) {
    /**
     * @generated from protobuf enum value: VERSIONED = 0;
     */
    Resource_UpdateMethod[Resource_UpdateMethod["VERSIONED"] = 0] = "VERSIONED";
    /**
     * @generated from protobuf enum value: ETAG = 1;
     */
    Resource_UpdateMethod[Resource_UpdateMethod["ETAG"] = 1] = "ETAG";
})(Resource_UpdateMethod || (Resource_UpdateMethod = {}));
/**
 * @generated from protobuf enum ResourceFilter.Scale
 */
export var ResourceFilter_Scale;
(function (ResourceFilter_Scale) {
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCALE_UNKNOWN = 0;
     */
    ResourceFilter_Scale[ResourceFilter_Scale["RESOURCE_FILTER_SCALE_UNKNOWN"] = 0] = "RESOURCE_FILTER_SCALE_UNKNOWN";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCALE_1X = 1;
     */
    ResourceFilter_Scale[ResourceFilter_Scale["RESOURCE_FILTER_SCALE_1X"] = 1] = "RESOURCE_FILTER_SCALE_1X";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCALE_2X = 2;
     */
    ResourceFilter_Scale[ResourceFilter_Scale["RESOURCE_FILTER_SCALE_2X"] = 2] = "RESOURCE_FILTER_SCALE_2X";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCALE_3X = 3;
     */
    ResourceFilter_Scale[ResourceFilter_Scale["RESOURCE_FILTER_SCALE_3X"] = 3] = "RESOURCE_FILTER_SCALE_3X";
})(ResourceFilter_Scale || (ResourceFilter_Scale = {}));
/**
 * @generated from protobuf enum ResourceFilter.Scenario
 */
export var ResourceFilter_Scenario;
(function (ResourceFilter_Scenario) {
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_UNKNOWN = 0;
     */
    ResourceFilter_Scenario[ResourceFilter_Scenario["RESOURCE_FILTER_SCENARIO_UNKNOWN"] = 0] = "RESOURCE_FILTER_SCENARIO_UNKNOWN";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_CARPLAY = 1;
     */
    ResourceFilter_Scenario[ResourceFilter_Scenario["RESOURCE_FILTER_SCENARIO_CARPLAY"] = 1] = "RESOURCE_FILTER_SCENARIO_CARPLAY";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_NAVIGATION = 2;
     */
    ResourceFilter_Scenario[ResourceFilter_Scenario["RESOURCE_FILTER_SCENARIO_NAVIGATION"] = 2] = "RESOURCE_FILTER_SCENARIO_NAVIGATION";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_HIGHVISIBILITY = 3;
     */
    ResourceFilter_Scenario[ResourceFilter_Scenario["RESOURCE_FILTER_SCENARIO_HIGHVISIBILITY"] = 3] = "RESOURCE_FILTER_SCENARIO_HIGHVISIBILITY";
    /**
     * @generated from protobuf enum value: RESOURCE_FILTER_SCENARIO_EXPLICIT = 4;
     */
    ResourceFilter_Scenario[ResourceFilter_Scenario["RESOURCE_FILTER_SCENARIO_EXPLICIT"] = 4] = "RESOURCE_FILTER_SCENARIO_EXPLICIT";
})(ResourceFilter_Scenario || (ResourceFilter_Scenario = {}));
// @generated message type with reflection information, may provide speed optimized methods
class ResourceManifestDownload$Type extends MessageType {
    constructor() {
        super("ResourceManifestDownload", [
            { no: 1, name: "resources", kind: "message", T: () => Resources }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ResourceManifestDownload
 */
export const ResourceManifestDownload = new ResourceManifestDownload$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Resources$Type extends MessageType {
    constructor() {
        super("Resources", [
            { no: 2, name: "tileSet", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSet },
            { no: 3, name: "styleSheet", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "texture", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "font", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "icon", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "xml", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 30, name: "authToken", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 31, name: "resourcesURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 32, name: "searchURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 33, name: "searchAttributionManifestURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 34, name: "autocompleteURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 35, name: "reverseGeocoderURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 36, name: "forwardGeocoderURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 37, name: "directionsURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 38, name: "etaURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 39, name: "locationShiftURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 40, name: "releaseInfo", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 41, name: "batchReverseGeocoderURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 42, name: "mapMatchURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 43, name: "simpleETAURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 44, name: "styleSheetChecksum", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 45, name: "textureChecksum", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 46, name: "fontChecksum", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 47, name: "iconChecksum", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 48, name: "xmlChecksum", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 49, name: "addressCorrectionInitURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 50, name: "addressCorrectionUpdateURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 51, name: "polyLocationShiftURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 52, name: "problemSubmissionURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 53, name: "problemStatusURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 54, name: "reverseGeocoderVersionsURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 55, name: "problemCategoriesURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 56, name: "usageURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 58, name: "businessCallerIDURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 59, name: "problemNotificationAvailabilityURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 61, name: "announcementsURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 62, name: "announcementsSupportedLanguage", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 63, name: "businessNameResolutionURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 64, name: "dispatcherURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 65, name: "problemOptInURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 66, name: "versionManifest", kind: "message", T: () => VersionManifest },
            { no: 67, name: "abExperimentURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 68, name: "businessPortalBaseURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 69, name: "logMessageUsageURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 71, name: "locationShiftVersion", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 72, name: "resource", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Resource },
            { no: 73, name: "spatialLookupURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 77, name: "realtimeTrafficProbeURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 78, name: "batchTrafficProbeURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 79, name: "proactiveRoutingURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 80, name: "logMessageUsageV3URL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 81, name: "backgroundDispatcherURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 82, name: "bluePOIDispatcherURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 83, name: "backgroundRevGeoURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 85, name: "wifiConnectionQualityProbeURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 88, name: "muninBaseURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 91, name: "authProxyURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 92, name: "urlInfoSet", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => URLInfoSet },
            { no: 93, name: "muninBucket", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => MuninBucket }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Resources
 */
export const Resources = new Resources$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TileSet$Type extends MessageType {
    constructor() {
        super("TileSet", [
            { no: 1, name: "baseURL", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "multiTileURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "style", kind: "enum", T: () => ["TileSet.Style", TileSet_Style] },
            { no: 5, name: "validVersion", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSetVersion },
            { no: 6, name: "scale", kind: "enum", T: () => ["TileSet.Scale", TileSet_Scale] },
            { no: 7, name: "size", kind: "enum", T: () => ["TileSet.Size", TileSet_Size] },
            { no: 9, name: "localizationURL", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "supportedLanguage", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Language },
            { no: 11, name: "multiTileURLUsesStatusCodes", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 12, name: "updateBehavior", kind: "enum", opt: true, T: () => ["TileSet.UpdateBehavior", TileSet_UpdateBehavior] },
            { no: 13, name: "countryRegionWhitelist", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => CountryRegionTuple },
            { no: 14, name: "checksumType", kind: "enum", T: () => ["TileSet.ChecksumType", TileSet_ChecksumType, "CHECKSUM_TYPE_"] },
            { no: 15, name: "dataSet", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 16, name: "requestStyle", kind: "enum", T: () => ["TileSet.RequestStyle", TileSet_RequestStyle, "REQUEST_STYLE_"] },
            { no: 17, name: "useAuthProxy", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 18, name: "supportsMultipathTCP", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 19, name: "alternativeMultipathTCPPort", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ },
            { no: 20, name: "deviceSKUWhitelist", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message TileSet
 */
export const TileSet = new TileSet$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TileSetRegion$Type extends MessageType {
    constructor() {
        super("TileSetRegion", [
            { no: 1, name: "minX", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "minY", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "maxX", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "maxY", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "minZ", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 6, name: "maxZ", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message TileSetRegion
 */
export const TileSetRegion = new TileSetRegion$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GenericTile$Type extends MessageType {
    constructor() {
        super("GenericTile", [
            { no: 1, name: "tileType", kind: "enum", T: () => ["GenericTile.TileType", GenericTile_TileType] },
            { no: 2, name: "textureIndex", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 3, name: "resourceIndex", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message GenericTile
 */
export const GenericTile = new GenericTile$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TileSetVersion$Type extends MessageType {
    constructor() {
        super("TileSetVersion", [
            { no: 1, name: "identifier", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "availableTile", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSetRegion },
            { no: 3, name: "timeToLiveSeconds", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "genericTile", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => GenericTile },
            { no: 5, name: "supportedLanguagesVersion", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message TileSetVersion
 */
export const TileSetVersion = new TileSetVersion$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Language$Type extends MessageType {
    constructor() {
        super("Language", [
            { no: 1, name: "identifier", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "language", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Language
 */
export const Language = new Language$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CountryRegionTuple$Type extends MessageType {
    constructor() {
        super("CountryRegionTuple", [
            { no: 1, name: "countryCode", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "region", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message CountryRegionTuple
 */
export const CountryRegionTuple = new CountryRegionTuple$Type();
// @generated message type with reflection information, may provide speed optimized methods
class VersionManifest$Type extends MessageType {
    constructor() {
        super("VersionManifest", [
            { no: 1, name: "serviceVersion", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ServiceVersion }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message VersionManifest
 */
export const VersionManifest = new VersionManifest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ServiceVersion$Type extends MessageType {
    constructor() {
        super("ServiceVersion", [
            { no: 1, name: "versionDomain", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "minimumVersion", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ServiceVersion
 */
export const ServiceVersion = new ServiceVersion$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Resource$Type extends MessageType {
    constructor() {
        super("Resource", [
            { no: 1, name: "resourceType", kind: "enum", T: () => ["Resource.ResourceType", Resource_ResourceType, "RESOURCE_TYPE_"] },
            { no: 2, name: "filename", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "checksum", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 4, name: "region", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TileSetRegion },
            { no: 5, name: "filter", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ResourceFilter },
            { no: 6, name: "connectionType", kind: "enum", T: () => ["Resource.ConnectionType", Resource_ConnectionType] },
            { no: 7, name: "preferWiFiAllowedStaleThreshold", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 8, name: "validationMethod", kind: "enum", T: () => ["Resource.ValidationMethod", Resource_ValidationMethod] },
            { no: 9, name: "alternateResourceURLIndex", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 10, name: "updateMethod", kind: "enum", T: () => ["Resource.UpdateMethod", Resource_UpdateMethod] },
            { no: 11, name: "timeToLiveSeconds", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message Resource
 */
export const Resource = new Resource$Type();
// @generated message type with reflection information, may provide speed optimized methods
class URLInfoSet$Type extends MessageType {
    constructor() {
        super("URLInfoSet", [
            { no: 1, name: "dataSet", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 2, name: "resourcesURL", kind: "message", T: () => URLInfo },
            { no: 3, name: "searchAttributionManifestURL", kind: "message", T: () => URLInfo },
            { no: 4, name: "directionsURL", kind: "message", T: () => URLInfo },
            { no: 5, name: "etaURL", kind: "message", T: () => URLInfo },
            { no: 6, name: "batchReverseGeocoderURL", kind: "message", T: () => URLInfo },
            { no: 7, name: "simpleETAURL", kind: "message", T: () => URLInfo },
            { no: 8, name: "addressCorrectionInitURL", kind: "message", T: () => URLInfo },
            { no: 9, name: "addressCorrectionUpdateURL", kind: "message", T: () => URLInfo },
            { no: 10, name: "polyLocationShiftURL", kind: "message", T: () => URLInfo },
            { no: 11, name: "problemSubmissionURL", kind: "message", T: () => URLInfo },
            { no: 12, name: "problemStatusURL", kind: "message", T: () => URLInfo },
            { no: 13, name: "reverseGeocoderVersionsURL", kind: "message", T: () => URLInfo },
            { no: 14, name: "problemCategoriesURL", kind: "message", T: () => URLInfo },
            { no: 15, name: "announcementsURL", kind: "message", T: () => URLInfo },
            { no: 16, name: "dispatcherURL", kind: "message", T: () => URLInfo },
            { no: 17, name: "problemOptInURL", kind: "message", T: () => URLInfo },
            { no: 18, name: "abExperimentURL", kind: "message", T: () => URLInfo },
            { no: 19, name: "businessPortalBaseURL", kind: "message", T: () => URLInfo },
            { no: 20, name: "logMessageUsageURL", kind: "message", T: () => URLInfo },
            { no: 21, name: "spatialLookupURL", kind: "message", T: () => URLInfo },
            { no: 22, name: "realtimeTrafficProbeURL", kind: "message", T: () => URLInfo },
            { no: 23, name: "batchTrafficProbeURL", kind: "message", T: () => URLInfo },
            { no: 24, name: "proactiveRoutingURL", kind: "message", T: () => URLInfo },
            { no: 25, name: "logMessageUsageV3URL", kind: "message", T: () => URLInfo },
            { no: 26, name: "backgroundDispatcherURL", kind: "message", T: () => URLInfo },
            { no: 27, name: "bluePOIDispatcherURL", kind: "message", T: () => URLInfo },
            { no: 28, name: "backgroundRevGeoURL", kind: "message", T: () => URLInfo },
            { no: 29, name: "wifiConnectionQualityProbeURL", kind: "message", T: () => URLInfo },
            { no: 30, name: "muninBaseURL", kind: "message", T: () => URLInfo },
            { no: 31, name: "authProxyURL", kind: "message", T: () => URLInfo },
            { no: 32, name: "wifiQualityURL", kind: "message", T: () => URLInfo },
            { no: 33, name: "feedbackSubmissionURL", kind: "message", T: () => URLInfo },
            { no: 34, name: "feedbackLookupURL", kind: "message", T: () => URLInfo },
            { no: 35, name: "junctionImageServiceURL", kind: "message", T: () => URLInfo },
            { no: 36, name: "analyticsCohortSessionURL", kind: "message", T: () => URLInfo },
            { no: 37, name: "analyticsLongSessionURL", kind: "message", T: () => URLInfo },
            { no: 38, name: "analyticsShortSessionURL", kind: "message", T: () => URLInfo },
            { no: 39, name: "analyticsSessionlessURL", kind: "message", T: () => URLInfo },
            { no: 40, name: "webModuleBaseURL", kind: "message", T: () => URLInfo },
            { no: 41, name: "wifiQualityTileURL", kind: "message", T: () => URLInfo },
            { no: 42, name: "alternateResourcesURL", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => URLInfo },
            { no: 43, name: "tokenAuthenticationURL", kind: "message", T: () => URLInfo },
            { no: 44, name: "authenticatedClientFeatureFlagURL", kind: "message", T: () => URLInfo },
            { no: 45, name: "addressCorrectionTaggedLocationURL", kind: "message", T: () => URLInfo },
            { no: 46, name: "proactiveAppClipURL", kind: "message", T: () => URLInfo },
            { no: 47, name: "enrichmentSubmissionURL", kind: "message", T: () => URLInfo },
            { no: 48, name: "ugcLogDiscardURL", kind: "message", T: () => URLInfo },
            { no: 49, name: "batchReverseGeocoderPlaceRequestURL", kind: "message", T: () => URLInfo },
            { no: 50, name: "pressureProbeDataURL", kind: "message", T: () => URLInfo },
            { no: 51, name: "poiBusynessActivityCollectionURL", kind: "message", T: () => URLInfo },
            { no: 52, name: "rapWebBundleURL", kind: "message", T: () => URLInfo },
            { no: 53, name: "networkSelectionHarvestURL", kind: "message", T: () => URLInfo },
            { no: 54, name: "offlineDataBatchListURL", kind: "message", T: () => URLInfo },
            { no: 55, name: "offlineDataSizeURL", kind: "message", T: () => URLInfo },
            { no: 56, name: "offlineDataDownloadBaseURL", kind: "message", T: () => URLInfo },
            { no: 57, name: "bcxDispatcherURL", kind: "message", T: () => URLInfo }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message URLInfoSet
 */
export const URLInfoSet = new URLInfoSet$Type();
// @generated message type with reflection information, may provide speed optimized methods
class URLInfo$Type extends MessageType {
    constructor() {
        super("URLInfo", [
            { no: 1, name: "url", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "useAuthProxy", kind: "scalar", opt: true, T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "supportsMultipathTCP", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "alternativeMultipathTCPPort", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message URLInfo
 */
export const URLInfo = new URLInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ResourceFilter$Type extends MessageType {
    constructor() {
        super("ResourceFilter", [
            { no: 1, name: "scale", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["ResourceFilter.Scale", ResourceFilter_Scale] },
            { no: 2, name: "scenario", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["ResourceFilter.Scenario", ResourceFilter_Scenario] }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message ResourceFilter
 */
export const ResourceFilter = new ResourceFilter$Type();
// @generated message type with reflection information, may provide speed optimized methods
class MuninBucket$Type extends MessageType {
    constructor() {
        super("MuninBucket", [
            { no: 3, name: "bucketID", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "bucketURL", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "lodLevel", kind: "scalar", opt: true, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message MuninBucket
 */
export const MuninBucket = new MuninBucket$Type();
